CoM objectives
pyomeca/bioptim pull request #273
Opened 2021-01-13 19:41 UTC by EveCharbie

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [NA] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)? Except acados, but since I didn't touch it, if should be fine
2. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2021-01-13 19:44 UTC, EveCharbie commented
@pariterre I don't know if the Axe thing should also appear on the CoM position (it wouldn't be CoM height, but CoM position instead)

2021-01-13 22:22 UTC, pariterre requested changes
Awesome job! Thanks :D

2021-01-13 22:22 UTC, pariterre commented on bioptim/limits/penalty.py
> +                    CoM_dot_proj = CoM_dot[axis]
Indeed, since the logic is there, I accept your suggestion to call `minimize_com_height` `minimize_com_position` and add axis.

2021-01-13 22:22 UTC, pariterre commented on bioptim/limits/objective_functions.py
> +        MINIMIZE_COM_VELOCITY = (PenaltyType.MINIMIZE_COM_VELOCITY,)
I think it would make sense to add it also to constraints

2021-01-15 13:46 UTC, EveCharbie commented
@pariterre désolée j'avais oublié de [WIP], mais là ca devrait être bon :)

2021-01-15 19:57 UTC, pariterre reviewed
Let's just answer the last comment and we are good!

2021-01-15 19:57 UTC, pariterre commented on tests/test_global_torque_driven_with_contact_ocp.py
> +        np.testing.assert_almost_equal(f[0, 0], 0.458575464873056)
Why the values changed? I felt that the changes were cosmetic?

2021-01-15 20:43 UTC, pariterre commented on tests/test_global_torque_driven_with_contact_ocp.py
> +        np.testing.assert_almost_equal(f[0, 0], 0.458575464873056)
This was quadratic

2021-01-18 21:37 UTC, pariterre approved these changes
LGTM :)

2021-01-18 21:41 UTC, pariterre approved these changes

2021-01-18 21:57 UTC, pariterre commented
Is the [WIP] still relevant? I was about to merge :)

2021-01-18 22:11 UTC, EveCharbie commented
Nope! Chillos :)

2021-01-18 22:18 UTC, merged