implicit torque driven dynamics
pyomeca/bioptim pull request #409
Opened 2021-11-23 21:19 UTC by Ipuch

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2021-11-24 23:00 UTC, pariterre requested changes
GG so far!

2021-11-24 23:00 UTC, pariterre commented on bioptim/dynamics/integrator.py
> +        x = [states[0] if r == 0 else x_irk_points[(r - 1) * nx: r * nx] for r in range(self.degree + 1)]
Did you black? I

2021-11-24 23:00 UTC, pariterre commented on bioptim/dynamics/configure_problem.py
> +        name_taudot = [str(i) for i in range(nlp.model.nbGeneralizedTorque())]
good catch

2021-11-25 15:27 UTC, Ipuch commented on bioptim/dynamics/integrator.py
> +    Numerical integration using fourth order Runge-Kutta method.
Yes, it turns out it doesn't matter in implicit dynamics.

2021-11-25 15:28 UTC, Ipuch commented on bioptim/dynamics/integrator.py
> +        x = [states[0] if r == 0 else x_irk_points[(r - 1) * nx: r * nx] for r in range(self.degree + 1)]
no

2021-11-25 15:30 UTC, Ipuch commented on bioptim/dynamics/ode_solver.py
> +        A Runge-Kutta 4 solver
yes

2021-11-25 15:33 UTC, Ipuch commented on bioptim/dynamics/configure_problem.py
> +            ocp.implicit_constraints.add(ImplicitConstraintFcn.QDDOT, node=Node.ALL_SHOOTING)
If you want a more descriptive way, i would say QDDOT_EQUALS_FORWARD_DYNAMICS

2021-11-25 15:39 UTC, Ipuch commented on bioptim/dynamics/dynamics_functions.py
> +        dtau = horzcat(*[dtau for _ in range(dq.shape[1])])
added, I'm not sure what it can do indeed.

2021-11-25 17:48 UTC, pariterre commented on bioptim/dynamics/integrator.py
> +    Numerical integration using fourth order Runge-Kutta method.
I mean, you left the "fourth order" in the doc

2021-11-25 18:04 UTC, Ipuch commented on bioptim/dynamics/integrator.py
> +    Numerical integration using fourth order Runge-Kutta method.
yes i figured out

2021-11-26 13:59 UTC, pariterre requested changes
Looking good, please fix the introduced bug and add a tested example :) (could be an example using the soft contact, that would introduce two new features?)

2021-11-26 13:59 UTC, pariterre commented on bioptim/dynamics/dynamics_functions.py
> +        dtau = horzcat(*[dtau for _ in range(dq.shape[1])])
I just noticed that you introduced a bug, you changed ddq to dq! Please revert this back!

2021-11-26 13:59 UTC, pariterre commented on bioptim/gui/graph.py
> +                        print(f"*** Constraint: {constraint.name}")
Maybe `**** Implicit Constraint:..` ?

2021-11-26 14:34 UTC, Ipuch commented
This PR has been merged with #408 due to simultaneous development.

2021-11-26 14:34 UTC, closed without merging

2021-11-26 14:39 UTC, Ipuch commented on bioptim/gui/graph.py
> +                        print(f"*** Constraint: {constraint.name}")
done

2021-11-26 14:49 UTC, Ipuch commented on bioptim/dynamics/dynamics_functions.py
> +        dtau = horzcat(*[dtau for _ in range(dq.shape[1])])
I fixed it.