Ignored plots for phase_transition
pyomeca/bioptim pull request #433
Opened 2022-01-25 22:27 UTC by EveCharbie

I don't think it should be merged since it is really a patch and not a fix.
But this way it is available to others, in the mean time :)

2022-01-28 01:48 UTC, pariterre commented
If you do not think it worths merging there is not really a point to PR it, as anyone can still connect to your fork and merge locally even if no PR is open :)

2022-03-08 16:52 UTC, pariterre requested changes
GG so far! :)

2022-03-09 02:58 UTC, Ipuch commented
ready to merge @pariterre

2022-03-09 20:04 UTC, pariterre approved these changes
LGTM

2022-03-09 20:05 UTC, merged