added cost details to sol
pyomeca/bioptim pull request #440
Opened 2022-02-07 20:15 UTC by EveCharbie

2022-02-21 22:35 UTC, pariterre commented
I don't understand the purpose of "to_console"? What happens if you put False, doesn't it just print nothing (which kind of doesn't make sense)?

2022-02-21 23:52 UTC, EveCharbie commented
Yes, if to_console=False, nothing is print to the console but the values are added to sol. This might be great if you are multi-starting and want to log the console or if you want to be able to follow what is happening in the console with a print_level very low. However, I would understand if you prefer to remove this option.

2022-03-08 16:45 UTC, pariterre commented
As verbally discussed:
Please create a separate function as it is not intended that printing modifies anything internally. If you think your function shares things with this one, it makes sense to create subfunctions that can be called by both of them!

2022-03-08 17:41 UTC, pariterre requested changes
See previous comment

2022-03-09 17:17 UTC, EveCharbie commented
I'm on black version :
black                     22.1.0             pyhd8ed1ab_0    conda-forge
And no file would have been changed on my computer :/

2022-03-11 16:28 UTC, pariterre requested changes
> Reviewed 3 of 3 files at r2, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/440)* status: all files reviewed, 2 unresolved discussions (waiting on @EveCharbie)

___
*[README.md, line 356 at r3](https://reviewable.io/reviews/pyomeca/bioptim/440#-MxtmbzP9fBHnrS02MMJ:-MxtmbzP9fBHnrS02MMK:bq1d4ye) ([raw file](https://github.com/pyomeca/bioptim/blob/d7f79455cc7ac268d22748c4528f1ed702086abd/README.md#L356)):*
> ```Markdown
> ```python
> sol.print_cost()  # For printing their values in the console
> sol.detailed_cost_values_to_sol()  # For adding the objectives details to sol for later manipulations
> ```

sol.compute_detailed_cost_values() (to sol is redundant)
___
*[tests/test_global_getting_started.py, line 74 at r3](https://reviewable.io/reviews/pyomeca/bioptim/440#-MxtnSPDBCqaCVM5vB3L:-MxtnSPDBCqaCVM5vB3M:bks0u3t) ([raw file](https://github.com/pyomeca/bioptim/blob/d7f79455cc7ac268d22748c4528f1ed702086abd/tests/test_global_getting_started.py#L74)):*
> ```Python
>         # detailed cost values
>         sol.detailed_cost_values_to_sol()
>         np.testing.assert_almost_equal(sol.detailed_cost[0]['cost_value_weighted'], 41.57063948309302)
> ```

Maybe to help for future, instead of hard coding the value, you can compare it to f[0, 0] that is already valided? Like that if it ever change, we won't have to update the 2 lines for each test that changed?


<!-- Sent from Reviewable.io -->

2022-03-11 16:29 UTC, pariterre commented
I like what you have done so far, I think it is a great addition :)

2022-03-24 01:04 UTC, EveCharbie commented
@pariterre are we good with this?

2022-03-24 14:54 UTC, pariterre commented
This commit https://github.com/pyomeca/bioptim/pull/440/commits/27eeac35db8f62ebe335e8dd69b787f2ba25e2ab
removed the folder "external" it is not possible anymore to use ACADOS. Please revert to the previous commit and recommit your last commit (I can help if you are affraid of losing work)

2022-03-24 15:35 UTC, EveCharbie commented
I'm so sorry it happened again!
Is it ok now?

2022-03-24 15:50 UTC, pariterre commented
@EveCharbie 
Unfortunately Submodules can't only be "revert", you have to checkout to the previous commit, then recommit the stuff you need to keep. Please note, that this process CAN lose work. I am availble if need to make sure you don't loose work ;)

2022-03-25 18:40 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 7 files at r4, 3 of 7 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/440#-:-Mz1NHJ63c4B2DfcBp0L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-03-30 13:47 UTC, pariterre approved these changes
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/440)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-03-30 13:48 UTC, merged