Readme update
pyomeca/bioptim pull request #458
Opened 2022-04-20 14:47 UTC by Ipuch

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

related to #416

2022-04-21 20:49 UTC, Ipuch commented
Still need to leverage some challenges:
* [ ] Handle targets with trapezoidal integration
* [ ] IPOPT seems to compute the objectives differently compared to sol.print_cost()
* [ ] make the test work.
* [ ] if control are constant (ControlType.CONSTANT) then integration should be the same in trapezoidal and rectangle

2022-04-25 21:59 UTC, Ipuch commented
still a weird bad file descriptor

2022-04-26 22:21 UTC, Ipuch commented
@pariterre, I think it started to be something now. I have to finalize the tests for the targets for each use case. Let me know if I need to modify something in the core.

2022-04-27 12:48 UTC, pariterre commented
@Ipuch  please update your branch to master

2022-04-27 13:22 UTC, pariterre requested changes
> Reviewed 4 of 10 files at r1, 3 of 6 files at r2, 7 of 7 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/458)* status: all files reviewed, 21 unresolved discussions (waiting on @Ipuch)

___
*[`README.md` line 329 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f3NSt6nTHRu1CS1I_:-N0f3NSuAhosjtlOfogW:bktrkkd) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/README.md#L329)):*
> ```Markdown
> To solve the ocp, you simply have to call the `solve()` method of the `ocp` class
> ```python
> solver=Solver.IPOPT(show_online_optim=True)
> ```

"r = S"
___
*[`bioptim/__init__.py` line 184 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f3c_36WvABBfrKZo3:-N0f3c_36WvABBfrKZo4:b-br154i) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/__init__.py#L184)):*
> ```Python
>     VariableType,
>     SolutionIntegrator,
>     IntegralApproximation,
> ```

I feel that "Integral" is the value of an "Integration", but I may be wrong... Inuitively it makes more sense to me to call it "IntegrationApproximation" as it is the process of integration which is approximate
___
*[`bioptim/examples/getting_started/pendulum.py` line 111 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f3t7bA_nxtNiRkEHW:-N0f3t7bA_nxtNiRkEHX:b66flsp) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/examples/getting_started/pendulum.py#L111)):*
> ```Python
> 
>     # Custom plots
>     ocp.add_plot_penalty(CostType.OBJECTIVES)
> ```

Please do not change, apart for good reasons, the behavior of example. If you want to try something you can create a "sandbox" folder and it will automatically be ignore for your push
___
*[`bioptim/examples/getting_started/pendulum.py` line 117 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f477QB78I_QxRjjj_:-N0f477QB78I_QxRjjja:buo9nmt) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/examples/getting_started/pendulum.py#L117)):*
> ```Python
> 
>     # --- Solve the ocp --- #
>     sol = ocp.solve(Solver.IPOPT(show_online_optim=False))
> ```

Same here
___
*[`bioptim/gui/plot.py` line 62 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f4AqRB9PlwXOl6A8s:-N0f4AqRB9PlwXOl6A8t:b-j8v55h) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/gui/plot.py#L62)):*
> ```Python
>         label: list = None,
>         compute_derivative: bool = False,
>         integration_rule: IntegralApproximation = IntegralApproximation.RECTANGLE,
> ```

Should trapezoidal be the default? 
___
*[`bioptim/interfaces/ipopt_interface.py` line 214 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f4f3rAwD6GoIjHkCD:-N0f4f3rAwD6GoIjHkCE:bmo1q4w) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/interfaces/ipopt_interface.py#L214)):*
> ```Python
> 
>     def __get_all_penalties(self, nlp, penalties):
>         def format_target(target_in: list) -> np.array:
> ```

Thx for that :)
___
*[`bioptim/interfaces/ipopt_interface.py` line 294 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f5gZB5EF5c2yIxysD:-N0f5gZB5EF5c2yIxysE:b5fr45i) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/interfaces/ipopt_interface.py#L294)):*
> ```Python
>                             target0 = format_target(penalty.target[0:1])
>                             target1 = format_target(penalty.target[1:])
>                             target = np.vstack((target0, target1)).T
> ```

This should be 
target0 = penalty.target[0] 
target1 = penalty.target[1]

Otherwise, what is the point of separating them in a list?



_Code quote:_
```Python
                            target0 = format_target(penalty.target[0:1])
                            target1 = format_target(penalty.target[1:])
                            target = np.vstack((target0, target1)).T
```
___
*[`bioptim/limits/objective_functions.py` line 260 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f5sJm1fUlUe0IvoGb:-N0f5sJm1fUlUe0IvoGc:b-ckf3dh) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/objective_functions.py#L260)):*
> ```Python
>             raise ValueError("'list_index' must be defined properly")
> 
>         ocp_or_nlp.J[list_index].target = [new_target]
> ```

What if the user already sent the second target (already a list)?
___
*[`bioptim/limits/penalty.py` line 85 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f63ne1ihSxto1yCS-:-N0f63ne1ihSxto1yCS0:bj3f9zb) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty.py#L85)):*
> ```Python
>             penalty.quadratic = True if penalty.quadratic is None else penalty.quadratic
>             if penalty.integration_rule == IntegralApproximation.RECTANGLE:
>                 penalty.add_target_to_plot(all_pn=all_pn, combine_to=f"{key}_controls")
> ```

Please add a todo so we remember some day to implement when it is not rectangle
___
*[`bioptim/limits/penalty_option.py` line 169 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f6Lgh6BmGpF5TbIkm:-N0f6Lgh6BmGpF5TbIkn:b-flqfx6) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L169)):*
> ```Python
>             if len(self.target) == 1 and self.integration_rule == IntegralApproximation.TRAPEZOIDAL:
>                 if self.node == Node.ALL or self.node == Node.DEFAULT:
>                     self.target = [self.target[0][:, :-1], self.target[0][:, 1:]]
> ```

See, you are doing it here already, that should not be done in IPOPT_INTERFACE
___
*[`bioptim/limits/penalty_option.py` line 173 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f6W7c4bcJ9CfOr2xY:-N0f6W7c4bcJ9CfOr2xZ:b-3kccz4) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L173)):*
> ```Python
>                     raise NotImplementedError(
>                         f"target with IntegralApproximation.TRAPEZOIDAL doesn't work with {self.node}, "
>                         "it only works if node is Node.NODE_ALL and Node.NODE_DEFAULT"
> ```

That is not true, the "automatic" does not work, but one can provide the two columns and it will (should) work. Please rephrase ("Trap needs the beginning and end column values except for NODE_ALL which can be automatically generated" or something like that



_Code quote:_
```Python
                    raise NotImplementedError(
                        f"target with IntegralApproximation.TRAPEZOIDAL doesn't work with {self.node}, "
                        "it only works if node is Node.NODE_ALL and Node.NODE_DEFAULT"
                    )
```
___
*[`bioptim/limits/penalty_option.py` line 179 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f7As18LMtWQnzByaS:-N0f7As18LMtWQnzByaT:bwe4uzt) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L179)):*
> ```Python
>         self.target_to_plot = None
>         # not implemented yet for trapezoidal integration
>         self.plot_target = False if self.integration_rule == IntegralApproximation.TRAPEZOIDAL else True
> ```

Add a todo
___
*[`bioptim/limits/penalty_option.py` line 298 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f7G7KEfFj1MRtaoqC:-N0f7G7KEfFj1MRtaoqD:b-aqav3g) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L298)):*
> ```Python
>         elif self.integration_rule == IntegralApproximation.TRAPEZOIDAL:
> 
>             for i in range(2):
> ```

 [...]

2022-04-27 14:34 UTC, Ipuch commented
*[`bioptim/__init__.py` line 184 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f3c_36WvABBfrKZo3:-N0fRH0U06KPf3ZP6xYT:b-7bwg2l) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/__init__.py#L184)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I feel that "Integral" is the value of an "Integration", but I may be wrong... Inuitively it makes more sense to me to call it "IntegrationApproximation" as it is the process of integration which is approximate
</blockquote></details>

IntegralApproximation is fine to me, What about NumericalIntegration ?


<!-- Sent from Reviewable.io -->

2022-04-27 14:36 UTC, Ipuch commented
*[`bioptim/examples/getting_started/pendulum.py` line 111 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f3t7bA_nxtNiRkEHW:-N0fRkU18juVpRwyEDQq:b-29ey7t) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/examples/getting_started/pendulum.py#L111)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please do not change, apart for good reasons, the behavior of example. If you want to try something you can create a "sandbox" folder and it will automatically be ignore for your push
</blockquote></details>

 Restored, Done.


<!-- Sent from Reviewable.io -->

2022-04-27 14:38 UTC, Ipuch commented
*[`bioptim/gui/plot.py` line 62 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f4AqRB9PlwXOl6A8s:-N0fRrUQ9qBOyuJ17KRA:b-hca3he) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/gui/plot.py#L62)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Should trapezoidal be the default? 
</blockquote></details>

If so it will change the value for every single test on an OCP and it will deprecate all the examples designed outside. But yes, let us try it as an option for now and when everybody agreed it is better, let's make the refactor.


<!-- Sent from Reviewable.io -->

2022-04-27 14:38 UTC, Ipuch commented
*[`bioptim/interfaces/ipopt_interface.py` line 214 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f4f3rAwD6GoIjHkCD:-N0fSP8F7ZVbEBo03lIm:bvpp70i) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/interfaces/ipopt_interface.py#L214)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Thx for that :)
</blockquote></details>

You're welcome


<!-- Sent from Reviewable.io -->

2022-04-27 14:42 UTC, Ipuch commented
*[`bioptim/limits/penalty.py` line 85 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f63ne1ihSxto1yCS-:-N0fTLeF2Oq8np3WkerJ:b-7rl0jd) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty.py#L85)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please add a todo so we remember some day to implement when it is not rectangle
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-04-27 14:52 UTC, Ipuch commented
*[`bioptim/misc/enums.py` line 136 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0fAK2iDyZMSw-DafHA:-N0fVULz5_48IkvF3KlD:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/misc/enums.py#L136)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I am not sure None makes sense...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 14:52 UTC, Ipuch commented
*[`bioptim/optimization/optimal_control_program.py` line 742 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0fAgvL1zjJ28z3v2en:-N0fVdXPCjhZNRZ5qNPc:bb77ufg) ([raw file](https://github.com/pyomeca/bioptim/blob/ab0bb6966732b4450989b338e38ffa0dff238c3a/bioptim/optimization/optimal_control_program.py#L742)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Just to confirm, this was removed because it shows the wrong result?
</blockquote></details>

Yes.


<!-- Sent from Reviewable.io -->

2022-04-27 14:59 UTC, Ipuch commented
*[`bioptim/limits/penalty_option.py` line 173 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f6W7c4bcJ9CfOr2xY:-N0fX4rpD0y0QkCK__zZ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L173)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

That is not true, the "automatic" does not work, but one can provide the two columns and it will (should) work. Please rephrase ("Trap needs the beginning and end column values except for NODE_ALL which can be automatically generated" or something like that
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-04-27 14:59 UTC, Ipuch commented
*[`bioptim/limits/penalty_option.py` line 179 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f7As18LMtWQnzByaS:-N0fXFWm2hn0WwCLRi8b:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L179)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add a todo
</blockquote></details>

done



_Code quote:_
```Python
# not implemented yet for trapezoidal integration
```


<!-- Sent from Reviewable.io -->

2022-04-27 15:02 UTC, Ipuch commented
*[`bioptim/limits/penalty_option.py` line 313 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f7S_58WY9b4-Klqgv:-N0fXoE48z-oejBXmYJR:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L313)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same. At least len(target).. How do you know it is 2, maybe we implemented polynomial integration?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-04-27 18:35 UTC, Ipuch commented
*[`bioptim/limits/penalty_option.py` line 430 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f9coj3Y5DOfZO_fh0:-N0gIjG7C0DmIDG-5Y5l:b-7rl0jd) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L430)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please give better naming
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-04-27 18:37 UTC, Ipuch commented
*[`bioptim/limits/penalty_option.py` line 467 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f9yzK5SNWTf7eVDqa:-N0gJ54y4LhvYdynPoC0:b-7rl0jd) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L467)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please remove this. 
expand only if the `expand` parameter is to True (see 10 lines later)
</blockquote></details>

done.


<!-- Sent from Reviewable.io -->

2022-04-27 18:40 UTC, Ipuch commented
*[`bioptim/limits/penalty_option.py` line 298 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f7G7KEfFj1MRtaoqC:-N0gJoYcBdN931FrLMzo:b-qy3qbu) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L298)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

for target in self.target

As a rule of thumb, if you find yourself writting "for ... in range(...)" in Python, you are probably doing something wrong
</blockquote></details>

yes, done.


<!-- Sent from Reviewable.io -->

2022-04-27 18:50 UTC, Ipuch commented
*[`bioptim/limits/penalty_option.py` line 426 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f8cH05BU0OkqkUouu:-N0gLntP9Z8C1CLcmViC:bj8c2xx) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L426)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why would you save that information?
</blockquote></details>

It has been simplified to ease the readiness of the code.


<!-- Sent from Reviewable.io -->

2022-04-27 18:51 UTC, Ipuch commented
*[`bioptim/limits/penalty_option.py` line 428 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f9K-B2N-OTcHVIs5c:-N0gM44f9aHcQdcKP4GU:bzfgmnr) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L428)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

why not do
`...("target", self.rows, self.cols + 1 if self.integration_rule == IntegralApproximation.TRAPEZOIDAL else 0)`?  which replaces the 5 lines before
</blockquote></details>

Done, self.rows is an array of indexes. I needed the size.


<!-- Sent from Reviewable.io -->

2022-04-27 19:17 UTC, Ipuch reviewed
ok done.

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/458#-:-N0gRMK1C3S-q7mo6U6D:b-7bhwlv)* status: 13 of 14 files reviewed, 21 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/interfaces/ipopt_interface.py` line 294 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f5gZB5EF5c2yIxysD:-N0gQqL7EfitVaAiGC6o:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/interfaces/ipopt_interface.py#L294)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should be 
target0 = penalty.target[0] 
target1 = penalty.target[1]

Otherwise, what is the point of separating them in a list?
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty_option.py` line 169 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f6Lgh6BmGpF5TbIkm:-N0gS3aREic04y14py6p:b-m3f8ce) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L169)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

See, you are doing it here already, that should not be done in IPOPT_INTERFACE
</blockquote></details>

I think I resolved that too
___
*[`bioptim/limits/penalty_option.py` line 325 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f7tQR-szVXZ1NS-Q3:-N0gRg3OCFzWAEHFHIOy:bn2ulxz) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L325)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Isn't it always true?
Again, how do you know there are exaclty 2 targets? If someone sends 3 or 4, what happens? I haven't see any control for that yet (maybe later)
</blockquote></details>

Now it is checked.


<!-- Sent from Reviewable.io -->

2022-04-29 19:31 UTC, pariterre requested changes
> Reviewed 10 of 10 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/458)* status: all files reviewed, 7 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/__init__.py` line 184 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f3c_36WvABBfrKZo3:-N0qnXdS2N_21ApVeYtF:be7yrp) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/__init__.py#L184)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

IntegralApproximation is fine to me, What about NumericalIntegration ?
</blockquote></details>

Let's leave it as is :)
___
*[`bioptim/gui/plot.py` line 62 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f4AqRB9PlwXOl6A8s:-N0qjXw_8taz5eCarVVj:b939gh7) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/gui/plot.py#L62)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

If so it will change the value for every single test on an OCP and it will deprecate all the examples designed outside. But yes, let us try it as an option for now and when everybody agreed it is better, let's make the refactor.
</blockquote></details>

To be done later
___
*[`bioptim/limits/objective_functions.py` line 260 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f5sJm1fUlUe0IvoGb:-N0qk-IT6pta75sHrQWC:birkzz4) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/objective_functions.py#L260)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Idk. Can you explain more? I've never put my finger into MHE until yesterday.
</blockquote></details>

This comment is not related to MHE, it is related to the user input
___
*[`bioptim/limits/penalty_option.py` line 298 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f7G7KEfFj1MRtaoqC:-N0qmeSSCMxhiQ4K3E3E:b-ntel1x) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L298)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

yes, done.
</blockquote></details>

for target in self.target



_Code quote:_
```Python
range(len
```
___
*[`bioptim/limits/penalty_option.py` line 426 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f8cH05BU0OkqkUouu:-N0qnbSO0K8imywnqPLB:b-xq8j84) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L426)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

It has been simplified to ease the readiness of the code.
</blockquote></details>

Please use the "is_integrated" I talk later
___
*[`bioptim/limits/penalty_option.py` line 659 at r6](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0qlzRg-Op2qIeR3wK0:-N0qlzRg-Op2qIeR3wK1:b5dfr4o) ([raw file](https://github.com/pyomeca/bioptim/blob/4c8487e56a85f0477835b63de8daeca97a8012d6/bioptim/limits/penalty_option.py#L659)):*
> ```Python
>                 all_pn.t[:-1]
>                 if (
>                     self.integration_rule == IntegralApproximation.TRAPEZOIDAL
> ```

You find yourself doing this check over and over and it is confusing. 
create a variable:
is_integrated = self.integration_rule == IntegralApproximation.TRAPEZOIDAL or self.integration_rule == IntegralApproximation.TRUE_TRAPEZOIDAL

and job done



_Code quote:_
```Python
                    self.integration_rule == IntegralApproximation.TRAPEZOIDAL
                    or self.integration_rule == IntegralApproximation.TRUE_TRAPEZOIDAL
```
___
*[`tests/test_cost_function_integration.py` line 148 at r6](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0qn-5NAawAI3SFVPg2:-N0qn-5NAawAI3SFVPg3:b-nvvo3r) ([raw file](https://github.com/pyomeca/bioptim/blob/4c8487e56a85f0477835b63de8daeca97a8012d6/tests/test_cost_function_integration.py#L148)):*
> ```Python
>     ocp = prepare_ocp(
>         biorbd_model_path=bioptim_folder + "/models/pendulum.bioMod",
>         n_shooting=30,
> ```

that seems a lot... 5? We don't care that the test actually converges... Ideally yes, but not at the expance of a test that is more than 5 to 10 seconds
___
*[`tests/test_cost_function_integration.py` line 381 at r6](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0qnFxR0bTAxHVmCC0M:-N0qnFxR0bTAxHVmCC0N:b-ppo1mw) ([raw file](https://github.com/pyomeca/bioptim/blob/4c8487e56a85f0477835b63de8daeca97a8012d6/tests/test_cost_function_integration.py#L381)):*
> ```Python
> 
>     solver = Solver.IPOPT()
>     solver.set_maximum_iterations(1)
> ```

I see, that was for to compensate the 30? Maybe 10 iterations so it leaves the beginning enough?


<!-- Sent from Reviewable.io -->

2022-04-29 20:15 UTC, Ipuch reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/458)* status: all files reviewed, 7 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/__init__.py` line 184 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f3c_36WvABBfrKZo3:-N0qqn12An_AqTcKUINl:b32wtd) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/__init__.py#L184)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Let's leave it as is :)
</blockquote></details>

ok
___
*[`bioptim/gui/plot.py` line 62 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f4AqRB9PlwXOl6A8s:-N0qqoebEBf_VXo_S5xP:b32wtd) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/gui/plot.py#L62)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be done later
</blockquote></details>

ok
___
*[`bioptim/limits/objective_functions.py` line 260 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f5sJm1fUlUe0IvoGb:-N0qxFsF7JH1DB3zIatQ:b-oce61j) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/objective_functions.py#L260)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This comment is not related to MHE, it is related to the user input
</blockquote></details>

modified as, 
[new_target] if not isinstance(new_target, list) else new_target
___
*[`bioptim/limits/penalty_option.py` line 298 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f7G7KEfFj1MRtaoqC:-N0qrRZz4Clh08HMHVOx:b5of7x5) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L298)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

for target in self.target
</blockquote></details>

Thx, done.
___
*[`bioptim/limits/penalty_option.py` line 426 at r3](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0f8cH05BU0OkqkUouu:-N0qrU_k1aIutxFllHAT:b-kbsj2b) ([raw file](https://github.com/pyomeca/bioptim/blob/60e4e1449278db2eaf4e10e5242b2102edb9565d/bioptim/limits/penalty_option.py#L426)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please use the "is_integrated" I talk later
</blockquote></details>

done, with is_trapezoidal
___
*[`bioptim/limits/penalty_option.py` line 659 at r6](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0qlzRg-Op2qIeR3wK0:-N0qsul7DAWJrZfD4iPO:b-7rl0jd) ([raw file](https://github.com/pyomeca/bioptim/blob/4c8487e56a85f0477835b63de8daeca97a8012d6/bioptim/limits/penalty_option.py#L659)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

You find yourself doing this check over and over and it is confusing. 
create a variable:
is_integrated = self.integration_rule == IntegralApproximation.TRAPEZOIDAL or self.integration_rule == IntegralApproximation.TRUE_TRAPEZOIDAL

and job done
</blockquote></details>

done.
___
*[`tests/test_cost_function_integration.py` line 148 at r6](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0qn-5NAawAI3SFVPg2:-N0qtAeD8-rdO3txHYwt:b2ni9bh) ([raw file](https://github.com/pyomeca/bioptim/blob/4c8487e56a85f0477835b63de8daeca97a8012d6/tests/test_cost_function_integration.py#L148)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

that seems a lot... 5? We don't care that the test actually converges... Ideally yes, but not at the expance of a test that is more than 5 to 10 seconds
</blockquote></details>

ok.
___
*[`tests/test_cost_function_integration.py` line 381 at r6](https://reviewable.io/reviews/pyomeca/bioptim/458#-N0qnFxR0bTAxHVmCC0M:-N0qtBh06uEmLqcZOvMe:b-qdrmpb) ([raw file](https://github.com/pyomeca/bioptim/blob/4c8487e56a85f0477835b63de8daeca97a8012d6/tests/test_cost_function_integration.py#L381)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I see, that was for to compensate the 30? Maybe 10 iterations so it leaves the beginning enough?
</blockquote></details>

ok. if you want, I picked 5 like the other one.


<!-- Sent from Reviewable.io -->

2022-05-04 20:02 UTC, pariterre requested changes
> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/458)* status: all files reviewed, 4 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/limits/objective_functions.py` line 275 at r7](https://reviewable.io/reviews/pyomeca/bioptim/458#-N1FeAE8ELv7pIqyKsqi:-N1FeAE8ELv7pIqyKsqj:b4g5725) ([raw file](https://github.com/pyomeca/bioptim/blob/e969c1409ff417065c06538af5ad2ef7536f9e88/bioptim/limits/objective_functions.py#L275)):*
> ```Python
>             raise ValueError("'list_index' must be defined properly")
> 
>         ocp_or_nlp.J[list_index].target = [new_target] if not isinstance(new_target, list) else new_target
> ```

Test for list and tuple
___
*[`bioptim/limits/penalty_option.py` line 316 at r7](https://reviewable.io/reviews/pyomeca/bioptim/458#-N1FeN9a-zEYaZk9zIC6:-N1FeN9a-zEYaZk9zIC7:bkirii8) ([raw file](https://github.com/pyomeca/bioptim/blob/e969c1409ff417065c06538af5ad2ef7536f9e88/bioptim/limits/penalty_option.py#L316)):*
> ```Python
>                 raise RuntimeError(f"targets with trapezoidal integration rule need to get a list of two elements.")
> 
>             for t in self.target:
> ```

please call "t" "target"


<!-- Sent from Reviewable.io -->

2022-05-04 20:40 UTC, Ipuch reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/458)* status: 13 of 15 files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/limits/objective_functions.py` line 275 at r7](https://reviewable.io/reviews/pyomeca/bioptim/458#-N1FeAE8ELv7pIqyKsqi:-N1Fg6YJ6DXD5_-f8RMm:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/e969c1409ff417065c06538af5ad2ef7536f9e88/bioptim/limits/objective_functions.py#L275)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Test for list and tuple
</blockquote></details>

done



_Code quote:_
```Python
        ocp_or_nlp.J[list_index].target = [new_target] if not isinstance(new_target, list) else new_target
```
___
*[`bioptim/limits/penalty_option.py` line 316 at r7](https://reviewable.io/reviews/pyomeca/bioptim/458#-N1FeN9a-zEYaZk9zIC6:-N1FgMwrBab25VeQEO38:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/e969c1409ff417065c06538af5ad2ef7536f9e88/bioptim/limits/penalty_option.py#L316)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please call "t" "target"
</blockquote></details>

done



_Code quote:_
```Python
for t in self.target:
```


<!-- Sent from Reviewable.io -->

2022-05-05 17:51 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/458#-:-N1KLE0u0qYnb2tv1nyu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)



<!-- Sent from Reviewable.io -->

2022-05-05 17:52 UTC, merged