merge master into crazydynamics
pyomeca/bioptim pull request #464
Opened 2022-05-06 19:19 UTC by Ipuch

2022-05-09 15:39 UTC, Ipuch commented
This is ready.

2022-05-09 15:52 UTC, Ipuch commented
mergeable :+1:

2022-05-12 19:06 UTC, pariterre requested changes
> Reviewed 3 of 4 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/464)* status: all files reviewed, 3 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/gui/graph.py` line 10 at r5](https://reviewable.io/reviews/pyomeca/bioptim/464#-N1tdAF_7LF9hZ1N04oY:-N1tdAF_7LF9hZ1N04oZ:b-xdbft3) ([raw file](https://github.com/pyomeca/bioptim/blob/ca46a030b1cdc327023ed0c1e93093fcaf6e7c13/bioptim/gui/graph.py#L10)):*
> ```Python
> from ..optimization.parameters import Parameter
> from ..misc.enums import Node
> from bioptim import InterpolationType
> ```

Please refer using local and not installed (..SOMETHING)
___
*[`bioptim/gui/graph.py` line 418 at r5](https://reviewable.io/reviews/pyomeca/bioptim/464#-N1tdQJ70WMUym7w-KZO:-N1tdQJ70WMUym7w-KZP:b3wvg8k) ([raw file](https://github.com/pyomeca/bioptim/blob/ca46a030b1cdc327023ed0c1e93093fcaf6e7c13/bioptim/gui/graph.py#L418)):*
> ```Python
>             title = ["", "Bounds"]
>         elif bounds.type == InterpolationType.LINEAR:
>             title = ["", "Beginning", "End"]
> ```

Please use a "else" with a raise NotImplementedError to encapsulate all the non implemented cases



_Code quote:_
```Python
        if bounds.type == InterpolationType.CONSTANT_WITH_FIRST_AND_LAST_DIFFERENT:
            title = ["", "Beginning", "Middle", "End"]
        elif bounds.type == InterpolationType.CONSTANT:
            title = ["", "Bounds"]
        elif bounds.type == InterpolationType.LINEAR:
            title = ["", "Beginning", "End"]
```
___
*[`tests/test_penalty.py` line 64 at r5](https://reviewable.io/reviews/pyomeca/bioptim/464#-N1teHnY7xS7IsQJ0Wqj:-N1teHnY7xS7IsQJ0Wqk:bh2xi5x) ([raw file](https://github.com/pyomeca/bioptim/blob/ca46a030b1cdc327023ed0c1e93093fcaf6e7c13/tests/test_penalty.py#L64)):*
> ```Python
> 
>     nu = nu * 2 if implicit else nu
>     nu = nu + 3 if implicit and with_contact else nu
> ```

```
if implicit:
    nu *=2
    if with_contact:
        nu += 3
```



_Code quote:_
```Python
    nu = nu * 2 if implicit else nu
    nu = nu + 3 if implicit and with_contact else nu
```


<!-- Sent from Reviewable.io -->

2022-05-12 21:15 UTC, Ipuch reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/464)* status: all files reviewed, 3 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/gui/graph.py` line 10 at r5](https://reviewable.io/reviews/pyomeca/bioptim/464#-N1tdAF_7LF9hZ1N04oY:-N1u6urA6oz9ffxPxbT5:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/ca46a030b1cdc327023ed0c1e93093fcaf6e7c13/bioptim/gui/graph.py#L10)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please refer using local and not installed (..SOMETHING)
</blockquote></details>

done
___
*[`bioptim/gui/graph.py` line 418 at r5](https://reviewable.io/reviews/pyomeca/bioptim/464#-N1tdQJ70WMUym7w-KZO:-N1u6a8ODYzD30COwu9H:b-x631op) ([raw file](https://github.com/pyomeca/bioptim/blob/ca46a030b1cdc327023ed0c1e93093fcaf6e7c13/bioptim/gui/graph.py#L418)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please use a "else" with a raise NotImplementedError to encapsulate all the non implemented cases
</blockquote></details>

There is no error if not executed. So I placed a "else return"
___
*[`tests/test_penalty.py` line 64 at r5](https://reviewable.io/reviews/pyomeca/bioptim/464#-N1teHnY7xS7IsQJ0Wqj:-N1u6wJK-qnYQIYT3Gyk:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/ca46a030b1cdc327023ed0c1e93093fcaf6e7c13/tests/test_penalty.py#L64)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

```
if implicit:
    nu *=2
    if with_contact:
        nu += 3
```
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-05-13 14:39 UTC, pariterre requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/464)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/gui/graph.py` line 418 at r5](https://reviewable.io/reviews/pyomeca/bioptim/464#-N1tdQJ70WMUym7w-KZO:-N1xqjsK2d7GLB6xcERc:b3hb6zd) ([raw file](https://github.com/pyomeca/bioptim/blob/ca46a030b1cdc327023ed0c1e93093fcaf6e7c13/bioptim/gui/graph.py#L418)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

There is no error if not executed. So I placed a "else return"
</blockquote></details>

That is exactly the problem, it should create an error, as the other case (that we did not think of yet) may create a problem some day. The NotImplemented case should be raise and not just a return


<!-- Sent from Reviewable.io -->

2022-05-13 15:58 UTC, Ipuch reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/464)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/gui/graph.py` line 418 at r5](https://reviewable.io/reviews/pyomeca/bioptim/464#-N1tdQJ70WMUym7w-KZO:-N1y85VW6N02fIoCSWhz:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/ca46a030b1cdc327023ed0c1e93093fcaf6e7c13/bioptim/gui/graph.py#L418)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

That is exactly the problem, it should create an error, as the other case (that we did not think of yet) may create a problem some day. The NotImplemented case should be raise and not just a return
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2022-05-13 18:07 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 7 files at r7, 5 of 5 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/464#-:-N1yageIDcKKmp-IOAjc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)



<!-- Sent from Reviewable.io -->

2022-05-13 18:07 UTC, merged