Terminology PR
pyomeca/bioptim pull request #465
Opened 2022-05-09 16:13 UTC by Ipuch

Enhanced terminology for algebraic constraints.

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/465)

2022-05-18 18:46 UTC, Ipuch commented
ready to be reviewed

2022-05-19 17:40 UTC, pariterre requested changes
> Reviewed 5 of 10 files at r5, 1 of 4 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/465)* status: all files reviewed, 8 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/dynamics/configure_problem.py` line 109 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SHj1e4fJYDEwpgoRY:-N2SHj1e4fJYDEwpgoRZ:bqza902) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L109)):*
> ```Python
>         with_contact: bool = False,
>         rigidbody_dynamics: Transcription = Transcription.ODE,
>         soft_contacts_dynamics: Transcription = Transcription.ODE,
> ```

`rigidbody_dynamics: RigidBodyDynamics = RigidBodyDynamics .ODE`
`soft_contacts_dynamics: SoftContactDynamics = SoftContactDynamics .ODE`



_Code quote:_
```Python
        rigidbody_dynamics: Transcription = Transcription.ODE,
        soft_contacts_dynamics: Transcription = Transcription.ODE,
```
___
*[`bioptim/dynamics/configure_problem.py` line 133 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SHzse9j7APsFkS3Nn:-N2SHzse9j7APsFkS3No:b-up28mh) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L133)):*
> ```Python
>             soft_contacts_dynamics != Transcription.CONSTRAINT
>             and soft_contacts_dynamics != Transcription.ODE
>             and nlp.model.nbSoftContacts() != 0
> ```

Put nbSoftContacts first
___
*[`bioptim/dynamics/configure_problem.py` line 140 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SIJIn-0ZEjgHhuZqb:-N2SIJIn-0ZEjgHhuZqc:bsn5o6t) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L140)):*
> ```Python
> 
>         if rigidbody_dynamics == Transcription.CONSTRAINT_ID:
>             if soft_contacts_dynamics == Transcription.ODE and nlp.model.nbSoftContacts() != 0:
> ```

Put soft contact in a factored if
___
*[`bioptim/dynamics/configure_problem.py` line 151 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SIcGN9VB03yFGdVrL:-N2SIcGN9VB03yFGdVrM:bx8i5vu) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L151)):*
> ```Python
>         ConfigureProblem.configure_qdot(nlp, True, False)
>         ConfigureProblem.configure_tau(nlp, False, True, fatigue)
>         if rigidbody_dynamics == Transcription.CONSTRAINT_FD or rigidbody_dynamics == Transcription.CONSTRAINT_ID:
> ```

LONG name
___
*[`bioptim/dynamics/configure_problem.py` line 153 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SIs5EBaWghz5iB-Yh:-N2SIs5EBaWghz5iB-Yi:b-7r38kq) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L153)):*
> ```Python
>         if rigidbody_dynamics == Transcription.CONSTRAINT_FD or rigidbody_dynamics == Transcription.CONSTRAINT_ID:
>             ConfigureProblem.configure_qddot(nlp, False, True)
>         if (
> ```

elif?
___
*[`bioptim/dynamics/configure_problem.py` line 259 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SKz0E5oixIi0Mep-k:-N2SKz0E5oixIi0Mep-l:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L259)):*
> ```Python
>             soft_contacts_dynamics != Transcription.CONSTRAINT
>             and soft_contacts_dynamics != Transcription.ODE
>             and nlp.model.nbSoftContacts() != 0
> ```

same
___
*[`bioptim/examples/getting_started/example_implicit_dynamics.py` line 78 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SLBG2CJO4xGHreoTC:-N2SLBG2CJO4xGHreoTD:b-srosnb) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/examples/getting_started/example_implicit_dynamics.py#L78)):*
> ```Python
> 
>     # Be careful to let the accelerations not to much bounded to find the same solution in implicit dynamics
>     if rigidbody_dynamics == Transcription.CONSTRAINT_ID or rigidbody_dynamics == Transcription.CONSTRAINT_FD:
> ```

CONTRAINT_INVERSE_DYNAMICS
___
*[`bioptim/misc/enums.py` line 145 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SOGn3EHwW0xEcc1ug:-N2SOGn3EHwW0xEcc1uh:b-l8g1z1) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/misc/enums.py#L145)):*
> ```Python
>     ODE = "ode"
>     CONSTRAINT = "constraint"
>     CONSTRAINT_ID = "constraint_id"
> ```

```python
class RigidBodyDynamics(Enum):
    ODE = "ode"
    DAE_INVERSE_DYNAMICS = "dae_inverse_dynamics"
    DAE_FORWARD_DYNAMICS = "dae_forward_dynamics"
    DAE_INVERSE_DYNAMICS_JERK = "dae_inverse_dynamics_jerk"
    DAE_FORWARD_DYNAMICS_JERK = "dae_forward_dynamics_jerk"
```



_Code quote:_
```Python
class Transcription(Enum):
    ODE = "ode"
    CONSTRAINT = "constraint"
    CONSTRAINT_ID = "constraint_id"
    CONSTRAINT_FD = "constraint_fd"
    CONSTRAINT_ID_JERK = "constraint_id_jerk"
    CONSTRAINT_FD_JERK = "constraint_fd_jerk"
```


<!-- Sent from Reviewable.io -->

2022-05-19 20:01 UTC, Ipuch reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/465)* status: 2 of 17 files reviewed, 8 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 109 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SHj1e4fJYDEwpgoRY:-N2Sh9bD0K--ChanJ5pn:b-7rl0jd) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L109)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`rigidbody_dynamics: RigidBodyDynamics = RigidBodyDynamics .ODE`
`soft_contacts_dynamics: SoftContactDynamics = SoftContactDynamics .ODE`
</blockquote></details>

done.
___
*[`bioptim/dynamics/configure_problem.py` line 133 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SHzse9j7APsFkS3Nn:-N2Sh8B54gUt2hVkEQqt:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L133)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put nbSoftContacts first
</blockquote></details>

done
___
*[`bioptim/dynamics/configure_problem.py` line 140 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SIJIn-0ZEjgHhuZqb:-N2ShBGh7ytSYnbw7EQf:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L140)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put soft contact in a factored if
</blockquote></details>

done
___
*[`bioptim/dynamics/configure_problem.py` line 151 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SIcGN9VB03yFGdVrL:-N2ShCOv6IiLAsWieFDL:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L151)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

LONG name
</blockquote></details>

done
___
*[`bioptim/dynamics/configure_problem.py` line 153 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SIs5EBaWghz5iB-Yh:-N2ShPIr7EpbveB1aq4q:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L153)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

elif?
</blockquote></details>

done
___
*[`bioptim/dynamics/configure_problem.py` line 259 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SKz0E5oixIi0Mep-k:-N2ShQgG0GfY91lxyTMq:bb7f2mf) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/dynamics/configure_problem.py#L259)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

same
</blockquote></details>

done
___
*[`bioptim/examples/getting_started/example_implicit_dynamics.py` line 78 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SLBG2CJO4xGHreoTC:-N2SuKQDArm_89OeJgVp:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/examples/getting_started/example_implicit_dynamics.py#L78)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

CONTRAINT_INVERSE_DYNAMICS
</blockquote></details>

Done
___
*[`bioptim/misc/enums.py` line 145 at r7](https://reviewable.io/reviews/pyomeca/bioptim/465#-N2SOGn3EHwW0xEcc1ug:-N2SuJ0m2HB0n6oEPagl:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/186112d9924e54254da7830fed1e5dddcf0d0458/bioptim/misc/enums.py#L145)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

```python
class RigidBodyDynamics(Enum):
    ODE = "ode"
    DAE_INVERSE_DYNAMICS = "dae_inverse_dynamics"
    DAE_FORWARD_DYNAMICS = "dae_forward_dynamics"
    DAE_INVERSE_DYNAMICS_JERK = "dae_inverse_dynamics_jerk"
    DAE_FORWARD_DYNAMICS_JERK = "dae_forward_dynamics_jerk"
```
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2022-05-19 20:08 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 15 of 15 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/465#-:-N2SvtAh4bAj-wYml2Zz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)



<!-- Sent from Reviewable.io -->

2022-05-19 20:09 UTC, merged