[WIP] Continuity objective
pyomeca/bioptim pull request #480
Opened 2022-06-08 15:04 UTC by Sciancisco

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

Related to #479

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/480)

2022-06-08 15:37 UTC, pariterre requested changes
GG so far

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480#-:-N42xajS26TNzvZgUOB2:b98zdim)* status: all files reviewed, 20 unresolved discussions (waiting on @Sciancisco)

___
*[`bioptim/dynamics/configure_problem.py` line 148 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42scFB5vhqUNYrRXbS:-N42scFB5vhqUNYrRXbT:b-8ir89f) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L148)):*
> ```Python
>                 ImplicitConstraintFcn.TAU_EQUALS_INVERSE_DYNAMICS,
>                 node=Node.ALL_SHOOTING,
>                 penalty_type=PenaltyType.IMPLICIT,
> ```

I think they can stay constraint as they are definitely constraints and not generic penalty
___
*[`bioptim/dynamics/configure_problem.py` line 174 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42skZpANDCEO99rWfz:-N42skZpANDCEO99rWg-:b-8ir89f) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L174)):*
> ```Python
>                 ImplicitConstraintFcn.SOFT_CONTACTS_EQUALS_SOFT_CONTACTS_DYNAMICS,
>                 node=Node.ALL_SHOOTING,
>                 penalty_type=PenaltyType.IMPLICIT,
> ```

I think they can stay constraint as they are definitely constraints and not generic penalty
___
*[`bioptim/dynamics/configure_problem.py` line 222 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42slWjAKDu9S0oDYEN:-N42slWjAKDu9S0oDYEO:b-8ir89f) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L222)):*
> ```Python
>                 ImplicitConstraintFcn.TAU_EQUALS_INVERSE_DYNAMICS,
>                 node=Node.ALL_SHOOTING,
>                 penalty_type=PenaltyType.IMPLICIT,
> ```

I think they can stay constraint as they are definitely constraints and not generic penalty
___
*[`bioptim/dynamics/configure_problem.py` line 247 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42sm1TEXZIgcCqArJH:-N42sm1TEXZIgcCqArJI:b-8ir89f) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L247)):*
> ```Python
>                 ImplicitConstraintFcn.SOFT_CONTACTS_EQUALS_SOFT_CONTACTS_DYNAMICS,
>                 node=Node.ALL_SHOOTING,
>                 penalty_type=PenaltyType.IMPLICIT,
> ```

I think they can stay constraint as they are definitely constraints and not generic penalty
___
*[`bioptim/gui/plot.py` line 693 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42svaPBkgMcuqz2hNK:-N42svaPBkgMcuqz2hNL:brb7dc1) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/gui/plot.py#L693)):*
> ```Python
>                     for i_var in range(self.variable_sizes[i][key]):
> 
>                         if self.plot_func[key][i].parameters["penalty"].multinode_penalty:
> ```

Don't you need to create two list? one `multinode_objective` and one `multinode_constraint`? I discuss this later... I see the problem
___
*[`bioptim/limits/constraints.py` line 101 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42tFor7okI7V3mB8s4:-N42tFor7okI7V3mB8s5:b5okzal) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/constraints.py#L101)):*
> ```Python
>             pool = all_pn.nlp.g if all_pn is not None and all_pn.nlp else all_pn.ocp.g
>         else:
>             raise ValueError(f"Invalid penalty type {self.penalty_type}.")
> ```

f"Invalid constraint type {self.penalty_type}."



_Code quote:_
```Python
f"Invalid penalty type {self.penalty_type}."
```
___
*[`bioptim/limits/constraints.py` line 543 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42tNNG4Yvgwaa85PaL:-N42tNNG4Yvgwaa85PaM:b-9dri7q) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/constraints.py#L543)):*
> ```Python
> 
> 
> class ConstraintContinuityFunctions:
> ```

Changing the name of this function does not feel it is required. We are in the Constraint file...



_Code quote:_
```Python
ConstraintContinuityFunctions
```
___
*[`bioptim/limits/multinode_constraint.py` line 8 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42trMj5OlHOJCa_-Nb:-N42trMj5OlHOJCa_-Nc:b-s2ijrs) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/multinode_constraint.py#L8)):*
> ```Python
> 
> 
> class MultinodeConstraint(MultinodePenalty, Constraint):  # call MultinodePenalty methods first
> ```

The comment is useless. 
Is the Constraint inheritance necessary? Probably...



_Code quote:_
```Python
MultinodePenalty, Constraint
```
___
*[`bioptim/limits/multinode_constraint.py` line 35 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42tjBp9zieywUQAcy-:-N42tjBp9zieywUQAcy0:b-607llo) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/multinode_constraint.py#L35)):*
> ```Python
>             The delta time
>         node_idx: int
>             The index of the node in nlp pre
> ```

Don't forget to black the code



_Code quote:_
```Python
        A placeholder for a multi node constraints

        Attributes
        ----------
        min_bound: list
            The minimal bound of the multi node constraints
        max_bound: list
            The maximal bound of the multi node constraints
        bounds: Bounds
            The bounds (will be filled with min_bound/max_bound)
        weight: float
            The weight of the cost function
        quadratic: bool
            If the objective function is quadratic
        phase_first_idx: int
            The first index of the phase of concern
        phase_second_idx: int
            The second index of the phase of concern
        first_node: Node
            The kind of the first node
        second_node: Node
            The kind of the second node
        dt: float
            The delta time
        node_idx: int
            The index of the node in nlp pre
        multinode_constraint: Union[Callable, Any]
            The nature of the cost function is the multi node constraint
        penalty_type: PenaltyType
            If the penalty is from the user or from bioptim (implicit or internal)
        """
```
___
*[`bioptim/limits/multinode_constraint.py` line 48 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42u8zPBI-BseJmgMCC:-N42u8zPBI-BseJmgMCD:b-n7ddxc) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/multinode_constraint.py#L48)):*
> ```Python
>         first_node: Union[Node, int],
>         second_node: Union[Node, int],
>         multinode_penalty: Union[Callable, Any] = None,
> ```

This should remain multinode_constraint for the constraints (later it gets:  `multinode_penalty=multinode_constraint`



_Code quote:_
```Python
multinode_penalty
```
___
*[`bioptim/limits/objective_functions.py` line 278 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42uooH2ej4-D8Kf7DE:-N42uooI5q9jp0IU4-J4:b-doanc9) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/objective_functions.py#L278)):*
> ```Python
> 
>     @staticmethod
>     def inner_phase_continuity(ocp):
> ```

Does this make sense as an objective? It is already an enforced Constraint (which is stronger than an objective)



_Code quote:_
```Python
    @staticmethod
    def inner_phase_continuity(ocp):
```
___
*[`bioptim/limits/objective_functions.py` line 295 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42v2855dTPtQfTQ5kj:-N42v2855dTPtQfTQ5kk:b-doanc9) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/objective_function [...]

2022-06-09 11:48 UTC, Ipuch commented
Yes, I will review it, what are the points I should focus on ?

2022-06-09 13:05 UTC, pariterre commented
@Ipuch Just making sure it does not break the other branch

2022-06-09 15:37 UTC, Sciancisco reviewed
Thank you!

To keep in mind for second round of review, for now I am mainly trying to breach the regression caused by the changes (i.e. make MultinodeConstraint work again).

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480#-:-N48008w8QWg37VGFDC5:b-z9hgcp)* status: 16 of 18 files reviewed, 20 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 148 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42scFB5vhqUNYrRXbS:-N47pOnoCgvracT2sjsu:bo96x4n) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L148)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I think they can stay constraint as they are definitely constraints and not generic penalty
</blockquote></details>

I changed them from ConstraintType to PenaltyType because it was called directly in what would become MultinodePenalty which would break the abstraction.

Furthermore, as a general comment, I would argue that if the problem is formulated with Continuity as an Objective, an implicit constraint becomes an implicit objective.
___
*[`bioptim/dynamics/configure_problem.py` line 174 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42skZpANDCEO99rWfz:-N480j3L3IZqWrdEaSa7:b-gr8aje) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L174)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I think they can stay constraint as they are definitely constraints and not generic penalty
</blockquote></details>

see reply to line 148
___
*[`bioptim/dynamics/configure_problem.py` line 222 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42slWjAKDu9S0oDYEN:-N480lY-5mKqe8HU-Hez:b-gr8aje) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L222)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I think they can stay constraint as they are definitely constraints and not generic penalty
</blockquote></details>

see reply to line 148
___
*[`bioptim/dynamics/configure_problem.py` line 247 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42sm1TEXZIgcCqArJH:-N480ohK-sFZICjFpnsp:b-gr8aje) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L247)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I think they can stay constraint as they are definitely constraints and not generic penalty
</blockquote></details>

see reply to line 148
___
*[`bioptim/gui/plot.py` line 693 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42svaPBkgMcuqz2hNK:-N442i5w273ryn2VOCjH:b-5vuyhr) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/gui/plot.py#L693)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Don't you need to create two list? one `multinode_objective` and one `multinode_constraint`? I discuss this later... I see the problem
</blockquote></details>

Maybe, that was changed by the refactoring tool. I think it is a problem for later, when the back-end stabilizes with the new feature.
___
*[`bioptim/limits/constraints.py` line 101 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42tFor7okI7V3mB8s4:-N47srejDipbgXd-aEFI:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/constraints.py#L101)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

f"Invalid constraint type {self.penalty_type}."
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 543 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42tNNG4Yvgwaa85PaL:-N47stLs4DlVWLiDno8Q:baw0zn) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/constraints.py#L543)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Changing the name of this function does not feel it is required. We are in the Constraint file...
</blockquote></details>

I changed it to mirror it in objective_functions.py to add continuity to objectives rather than constraints.
___
*[`bioptim/limits/multinode_constraint.py` line 8 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42trMj5OlHOJCa_-Nb:-N440B3Z3qFTl-DcarcD:b-ja8z7) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/multinode_constraint.py#L8)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

The comment is useless. 
Is the Constraint inheritance necessary? Probably...
</blockquote></details>

MultinodeConstraint used to inherit only of Constraint. With the introduction of MultinodePenalty, MultinodeConstraint now has to inherit both and eventually MultinodeObjective will inherit from MultinodePenalty and Objective.

From what I understood, it is the definition of `add_or_replace_to_penalty_pool` that decides what goes in constraints and what goes in objectives.

For now, on example `example_multinode_constraint`it fails to set `self.type`.

I added the comment to highlight that even though both MultinodePenalty and Constraint redefined `add_or_replace_to_penalty_pool`, this will make it so that `MultinodePenalty._add_penalty_to_pool` is called rather then `Constraint._add_penalty_to_pool` since before `MultinodeConstraint` did redined `Constraint`'s `_add_penalty_to_pool`.
___
*[`bioptim/limits/multinode_constraint.py` line 35 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42tjBp9zieywUQAcy-:-N481KGK1aKaKV455p4C:byelywf) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/multinode_constraint.py#L35)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Don't forget to black the code
</blockquote></details>

won't forget
___
*[`bioptim/limits/multinode_constraint.py` line 48 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42u8zPBI-BseJmgMCC:-N4827YP5idr-OzDjcXo:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/multinode_constraint.py#L48)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should remain multinode_constraint for the constraints (later it gets:  `multinode_penalty=multinode_constraint`
</blockquote></details>

Done.
___
*[`bioptim/limits/objective_functions.py` line 278 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42uooH2ej4-D8Kf7DE:-N47t8YV0r04RM3ey87Z:byvs7bx) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/limits/objective_functions.py#L278)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Does this make sense as an objective? It is already an enforced Constraint (which is stronger than an objective)
</blockquote></details>

It is the whole reason behind this PR.

The goal is to have a continuity set as effectively a "soft constraint" to be able to generate a partial solution that is then fed back as an initial guess to the same problem but with continuity set as a "hard constraint" to find the optimal solution.

The hope behind all this is to speed up the convergence by reducing the number of constraint in the first pass and having an initial guess good enough so that converging will won't be long in the second pass.
___
*[`bioptim/limits/objective_functions.py` line 295 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42v2855dTPtQfTQ5kj:-N47v8KN1WUD8IupGsGS:b-gr89q4) ([raw f [...]

2022-06-13 18:18 UTC, Ipuch reviewed
> Reviewed 4 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480)* status: 17 of 18 files reviewed, 20 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/optimization/optimal_control_program.py` line 157 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42wNlD8_MzEnpJPZ-T:-N4TH1m_EP1cpGozCUSf:b4v02qn) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/optimization/optimal_control_program.py#L157)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

For now I just wanted to communicate my intent, so yeah sure.
</blockquote></details>

I agree :)


<!-- Sent from Reviewable.io -->

2022-06-13 19:05 UTC, Sciancisco reviewed
Last commit might be a little big and all over the place.

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480#-:-N4TNt2A-OJe0OSqG3xB:b5gemkf)* status: 11 of 19 files reviewed, 22 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/limits/multinode_constraint.py` line 73 at r3](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4TOaOW2Apz5opBaHqW:-N4TOaOX6TUONF1gytkx:b-vg2lyi) ([raw file](https://github.com/pyomeca/bioptim/blob/484aaf3395729395870c0d507d8a189312a6dc34/bioptim/limits/multinode_constraint.py#L73)):*
> ```Python
>             min_bound=min_bound,
>             max_bound=max_bound,
>             **params,
> ```

Removed the weight from MultinodeConstraint
___
*[`bioptim/limits/multinode_constraint.py` line 87 at r3](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4TOjdL7uyXZyDw-TjY:-N4TOjdL7uyXZyDw-TjZ:buz0lft) ([raw file](https://github.com/pyomeca/bioptim/blob/484aaf3395729395870c0d507d8a189312a6dc34/bioptim/limits/multinode_constraint.py#L87)):*
> ```Python
>             max_bound=max_bound,
>             **params,
>         )
> ```

Calling `__init__` with `super` wouldn't work.


<!-- Sent from Reviewable.io -->

2022-06-13 20:53 UTC, Sciancisco reviewed
I propose some changes:

Make the declaration of custom function more general:
`WhateverList.add(whatever=WhateverFcn.CUSTOM, custom_function=a_custom_function, ...)`
instead of
`WhateverList.add(whatever=a_custom_function, ...)`.
It is already a available and valid way for the user of of specifying a custom function and it would simplify many `__init__` and solve one of my problems elegantly. Otherwise during the initialization of `Multinode(Constraint|Objective)` I get TypeError because of multiple values for `custom_function` keyword.

Remove the wierd behaviour of `weight == 0 -> Constraint` and `weight != 0 -> Objective`. I am sure that one day a user will want to set an objective to 0 expecting make it's effect null and won't realize that he effectively made it even more stringent then before. If this behaviour is to stay, I would at least make it so `weight == float('inf') -> Constraint`.

Also, I am now having problems with `PhaseTransition`. Should I also split it in `PhaseTransitionConstraint` and `PhaseTransitionObjective`?

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480#-:-N4TlDEnC5LtmrP4s5oQ:b-xf7c8)* status: 8 of 19 files reviewed, 22 unresolved discussions (waiting on @Ipuch and @pariterre)



<!-- Sent from Reviewable.io -->

2022-06-16 19:50 UTC, pariterre requested changes
> Reviewed 3 of 4 files at r4, 13 of 13 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480)* status: all files reviewed, 17 unresolved discussions (waiting on @Ipuch, @pariterre, and @Sciancisco)

___
*[`bioptim/dynamics/configure_problem.py` line 148 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42scFB5vhqUNYrRXbS:-N4hgmBn9WOC9Ks9xPmW:boh25sv) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L148)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

I changed them from ConstraintType to PenaltyType because it was called directly in what would become MultinodePenalty which would break the abstraction.

Furthermore, as a general comment, I would argue that if the problem is formulated with Continuity as an Objective, an implicit constraint becomes an implicit objective.
</blockquote></details>

I still think it is an actual constraint



_Code quote:_
```Python
.implicit_constraints
```
___
*[`bioptim/dynamics/configure_problem.py` line 174 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42skZpANDCEO99rWfz:-N4hgtip50PipUXm2e7s:bn4zliv) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L174)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

see reply to line 148
</blockquote></details>

see reply of reply to line 148
___
*[`bioptim/dynamics/configure_problem.py` line 222 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42slWjAKDu9S0oDYEN:-N4hgxTp8mrwKtWhCLB5:bn4zliv) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L222)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

see reply to line 148
</blockquote></details>

see reply of reply to line 148
___
*[`bioptim/dynamics/configure_problem.py` line 247 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42sm1TEXZIgcCqArJH:-N4hgxvp1-sMP1BNf8hx:bn4zliv) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/dynamics/configure_problem.py#L247)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

see reply to line 148
</blockquote></details>

see reply of reply to line 148
___
*[`bioptim/examples/getting_started/example_multinode_constraints.py` line 9 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4hh93W7oa-H1mp3Eez:-N4hh93W7oa-H1mp3Ef-:b-okewhz) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/examples/getting_started/example_multinode_constraints.py#L9)):*
> ```Python
> 
> from casadi import MX
> import biorbd_casadi as biorbd
> ```

change the name of the file



_Code quote:_
```Python
import biorbd_casadi as biorbd
from bioptim import (
```
___
*[`bioptim/examples/getting_started/example_multinode_objectives.py` line 2 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4hhUOAAo0Xc_95Y2w3:-N4hhUOAAo0Xc_95Y2w4:b-2xs0jq) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/examples/getting_started/example_multinode_objectives.py#L2)):*
> ```Python
> """
> This example is a trivial box that must superimpose one of its corner to a marker at the beginning of the movement and
> ```

Make sure this description fits what you are doing and that it explains what we learn from it
Also make sure the name is coherent 



_Code quote:_
```Python
"""
This example is a trivial box that must superimpose one of its corner to a marker at the beginning of the movement and
a the at different marker at the end of each phase. Moreover a constraint on the rotation is imposed on the cube.
Extra constraints are defined between specific nodes of phases.
It is designed to show how one can define a multinode constraints and objectives in a multiphase optimal control program
"""
```
___
*[`bioptim/limits/constraints.py` line 56 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4hjwzp7J3kK4Ew8jnA:-N4hjwzp7J3kK4Ew8jnB:brh2db9) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/limits/constraints.py#L56)):*
> ```Python
>         # if not isinstance(constraint, (ConstraintFcn, ImplicitConstraintFcn, MultinodePenaltyFcn)):
>         #     custom_function = constraint
>         #     constraint = ConstraintFcn.CUSTOM
> ```

To be tried :

```
def _manage_custom_function():
    custom_function = None
    if not isinstance(constraint, (ConstraintFcn, ImplicitConstraintFcn, MultinodePenaltyFcn)):
        custom_function = constraint
        constraint = ConstraintFcn.CUSTOM
```

puis dans MultinodePenalty
```
def _manage_custom_function():
    pass
```



_Code quote:_
```Python
        # custom_function = None
        # if not isinstance(constraint, (ConstraintFcn, ImplicitConstraintFcn, MultinodePenaltyFcn)):
        #     custom_function = constraint
        #     constraint = ConstraintFcn.CUSTOM
```
___
*[`bioptim/limits/multinode_constraint.py` line 68 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4hlQqX0j0_WY-qJI3h:-N4hlQqX0j0_WY-qJI3i:b-y3gvem) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/limits/multinode_constraint.py#L68)):*
> ```Python
>             min_bound=min_bound,
>             max_bound=max_bound,
>             quadratic=True,  # how it was in MultinodeConstraint before
> ```

Quadratic does not make sense for Constraints
___
*[`bioptim/limits/multinode_constraint.py` line 133 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4i1IoiEAho2mUGxdLR:-N4i1IoiEAho2mUGxdLS:btz5xqi) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/limits/multinode_constraint.py#L133)):*
> ```Python
>         # if not isinstance(multinode_constraint, MultinodeConstraintFcn):  # if we change interface to only accept CUSTOM with custom_function this can be removed
>         #     extra_arguments["custom_function"] = multinode_constraint     # it is already valid and would simplify the "add" methods
>         #     multinode_constraint = MultinodeConstraintFcn.CUSTOM
> ```

Try what was discussed before. If it works, I'd prefer keeping the old behavior



_Code quote:_
```Python
        # if not isinstance(multinode_constraint, MultinodeConstraintFcn):  # if we change interface to only accept CUSTOM with custom_function this can be removed
        #     extra_arguments["custom_function"] = multinode_constraint     # it is already valid and would simplify the "add" methods
        #     multinode_constraint = MultinodeConstraintFcn.CUSTOM
        super(MultinodeConstraintList, self)._add(
            option_type=MultinodeConstraint, multinode_constraint=multinode_constraint, phase=-1, **extra_arguments
```
___
*[`bioptim/limits/multinode_objective.py` line 100 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4i1Rj2CqguM098hKPd:-N4i1Rj2CqguM098hKPe:brohwnt) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/limits/multinode_objective.py#L100)):*
> ```Python
>         """
> 
>         # if not isinstance(multinode_objective, MultinodePenaltyFcn):  # could be removed
> ```

Same thing



_Code quote:_
```Python
        # if not isinstance(multinode_objective, MultinodePenaltyFcn):  # could be removed
        #     extra_arguments["custom_function"] = multinode_objective
        #     multinode_objective = MultinodePenaltyFcn.CUSTOM
```
___
*[`bioptim/limits/multinode_penalty.py` line 75 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4i1_UO0DHSD9nm9usL:-N4i1_UO0DHSD9nm9usM:b-89bl1o) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/limits/mult [...]

2022-07-08 16:29 UTC, Sciancisco commented
*[`bioptim/limits/objective_functions.py` line 5 at r8](https://reviewable.io/reviews/pyomeca/bioptim/480#-N6Td-mTAs4UGupTTDaP:-N6Td-mTAs4UGupTTDaQ:b-89a46v) ([raw file](https://github.com/pyomeca/bioptim/blob/d3a62c9933af86819aa442a2dba8b3425342b13c/bioptim/limits/objective_functions.py#L5)):*
> ```Python
> 
> from .penalty import PenaltyFunctionAbstract, PenaltyOption
> from .multinode_penalty import MultinodePenaltyFcn  # this causes a circular import. maybe fixable by other means but it is getting messy
> ```

If we want to keep the current behavior for custom_function, objective_functions.py must import MultinodePenaltyFcn to handle a special case but this creates a circular import. Maybe fixable by other means but it is getting messy.


<!-- Sent from Reviewable.io -->

2022-07-26 15:26 UTC, Sciancisco reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480)* status: 6 of 29 files reviewed, 18 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/examples/getting_started/example_multinode_constraints.py` line 9 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4hh93W7oa-H1mp3Eez:-N7v3oEuBy_f_78iy1Tm:b-4kydyo) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/examples/getting_started/example_multinode_constraints.py#L9)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

change the name of the file
</blockquote></details>

This example now shows how to use multinode constraints and objectives. File name changed to reflect new purpose.
___
*[`bioptim/examples/getting_started/example_multinode_objectives.py` line 2 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4hhUOAAo0Xc_95Y2w3:-N7v4FkN48QqjwWF42BL:bss4a2b) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/examples/getting_started/example_multinode_objectives.py#L2)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Make sure this description fits what you are doing and that it explains what we learn from it
Also make sure the name is coherent 
</blockquote></details>

Removed.
___
*[`bioptim/limits/multinode_penalty.py` line 113 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4i1pyd2jROqIWAuupl:-N7v4K_w-3dwoTdQeerU:b-rww6ey) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/limits/multinode_penalty.py#L113)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

They can comment out the objective. But I agree that "None" should be the default value (and not 0), even though a weight=0 for an objective does not make any sense
</blockquote></details>

This comment is now way out of date. Many changes happened since then.
___
*[`bioptim/limits/phase_transition.py` line 60 at r5](https://reviewable.io/reviews/pyomeca/bioptim/480#-N4i2SnD1CT8vuhIcuiu:-N7v4k9R83XYNJeeOmm1:bd75yi9) ([raw file](https://github.com/pyomeca/bioptim/blob/4bdddc90530bfb8595690994214937d71602fb01/bioptim/limits/phase_transition.py#L60)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I am opening this comment just to keep track of this TODO
</blockquote></details>

TODO has now disappeared.
___
*[`bioptim/optimization/optimal_control_program.py` line 157 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42wNlD8_MzEnpJPZ-T:-N7v50F5CV9KuEpZskz9:b-med69k) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/optimization/optimal_control_program.py#L157)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I agree :)
</blockquote></details>

Will need new feedback.


<!-- Sent from Reviewable.io -->

2022-07-28 19:14 UTC, pariterre requested changes
> Reviewed 1 of 7 files at r7, 26 of 26 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480)* status: all files reviewed, 45 unresolved discussions (waiting on @Ipuch, @pariterre, and @Sciancisco)

___
*[`bioptim/__init__.py` line 114 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85Dgxs4eTT4dmzEetr:-N85Dgxs4eTT4dmzEets:b-3curtu) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/__init__.py#L114)):*
> ```Python
>     Selection of valid phase transition functions
> ```

Why this space?
___
*[`bioptim/dynamics/configure_problem.py` line 1093 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N84xumU1igmgyLKaIe2:-N84xumU1igmgyLKaIe3:byp18fd) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/dynamics/configure_problem.py#L1093)):*
> ```Python
> 
>         # if dynamic_function and dynamics_type != DynamicsFcn.CUSTOM:
>         #     raise RuntimeError("custom dynamic function detected but no custom configure was provided")
> ```

Remove



_Code quote:_
```Python
        # if dynamic_function and dynamics_type != DynamicsFcn.CUSTOM:
        #     raise RuntimeError("custom dynamic function detected but no custom configure was provided")
```
___
*[`bioptim/examples/getting_started/example_cyclic_movement.py` line 98 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N84yQBjAjw6fC9xnSA_:-N84yQBjAjw6fC9xnSAa:b-6p0idc) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/examples/getting_started/example_cyclic_movement.py#L98)):*
> ```Python
>         phase_transitions.add(PhaseTransitionFcn.CYCLIC)
>     else:
>         phase_transitions.add(PhaseTransitionFcn.CYCLIC, relaxed=True, weight=10000)
> ```

relaxed is useless
___
*[`bioptim/interfaces/ipopt_interface.py` line 335 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N84yqgL8IMgk_M_d6vz:-N84yqgL8IMgk_M_d6w-:b-bmzcs4) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/interfaces/ipopt_interface.py#L335)):*
> ```Python
>                         target = format_target(penalty.target[0])
> 
>                     if np.isnan(np.sum(target)):  # why??? could be removed
> ```

To continue the loop
___
*[`bioptim/interfaces/ipopt_interface.py` line 344 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N84zaFN5PT4laRGYqV0:-N84zaFN5PT4laRGYqV1:b2cvywa) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/interfaces/ipopt_interface.py#L344)):*
> ```Python
>                         x, u = get_x_and_u_at_idx(penalty, idx)
> 
>                     # NOTE: here is why phase transition as a constraint must have weight = 0
> ```

Please write PhaseTransition
And remove "NOTE"?



_Code quote:_
```Python
phase transition
```
___
*[`bioptim/limits/constraints.py` line 59 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85-wm62oy61pRTYT2I:-N85-wm62oy61pRTYT2J:b7hwkx6) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/constraints.py#L59)):*
> ```Python
>                 raise RuntimeError(f"constraint of type '{type(constraint)}' not allowed")
>         else:
>             custom_function = constraint
> ```

Why not testing if it is a callable too?
___
*[`bioptim/limits/multinode_constraint.py` line 11 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N852Yv_B-Umumz9sWIo:-N852Yv_B-Umumz9sWIp:b-fmk1cq) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_constraint.py#L11)):*
> ```Python
> 
> 
> class MultinodeConstraint(Constraint, MultinodePenalty):
> ```

Still not convinced by this multiple inheritance. 
___
*[`bioptim/limits/multinode_constraint.py` line 72 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N850lsH4PkE63JBPQSF:-N850lsH4PkE63JBPQSG:b-f1syyy) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_constraint.py#L72)):*
> ```Python
>                 raise RuntimeError(f"multinode_constraint of type '{type(multinode_constraint)}' not allowed")
>         else:
>             custom_function = multinode_constraint
> ```

Why not testing for callable?
___
*[`bioptim/limits/multinode_constraint.py` line 100 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N852Vlq9H753eiGBVPa:-N852VlrEF8P36FrWbU6:b-m5vy9o) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_constraint.py#L100)):*
> ```Python
> 
>     def clear_penalty(self, ocp, nlp):
>         pool_to_add_to = nlp.g_internal if nlp else ocp.g_internal
> ```

g was clearer for me...
___
*[`bioptim/limits/multinode_constraint.py` line 116 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N852yKZDv73OcSXwtll:-N852yKZDv73OcSXwtlm:btssy8o) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_constraint.py#L116)):*
> ```Python
> 
> 
> class MultinodeConstraintList(UniquePerPhaseOptionList):
> ```

Why only one per phase?
___
*[`bioptim/limits/multinode_objective.py` line 43 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N853cF-2hJOztR7Ee2M:-N853cF-2hJOztR7Ee2N:b-49zs3e) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_objective.py#L43)):*
> ```Python
>                 raise RuntimeError(f"multinode_objective of type '{type(multinode_objective)}' not allowed")
>         else:
>             custom_function = multinode_objective
> ```

Why not check if callable?
___
*[`bioptim/limits/multinode_objective.py` line 72 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N853kEi9EcfSdrZEwdJ:-N853kEi9EcfSdrZEwdK:b-2gueng) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_objective.py#L72)):*
> ```Python
> 
>     def clear_penalty(self, ocp, nlp):
>         pool_to_add_to = nlp.J_internal if nlp else ocp.J_internal
> ```

`J` seems more appropriate
___
*[`bioptim/limits/multinode_objective.py` line 88 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N853nIHC7pP6Cc8eFfl:-N853nIHC7pP6Cc8eFfm:btssy8o) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_objective.py#L88)):*
> ```Python
> 
> 
> class MultinodeObjectiveList(UniquePerPhaseOptionList):
> ```

Why only one per phase?
___
*[`bioptim/limits/multinode_penalty.py` line 76 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N854OKP9iG3Tg5RYFNZ:-N854OKP9iG3Tg5RYFN_:b-8cwr7g) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_penalty.py#L76)):*
> ```Python
>             )
> 
>         # TODO: yet another reason to have user pass CUSTOM and custom_function himself, was broken when inheritence
> ```

To remove



_Code quote:_
```Python
# TODO: yet another reason to have user pass CUSTOM and custom_function himself, was broken when inheritence
```
___
*[`bioptim/limits/multinode_penalty.py` line 87 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N854i5y6qw_Nl5-RXqh:-N854i5y6qw_Nl5-RXqi:b-g0b1pz) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_penalty.py#L87)):*
> ```Python
>         self.node = self.first_node, self.second_node
>         self.node_idx = [0]
>         self.penalty_type = penalty_type  # TODO: fix with proper multiple inheritence
> ```

mmmm...



_Code quote:_
```Python
 fix with proper multiple inheritence
```
___
*[`bioptim/limits/multinode_penalty.py` line 89 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N854s5c7gNQkxSQMJDd:-N854s5c7gNQ [...]

2022-07-28 20:40 UTC, Sciancisco reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480)* status: all files reviewed, 45 unresolved discussions (waiting on @AbstractMethod, @Ipuch, @pariterre, and @Sciancisco)

___
*[`bioptim/__init__.py` line 114 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85Dgxs4eTT4dmzEetr:-N85GJ4A0IIQdSi3q1E5:b89gpwi) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/__init__.py#L114)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why this space?
</blockquote></details>

Looked around in code and turns out that double newline is the norm.
___
*[`bioptim/dynamics/configure_problem.py` line 1093 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N84xumU1igmgyLKaIe2:-N85H75XEHx9vJIzCrIa:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/dynamics/configure_problem.py#L1093)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.
___
*[`bioptim/interfaces/ipopt_interface.py` line 335 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N84yqgL8IMgk_M_d6vz:-N85JoCM01l1eVVpYLGv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/interfaces/ipopt_interface.py#L335)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To continue the loop
</blockquote></details>

Done.
___
*[`bioptim/interfaces/ipopt_interface.py` line 344 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N84zaFN5PT4laRGYqV0:-N85JojB0yCli5uHCh1n:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/interfaces/ipopt_interface.py#L344)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please write PhaseTransition
And remove "NOTE"?
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 59 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85-wm62oy61pRTYT2I:-N85K4DB9Me7gUa2-5M3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/constraints.py#L59)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why not testing if it is a callable too?
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_constraint.py` line 72 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N850lsH4PkE63JBPQSF:-N85L6r6DfOPcWUV_O9p:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_constraint.py#L72)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why not testing for callable?
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_constraint.py` line 100 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N852Vlq9H753eiGBVPa:-N85P39Z4W_wSeY8-hNl:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_constraint.py#L100)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

g was clearer for me...
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_constraint.py` line 116 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N852yKZDv73OcSXwtll:-N85M2rf2j2JVwJI6vex:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_constraint.py#L116)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why only one per phase?
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_objective.py` line 43 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N853cF-2hJOztR7Ee2M:-N85MpwmC_1wfYazNrN5:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_objective.py#L43)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why not check if callable?
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_objective.py` line 72 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N853kEi9EcfSdrZEwdJ:-N85Mrwq7uWUOvkvlAQQ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_objective.py#L72)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`J` seems more appropriate
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_objective.py` line 88 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N853nIHC7pP6Cc8eFfl:-N85NUPI5Zx64FuxP0-W:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_objective.py#L88)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why only one per phase?
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_penalty.py` line 76 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N854OKP9iG3Tg5RYFNZ:-N85NgCHAUNNbfrfr634:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_penalty.py#L76)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To remove
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_penalty.py` line 89 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N854s5c7gNQkxSQMJDd:-N85Nsog5tUE6uCMzuZK:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/multinode_penalty.py#L89)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Don't forget to remove this
</blockquote></details>

Done.
___
*[`bioptim/limits/objective_functions.py` line 15 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N855H5u07p5LVCS_OGZ:-N85O99Y6od5GCbv7ouN:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/objective_functions.py#L15)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

no need for this comment
</blockquote></details>

Done.
___
*[`bioptim/limits/objective_functions.py` line 40 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N855MpT0z_w7I2XJalU:-N85OLVDDpf2yippv94V:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/objective_functions.py#L40)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why not testing if callable?
</blockquote></details>

Done.
___
*[`bioptim/limits/objective_functions.py` line 316 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N856-To3eXSQtN-U_xj:-N85OSc-3bGGfnpOdZDQ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/objective_functions.py#L316)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

todo can be removed
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty_option.py` line 159 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N856ih-2wbbRahWsQ7y:-N85Qbe2CML0X__TCA8H:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/penalty_option.py#L159)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should be removed and put placed before `target = np.array(target)`
</blockquote></details>

Done.
___
*[`bioptim/limits/phase_transition.py` line 69 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N857EOd9mkdV-htKItt:-N85SkOE37yR8jWSXH [...]

2022-07-29 17:09 UTC, Sciancisco reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/480)* status: 15 of 30 files reviewed, 45 unresolved discussions (waiting on @AbstractMethod, @Ipuch, @pariterre, and @Sciancisco)

___
*[`bioptim/examples/getting_started/example_cyclic_movement.py` line 98 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N84yQBjAjw6fC9xnSA_:-N89hl8d0PGNjwfRcFkw:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/examples/getting_started/example_cyclic_movement.py#L98)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

relaxed is useless
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty_option.py` line 159 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N856ih-2wbbRahWsQ7y:-N89TXbj9u2kX1r9XbB5:bwircpz) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/penalty_option.py#L159)):*
<details><summary><i>Previously, Sciancisco wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Might have implemented badly, but broke things so I reverted.
___
*[`bioptim/limits/phase_transition.py` line 58 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N857AI75oiJEKc4Y5Xx:-N89akPLAar3AdRgZn9w:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/phase_transition.py#L58)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be removed
</blockquote></details>

Done.
___
*[`bioptim/limits/phase_transition.py` line 75 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N857WEC905xPXn32waB:-N89amlvC_SXdUs1AqzP:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/phase_transition.py#L75)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is useless as if weight = 0 we know for sure that relaxed = False
</blockquote></details>

Done.
___
*[`bioptim/limits/phase_transition.py` line 97 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N8598En1NWdRQcOoYYx:-N89bLUN-SEL3_oJNblW:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/phase_transition.py#L97)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be removed
</blockquote></details>

Done.
___
*[`bioptim/limits/phase_transition.py` line 125 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N859Ksa9oS3KEbK8_iZ:-N89bRSX61CJ28uoNNvy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/phase_transition.py#L125)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be replaced by self.weight = 0
</blockquote></details>

Done.
___
*[`bioptim/limits/phase_transition.py` line 210 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85AAU495jDB_H0f46r:-N89bSpMCFvJ2uj_P1Mz:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/phase_transition.py#L210)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

to be removed
</blockquote></details>

Done.
___
*[`bioptim/limits/phase_transition.py` line 227 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85A9R83VtBsVV-QH3E:-N89bWhX78N6uBa6S521:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/limits/phase_transition.py#L227)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be replaced
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 157 at r1](https://reviewable.io/reviews/pyomeca/bioptim/480#-N42wNlD8_MzEnpJPZ-T:-N89e6Go8zxH6kMUOys_:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fff74737faa49a26db7953726dbf26969cb8b11a/bioptim/optimization/optimal_control_program.py#L157)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please only keep `state_continuity_weight` 
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 256 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85C2r8CRF-4DIaw5KM:-N89f6nX9Ivz9reaijCH:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/optimization/optimal_control_program.py#L256)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Adapt here
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 366 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85C6AWEiiUZGNY1wtB:-N89f8DT91YWM-e4yRMc:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/optimization/optimal_control_program.py#L366)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Adapt here
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 463 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85CCSt6C4N1obNj6oq:-N89f99a-pRauBkmkcqm:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/optimization/optimal_control_program.py#L463)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

To be adapted
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 463 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85CF1w354to3TPOwuO:-N89fFLpBopOsDokv2RT:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/optimization/optimal_control_program.py#L463)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

state_continuity_weight
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 468 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85Ct4SCjSz9Fjyeeiz:-N89hhf03KX4bPbYqb37:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/optimization/optimal_control_program.py#L468)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please make sure that interphase continuity are skipped too if needed (if possible)
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 471 at r9](https://reviewable.io/reviews/pyomeca/bioptim/480#-N85ChWK4gGucUyF0-uZ:-N89hgJE63LwIADwcRT7:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/0e288847c985921efe6d0f0810be1b8110257ef9/bioptim/optimization/optimal_control_program.py#L471)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should be inside of the `if not skip_continuity:` and the `if continuity_as_objective` should be inside too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-26 13:31 UTC, Sciancisco commented
This PR was getting to big and was split in PR #512 and #516. It is no longer relevant.

2022-08-26 13:31 UTC, closed without merging