animated tracked markers
pyomeca/bioptim pull request #500
Opened 2022-07-20 14:41 UTC by thasaarah

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2022-07-21 13:49 UTC, pariterre requested changes
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/500)* status: all files reviewed, 1 unresolved discussion (waiting on @thasaarah)

___
*[`bioptim/optimization/solution.py` line 1048 at r1](https://reviewable.io/reviews/pyomeca/bioptim/500#-N7W03YK0P9nSHAfPQRY:-N7W03YK0P9nSHAfPQRZ:b-dngog1) ([raw file](https://github.com/pyomeca/bioptim/blob/1cc3c2477d261f4306d6f22b67b511108928ff6d/bioptim/optimization/solution.py#L1048)):*
> ```Python
>                 if objective.type in (ObjectiveFcn.Mayer.TRACK_MARKERS, ObjectiveFcn.Lagrange.TRACK_MARKERS):
>                     if objective.node[0] in (Node.ALL, Node.ALL_SHOOTING):
>                         if objective.target is not None:
> ```

This looks like it is additive conditions (if .. AND ... AND...) 
If so, please make it explicit in a single if instead of nesting if

I think it also make sense to test (objective.target) first 



_Code quote:_
```Python
                if objective.type in (ObjectiveFcn.Mayer.TRACK_MARKERS, ObjectiveFcn.Lagrange.TRACK_MARKERS):
                    if objective.node[0] in (Node.ALL, Node.ALL_SHOOTING):
                        if objective.target is not None:
```


<!-- Sent from Reviewable.io -->

2022-07-21 19:22 UTC, thasaarah reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/500)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/optimization/solution.py` line 1048 at r1](https://reviewable.io/reviews/pyomeca/bioptim/500#-N7W03YK0P9nSHAfPQRY:-N7XBjei3tJgvPG9Mv6j:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/1cc3c2477d261f4306d6f22b67b511108928ff6d/bioptim/optimization/solution.py#L1048)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This looks like it is additive conditions (if .. AND ... AND...) 
If so, please make it explicit in a single if instead of nesting if

I think it also make sense to test (objective.target) first 
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-07-28 14:44 UTC, thasaarah commented on bioptim/optimization/solution.py
> +                    if objective.type in cond and objective.node[0] in cond:
Done

2022-07-28 14:56 UTC, Ipuch commented on bioptim/limits/constraints.py
> -    TRACK_QDDOT = (PenaltyFunctionAbstract.Functions.minimize_qddot,)
Can you restore this enum?

2022-07-28 17:31 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/500#-:-N84rGJZ6MZs4kLlouNM:bnfp4nl)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @Ipuch and @pariterre)



<!-- Sent from Reviewable.io -->

2022-08-01 14:57 UTC, merged