collocation initial guess
pyomeca/bioptim pull request #504
Opened 2022-07-25 13:59 UTC by thasaarah

2022-07-28 17:51 UTC, pariterre requested changes
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: all files reviewed, 7 unresolved discussions (waiting on @thasaarah)

___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 139 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84t7zHCNF-Yy9iYrDR:-N84t7zHCNF-Yy9iYrDS:b-ap07q) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/examples/getting_started/custom_initial_guess.py#L139)):*
> ```Python
>         if ode_solver.is_direct_collocation:
>             x = np.random.random((nq + nqdot, n_shooting * (ode_solver.polynomial_degree + 1) + 1))
>             u = np.random.random((ntau, n_shooting))
> ```

Please remove the if check here. We want to let the capability to the example to fail if one wants to try this ALL_POINTS thing



_Code quote:_
```Python
        if ode_solver.is_direct_collocation:
            x = np.random.random((nq + nqdot, n_shooting * (ode_solver.polynomial_degree + 1) + 1))
            u = np.random.random((ntau, n_shooting))
        else:
            raise ValueError("InterpolationType.ALL_POINTS must only be used in direct collocation")
```
___
*[`bioptim/limits/path_conditions.py` line 248 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84tVCg499oK0zgozt1:-N84tVCg499oK0zgozt2:b-j1g996) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/limits/path_conditions.py#L248)):*
> ```Python
>             if self.shape[1] != self.n_shooting:
>                 raise RuntimeError(
>                     f"Invalid number of column for InterpolationType.EACH_FRAME (ncols = {self.shape[1]}), "
> ```

ALL_POINTS
___
*[`bioptim/misc/enums.py` line 50 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84te1i8ROsVNUMueJN:-N84te1i8ROsVNUMueJO:b-57a6yu) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/misc/enums.py#L50)):*
> ```Python
>     LINEAR = 2  # Linear interpolation between first and last
>     EACH_FRAME = 3  # Each values are provided by the user
>     ALL_POINTS = 4
> ```

Please add a relevent description (and in the ReadMe too)
___
*[`bioptim/optimization/optimization_vector.py` line 142 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84uGgk4DOrFyE0rB5u:-N84uGgk4DOrFyE0rB5v:b-9bcuvu) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L142)):*
> ```Python
>             if type(self.ocp.original_values["x_init"]) == InitialGuess:
>                 interpolation_type = nlp.x_init.type
>             elif type(self.ocp.original_values["x_init"]) == InitialGuessList:
> ```

What is the expected value of interpolation_type if both if fails?



_Code quote:_
```Python
            if type(self.ocp.original_values["x_init"]) == InitialGuess:
                interpolation_type = nlp.x_init.type
            elif type(self.ocp.original_values["x_init"]) == InitialGuessList:
                interpolation_type = self.ocp.original_values["x_init"][phase].type
```
___
*[`bioptim/optimization/optimization_vector.py` line 360 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84uYOE9vI3rEmpVBUL:-N84uYOE9vI3rEmpVBUM:bdc4czj) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L360)):*
> ```Python
>             if ocp.nlp[i].x_init.type == InterpolationType.ALL_POINTS:
>                 if not ocp.nlp[i].ode_solver.is_direct_collocation:
>                     raise ValueError("InterpolationType.ALL_POINTS must only be used in direct collocation")
> ```

"with" direct collocation
___
*[`bioptim/optimization/optimization_vector.py` line 361 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84ucI84vsBtgG36Zv-:-N84ucI84vsBtgG36Zv0:bvbw3pc) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L361)):*
> ```Python
>                 if not ocp.nlp[i].ode_solver.is_direct_collocation:
>                     raise ValueError("InterpolationType.ALL_POINTS must only be used in direct collocation")
>             if hasattr(ocp.original_values["x_init"], "type"):
> ```

`hasattr` is usually a design flaw. Please create the define the value no matter what with a default to None.

That said, it seems that you are testing for something else indirectly. Do not do that. Test directly and explicitely what you need



_Code quote:_
```Python
            if hasattr(ocp.original_values["x_init"], "type"):
                interpolation_type = ocp.original_values["x_init"].type
            elif hasattr(ocp.original_values["x_init"], "options"):
                interpolation_type = ocp.original_values["x_init"].options[i][0].type
            else:
                interpolation_type = None
```
___
*[`bioptim/optimization/optimization_vector.py` line 387 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84vaQX8Xr0svWzxGWh:-N84vaQX8Xr0svWzxGWi:b-ms0f9k) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L387)):*
> ```Python
>             if (
>                 nlp.ode_solver.is_direct_collocation
>                 and interpolation_type != InterpolationType.EACH_FRAME
> ```

Do you mean `== InterpolationType.ALL_POINTS`? If so, please be explicit 


<!-- Sent from Reviewable.io -->

2022-08-03 21:41 UTC, thasaarah reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: 0 of 6 files reviewed, 7 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 139 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84t7zHCNF-Yy9iYrDR:-N8Ph7C0BAjgFSrIKnK-:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/examples/getting_started/custom_initial_guess.py#L139)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please remove the if check here. We want to let the capability to the example to fail if one wants to try this ALL_POINTS thing
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 248 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84tVCg499oK0zgozt1:-N85VLtU0Ov320D_RTen:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/limits/path_conditions.py#L248)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

ALL_POINTS
</blockquote></details>

Done.
___
*[`bioptim/misc/enums.py` line 50 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84te1i8ROsVNUMueJN:-N8ZEIZRE1EVirANLQ07:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/misc/enums.py#L50)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please add a relevent description (and in the ReadMe too)
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 142 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84uGgk4DOrFyE0rB5u:-N8ZK_muBH9cLe4wTvUu:bb710wt) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L142)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

What is the expected value of interpolation_type if both if fails?
</blockquote></details>

None
___
*[`bioptim/optimization/optimization_vector.py` line 360 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84uYOE9vI3rEmpVBUL:-N85VOr599SEJspOAirT:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L360)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

"with" direct collocation
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 361 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84ucI84vsBtgG36Zv-:-N8PhOxm0cL1N2HPGDoT:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L361)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`hasattr` is usually a design flaw. Please create the define the value no matter what with a default to None.

That said, it seems that you are testing for something else indirectly. Do not do that. Test directly and explicitely what you need
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 387 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84vaQX8Xr0svWzxGWh:-N8Zrf2EClK_5Ybvq9bT:byf0pbe) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L387)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do you mean `== InterpolationType.ALL_POINTS`? If so, please be explicit 
</blockquote></details>

No, any interpolation type but EACH_FRAME


<!-- Sent from Reviewable.io -->

2022-08-04 18:35 UTC, pariterre requested changes
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: all files reviewed, 6 unresolved discussions (waiting on @thasaarah)

___
*[`bioptim/limits/path_conditions.py` line 898 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e5O6HEhR6SVJ1tn39:-N8e5O6HEhR6SVJ1tn3A:bvzz1s5) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/limits/path_conditions.py#L898)):*
> ```Python
>             initial_guess=self.noised_initial_guess,
>             interpolation=interpolation
>             if interpolation == InterpolationType.ALL_POINTS
> ```

Please add a comment that says that this interpolation should always be done at each data point



_Code quote:_
```Python
            interpolation=interpolation
            if interpolation == InterpolationType.ALL_POINTS
            else InterpolationType.EACH_FRAME,
```
___
*[`bioptim/optimization/optimization_vector.py` line 361 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84ucI84vsBtgG36Zv-:-N8e7OSY31gs5e2ZS6c_:b-fmpwu0) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L361)):*
<details><summary><i>Previously, thasaarah wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`type(...) == SomeClass` should be `isinstance(..., SomeClass)`
___
*[`bioptim/optimization/optimization_vector.py` line 145 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e6Bvc7ITvJJivo_F0:-N8e6Bvc7ITvJJivo_F1:b-1gk56r) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/optimization/optimization_vector.py#L145)):*
> ```Python
>                 interpolation_type = self.ocp.original_values["x_init"][phase].type
>             else:
>                 interpolation_type = None
> ```

Please make sure this line is tested, if not, check if it is sane (do we allow "x_init" to not be either). If it runs smoothly then change `interpolation_type = None` for `pass`, if it fails, raise an error.

Also add a line return after this if block



_Code quote:_
```Python
 interpolation_type = None
```
___
*[`bioptim/optimization/optimization_vector.py` line 366 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e7bpw8fkMr5UVlxuV:-N8e7bpw8fkMr5UVlxuW:b2gq2yo) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/optimization/optimization_vector.py#L366)):*
> ```Python
>                 interpolation_type = ocp.original_values["x_init"][i].type
>             else:
>                 interpolation_type = None
> ```

Same thing as before

Add a line return after this if block
___
*[`bioptim/optimization/optimization_vector.py` line 371 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e7hr44KHQBPTxDKvQ:-N8e7hr44KHQBPTxDKvR:b-lewuyv) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/optimization/optimization_vector.py#L371)):*
> ```Python
>                 if ocp.nlp[i].ode_solver.is_direct_collocation
>                 and interpolation_type != InterpolationType.EACH_FRAME
>                 and type(ocp.nlp[i].x_init) != NoisedInitialGuess
> ```

isinstance instead of type (if it makes sense)



_Code quote:_
```Python
type(ocp.nlp[i].x_init) != NoisedInitialGuess
```
___
*[`bioptim/optimization/optimization_vector.py` line 399 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e7u8w6K2Hht8NJHSt:-N8e7u8w6K2Hht8NJHSu:b-sk0g3g) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/optimization/optimization_vector.py#L399)):*
> ```Python
>                 for p in range(repeat if k != nlp.ns else 1):
>                     span = slice(k * outer_offset + p * nx, k * outer_offset + (p + 1) * nx)
>                     if nlp.x_init.type == InterpolationType.EACH_FRAME and type(nlp.x_init) != NoisedInitialGuess:
> ```

isinstance



_Code quote:_
```Python
ype(nlp.x_init) != NoisedInitialGuess:
```


<!-- Sent from Reviewable.io -->

2022-08-11 16:07 UTC, thasaarah reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: 4 of 11 files reviewed, 6 unresolved discussions (waiting on @pariterre and @thasaarah)

___
*[`bioptim/limits/path_conditions.py` line 898 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e5O6HEhR6SVJ1tn39:-N97FOac7kaKlRTA0aO5:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/limits/path_conditions.py#L898)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please add a comment that says that this interpolation should always be done at each data point
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 361 at r1](https://reviewable.io/reviews/pyomeca/bioptim/504#-N84ucI84vsBtgG36Zv-:-N8jqLDC43QPOENYqiJQ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/f6a357afae1f5b5b53b9c062f3bc8ceb843d0a84/bioptim/optimization/optimization_vector.py#L361)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`type(...) == SomeClass` should be `isinstance(..., SomeClass)`
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 366 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e7bpw8fkMr5UVlxuV:-N98SKvP6_sBaSCeOPk-:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/optimization/optimization_vector.py#L366)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same thing as before

Add a line return after this if block
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 371 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e7hr44KHQBPTxDKvQ:-N98SnSj9zOq8g-Xhq9R:b-32f85e) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/optimization/optimization_vector.py#L371)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

isinstance instead of type (if it makes sense)
</blockquote></details>

used type(ocp.nlp[i].x_init) is InitialGuess here to make the condition more evident by avoiding negation
___
*[`bioptim/optimization/optimization_vector.py` line 399 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e7u8w6K2Hht8NJHSt:-N8jqbi5B_X87OtMOl1h:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/optimization/optimization_vector.py#L399)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

isinstance
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-08-11 17:46 UTC, thasaarah reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: 4 of 11 files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/optimization/optimization_vector.py` line 145 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e6Bvc7ITvJJivo_F0:-N9CeSei69HN9INlJ4IO:b-87i3tj) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/optimization/optimization_vector.py#L145)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please make sure this line is tested, if not, check if it is sane (do we allow "x_init" to not be either). If it runs smoothly then change `interpolation_type = None` for `pass`, if it fails, raise an error.

Also add a line return after this if block
</blockquote></details>

interpolation_type needs to defined before a value can be assigned to ns


<!-- Sent from Reviewable.io -->

2022-08-11 18:43 UTC, pariterre requested changes
> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: all files reviewed, 7 unresolved discussions (waiting on @pariterre and @thasaarah)

___
*[`bioptim/limits/path_conditions.py` line 898 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e5O6HEhR6SVJ1tn39:-N9D77xk5lpDDT9Qy482:b-sb8qod) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/limits/path_conditions.py#L898)):*
<details><summary><i>Previously, thasaarah wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It was added but at the wrong place, it should be with the if
___
*[`bioptim/limits/path_conditions.py` line 894 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9D65LE9DSH9XaFAsZZ:-N9D65LE9DSH9XaFAsZ_:b-i11ker) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/bioptim/limits/path_conditions.py#L894)):*
> ```Python
> 
>         if bounds is None:
>             raise RuntimeError("bounds must be specified to generate noised initial guess")
> ```

Add single quotations around 'bounds' to emphasize it is a parameter



_Code quote:_
```Python
bounds
```
___
*[`bioptim/limits/path_conditions.py` line 900 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9D6C2iEE_h0R4zheH1:-N9D6C2iEE_h0R4zheH2:b-afy7br) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/bioptim/limits/path_conditions.py#L900)):*
> ```Python
>             bounds.n_shooting = initial_guess.shape[1]
>             bounds.min.n_shooting = initial_guess.shape[1]
>             bounds.max.n_shooting = initial_guess.shape[1]
> ```

The `min` and `max` update should be automatically done in Bounds if n_shooting is modify. So : 
```
bounds.n_shooting = value 
```
should be enough



_Code quote:_
```Python
            bounds.n_shooting = initial_guess.shape[1]
            bounds.min.n_shooting = initial_guess.shape[1]
            bounds.max.n_shooting = initial_guess.shape[1]
```
___
*[`bioptim/optimization/optimization_vector.py` line 416 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9D8n7b0axW9LOhSU1j:-N9D8n7b0axW9LOhSU1k:b-z7wgll) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/bioptim/optimization/optimization_vector.py#L416)):*
> ```Python
>         if ocp.nlp[phase].ode_solver.is_direct_collocation:
>             if (
>                 isinstance(ocp.nlp[phase].x_init, NoisedInitialGuess)
> ```

Is suggestion good?



_Suggestion:_
```Python
        ns = ocp.nlp[phase].ns
        if ocp.nlp[phase].ode_solver.is_direct_collocation:
            if isinstance(ocp.nlp[phase].x_init, NoisedInitialGuess):
                if interpolation_type == InterpolationType.ALL_POINTS:
                    ns *= (ocp.nlp[phase].ode_solver.steps + 1)
            elif isinstance(ocp.nlp[phase].x_init, InitialGuess):
                if interpolation_type != InterpolationType.EACH_FRAME:
                    ns *= (ocp.nlp[phase].ode_solver.steps + 1)
        return ns
```
___
*[`bioptim/optimization/optimization_vector.py` line 469 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9DBE0O9GojwGmS2_6V:-N9DBE0O9GojwGmS2_6W:b-qotz4n) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/bioptim/optimization/optimization_vector.py#L469)):*
> ```Python
>                     if type(nlp.x_init) is InitialGuess and nlp.x_init.type == InterpolationType.EACH_FRAME:
>                         point = k * repeat + p
>                     elif isinstance(nlp.x_init, NoisedInitialGuess) and nlp.x_init.type == InterpolationType.ALL_POINTS:
> ```

Same as before, put `isinstance(..., Noised...) before the `instance(..., InitialGuess) so it catches it before it can be catch be InitialGuess. Therefore no need for type == ...



_Code quote:_
```Python
isinstance(nlp.x_init, NoisedInitialGuess)
```
___
*[`external/acados` line 0 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9DCqacEG3LC8s8UHVo:-N9DCqacEG3LC8s8UHVp:b-cmh62d) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/external/acados#L0)):*
This is not acceptable, please force push to reinstate


<!-- Sent from Reviewable.io -->

2022-08-18 17:59 UTC, pariterre requested changes
> Reviewed 8 of 41 files at r8, 35 of 35 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: all files reviewed, 4 unresolved discussions (waiting on @pariterre and @thasaarah)

___
*[`bioptim/limits/path_conditions.py` line 518 at r9](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9m2G3kDwva4PLoOBf_:-N9m2G3kDwva4PLoOBfa:b-aobe6q) ([raw file](https://github.com/pyomeca/bioptim/blob/d6983f4b1654992048623e59c7a82dd158ad8c92/bioptim/limits/path_conditions.py#L518)):*
> ```Python
>         return self.min.shape
> 
>     # todo: to be removed?
> ```

nope, `n_shooting` should be changed to `_n_shooting` with a `property` that returns `_n_shooting` and a setter. This would look like this: 
```
def __init__(self):
    self._n_shooting = ns
```

```
    @property
    def n_shooting(self):
        return self._n_shooting

    @n_shooting.setter
    def n_shooting(self, ns):
        self._n_shooting = ns
        self.min.n_shooting = ns
        self.max.n_shooting = ns
```


<!-- Sent from Reviewable.io -->

2022-08-18 18:59 UTC, pariterre requested changes
> Reviewed 4 of 4 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: all files reviewed, 6 unresolved discussions (waiting on @pariterre and @thasaarah)

___
*[`bioptim/limits/path_conditions.py` line 908 at r10](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9mJWZDBDXezrUXMLyC:-N9mJWZDBDXezrUXMLyD:b-8gpxqy) ([raw file](https://github.com/pyomeca/bioptim/blob/3c7dc7e90bc3e0b19e8471503e1a6cd6b7ebe5db/bioptim/limits/path_conditions.py#L908)):*
> ```Python
>             interpolation = initial_guess.type
>         if interpolation == InterpolationType.ALL_POINTS:
>             bounds._n_shooting = initial_guess.shape[1]
> ```

this should be `bounds.n_shooting`
___
*[`tests/test_update_bounds_and_init.py` line 1444 at r10](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9mJn9bAE87_EQdWiAg:-N9mJn9bAE87_EQdWiAh:b-eosb8h) ([raw file](https://github.com/pyomeca/bioptim/blob/3c7dc7e90bc3e0b19e8471503e1a6cd6b7ebe5db/tests/test_update_bounds_and_init.py#L1444)):*
> ```Python
>             ]
>         )
>     elif interpolation == InterpolationType.CONSTANT_WITH_FIRST_AND_LAST_DIFFERENT:
> ```

These two tests should be there


<!-- Sent from Reviewable.io -->

2022-08-18 20:11 UTC, thasaarah reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: 44 of 45 files reviewed, 6 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/limits/path_conditions.py` line 898 at r2](https://reviewable.io/reviews/pyomeca/bioptim/504#-N8e5O6HEhR6SVJ1tn39:-N9DgG234gQRPMKE4gBw:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c0eafbc705a523249126592e373509918f9bbc8d/bioptim/limits/path_conditions.py#L898)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

It was added but at the wrong place, it should be with the if
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 894 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9D65LE9DSH9XaFAsZZ:-N9IJRCR6dYkK-FmiqCP:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/bioptim/limits/path_conditions.py#L894)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Add single quotations around 'bounds' to emphasize it is a parameter
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 900 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9D6C2iEE_h0R4zheH1:-N9lfv97AlGDigorNYyu:b-3wam6n) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/bioptim/limits/path_conditions.py#L900)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

The `min` and `max` update should be automatically done in Bounds if n_shooting is modify. So : 
```
bounds.n_shooting = value 
```
should be enough
</blockquote></details>

added a function to set n_shooting but it might not be necessary
___
*[`bioptim/limits/path_conditions.py` line 518 at r9](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9m2G3kDwva4PLoOBf_:-N9mZ9FZCiVrxs43tP00:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/d6983f4b1654992048623e59c7a82dd158ad8c92/bioptim/limits/path_conditions.py#L518)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

nope, `n_shooting` should be changed to `_n_shooting` with a `property` that returns `_n_shooting` and a setter. This would look like this: 
```
def __init__(self):
    self._n_shooting = ns
```

```
    @property
    def n_shooting(self):
        return self._n_shooting

    @n_shooting.setter
    def n_shooting(self, ns):
        self._n_shooting = ns
        self.min.n_shooting = ns
        self.max.n_shooting = ns
```
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 908 at r10](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9mJWZDBDXezrUXMLyC:-N9mZ6nYAWHhLxk39yAj:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/3c7dc7e90bc3e0b19e8471503e1a6cd6b7ebe5db/bioptim/limits/path_conditions.py#L908)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

this should be `bounds.n_shooting`
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 416 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9D8n7b0axW9LOhSU1j:-N9DjXXl3zQIAbYDG5S9:b2nign6) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/bioptim/optimization/optimization_vector.py#L416)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Is suggestion good?
</blockquote></details>

yes
___
*[`bioptim/optimization/optimization_vector.py` line 469 at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9DBE0O9GojwGmS2_6V:-N9DjZtYEfRGInEFml1S:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/bioptim/optimization/optimization_vector.py#L469)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same as before, put `isinstance(..., Noised...) before the `instance(..., InitialGuess) so it catches it before it can be catch be InitialGuess. Therefore no need for type == ...
</blockquote></details>

Done.
___
*[`external/acados` line  at r4](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9DCqacEG3LC8s8UHVo:-N9g9pJUBz4mSbVgWGN9:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/5ac7b10295a556f1d152df4f4eb736cc717bd0b8/external/acados#L)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is not acceptable, please force push to reinstate
</blockquote></details>

Done.
___
*[`tests/test_update_bounds_and_init.py` line 1444 at r10](https://reviewable.io/reviews/pyomeca/bioptim/504#-N9mJn9bAE87_EQdWiAg:-N9mZ_8q3300IUBRb4FD:b-ynjcvq) ([raw file](https://github.com/pyomeca/bioptim/blob/3c7dc7e90bc3e0b19e8471503e1a6cd6b7ebe5db/tests/test_update_bounds_and_init.py#L1444)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

These two tests should be there
</blockquote></details>

i think it was already fixed


<!-- Sent from Reviewable.io -->

2022-08-18 21:26 UTC, pariterre reviewed
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: all files reviewed, 3 unresolved discussions (waiting on @pariterre)



<!-- Sent from Reviewable.io -->

2022-08-25 13:11 UTC, pariterre reviewed
> Reviewed 3 of 3 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504)* status: all files reviewed, 1 unresolved discussion (waiting on @pariterre)



<!-- Sent from Reviewable.io -->

2022-08-25 13:12 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/504#-:-NAK7QwV6hNaBPC2W9lP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @pariterre)



<!-- Sent from Reviewable.io -->

2022-08-25 13:12 UTC, merged