[RTR] Multi-model (phase mapping)
pyomeca/bioptim pull request #548
Opened 2022-10-06 16:18 UTC by EveCharbie

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [NA] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [x] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

2022-10-06 19:07 UTC, pariterre requested changes
GG so far!

> Reviewed 1 of 8 files at r2, 29 of 29 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548#-:-NDigSiaEwgitGStistS:b2m0f5f)* status: all files reviewed, 29 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/configure_problem.py` line 850 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiOC_c5i2wjnbZH7xA:-NDiOC_c5i2wjnbZH7xB:b-fc4y8r) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/dynamics/configure_problem.py#L850)):*
> ```Python
>         copy_states = False
>         if nlp.use_states_from_phase_idx is not None:
>             if nlp.use_states_from_phase_idx < nlp.phase_idx:
> ```

Raise if not true



_Suggestion:_
```Python
if nlp.use_states_from_phase_idx > nlp.phase_idx:
    raise...
```
___
*[`bioptim/dynamics/configure_problem.py` line 856 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiOgKt3IXSSq_Sinpr:-NDiOgKt3IXSSq_Sinps:b-5vpmun) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/dynamics/configure_problem.py#L856)):*
> ```Python
>         copy_controls = False
>         if nlp.use_controls_from_phase_idx is not None:
>             if nlp.use_controls_from_phase_idx < nlp.phase_idx:
> ```

Raise if untrue



_Code quote:_
```Python
if nlp.use_controls_from_phase_idx < nlp.phase_idx:
```
___
*[`bioptim/dynamics/configure_problem.py` line 862 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiOiyI4IaHHqoGc1xQ:-NDiOiyI4IaHHqoGc1xR:balvwvl) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/dynamics/configure_problem.py#L862)):*
> ```Python
>         copy_states_dot = False
>         if nlp.use_states_dot_from_phase_idx is not None:
>             if nlp.use_states_dot_from_phase_idx < nlp.phase_idx:
> ```

raise if untrue



_Code quote:_
```Python
if nlp.use_states_dot_from_phase_idx < nlp.phase_idx:
```
___
*[`bioptim/dynamics/configure_problem.py` line 870 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiOr8pEuUny5qXbjuO:-NDiOr8pEuUny5qXbjuP:b2ec4z9) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/dynamics/configure_problem.py#L870)):*
> ```Python
>         mx_states_dot = [] if not copy_states_dot else [ocp.nlp[nlp.use_states_dot_from_phase_idx].states_dot[name].mx]
> 
>         # if mapping on variables, what do we do with mapping on the nodes ?
> ```

Mapping must be the same between phases. A check is probably required to make sure



_Code quote:_
```Python
# if mapping on variables, what do we do with mapping on the nodes 
```
___
*[`bioptim/examples/torque_driven_ocp/multi_model_by_constraint.py` line 137 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiQY95Ae7IXbVmNXyS:-NDiQY960IWNF_pTdwfm:b-lbbqus) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/examples/torque_driven_ocp/multi_model_by_constraint.py#L137)):*
> ```Python
>     # --- Show results --- #
>     show_solution_animation = True
>     if show_solution_animation:
> ```

Put `False` as default



_Suggestion:_
```Python
    show_solution_animation = False
    if show_solution_animation:
```
___
*[`bioptim/examples/torque_driven_ocp/multi_model_by_mapping.py` line 124 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiQhjF88fFSQkB7p-1:-NDiQhjF88fFSQkB7p-2:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/examples/torque_driven_ocp/multi_model_by_mapping.py#L124)):*
> ```Python
> 
>     # --- Show results --- #
>     show_solution_animation = True
> ```





_Suggestion:_
```Python
show_solution_animation = False
```
___
*[`bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_bounds.py` line 30 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiQwGo6jfGc7hkk64T:-NDiQwGo6jfGc7hkk64U:bz0lice) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_bounds.py#L30)):*
> ```Python
> 
>     # Problem parameters
>     n_shooting = (5, 5)
> ```

Put this as a parameter with previous 40, 40 (but you can change it for the tests)



_Code quote:_
```Python
5, 5
```
___
*[`bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_mapping.py` line 30 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiR4Ic9qZ5sf-dcbGR:-NDiR4Ic9qZ5sf-dcbGS:bz0lice) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_mapping.py#L30)):*
> ```Python
> 
>     # Problem parameters
>     n_shooting = (5, 5)
> ```

Put this as a parameter with previous 40, 40 (but you can change it for the tests)



_Code quote:_
```Python
(5, 5
```
___
*[`bioptim/gui/plot.py` line 647 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiRriLC2IsZD2gyV21:-NDiRriLC2IsZD2gyV22:b-av7z20) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/gui/plot.py#L647)):*
> ```Python
>             state = np.ndarray((0, n_elements))
>             for s in nlp.states:
>                 if nlp.use_states_from_phase_idx == nlp.phase_idx:
> ```

If it is easy to do: 
Add the number of the mapped phase to the title of the previous phase (in `configure_new_variable`)



_Code quote:_
```Python
if nlp.use_states_from_phase_idx == nlp.phase_idx:
```
___
*[`bioptim/interfaces/ipopt_interface.py` line 262 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiSo2U2amk5rp79eqB:-NDiSo2U2amk5rp79eqC:b-qeajdo) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/interfaces/ipopt_interface.py#L262)):*
> ```Python
>             if _penalty.transition:
>                 if _penalty.type == PhaseTransitionFcn.DISCONTINUOUS:
>                     _x = vertcat(ocp.nlp[0].X[-1], ocp.nlp[0].X[0][:, 0])
> ```

_x = MX(0, 2)  # There is no constraint (? to test)
OR
break if DISCONTINUOUS as no cost function is associated
(probably remove (see below))



_Code quote:_
```Python
_x = vertcat(ocp.nlp[0].X[-1], ocp.nlp[0].X[0][:, 0])
```
___
*[`bioptim/interfaces/ipopt_interface.py` line 284 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiUHnH6yBpiHiBt-2l:-NDiUHnH6yBpiHiBt-2m:bjf0oue) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/interfaces/ipopt_interface.py#L284)):*
> ```Python
>                 )
>             elif _penalty.integrate:
>                 _x = ocp.nlp[states_idx].X[_idx]
> ```

This is already taken care by `configure_new_variable`. I think you can leave `nlp.X`
This is true for all next `ocp.nlp[...]`



_Code quote:_
```Python
ocp.nlp[states_idx]
```
___
*[`bioptim/interfaces/ipopt_interface.py` line 313 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiYERS65ItyEb3QESv:-NDiYERS65ItyEb3QESw:b9w3lqo) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/interfaces/ipopt_interface.py#L313)):*
> ```Python
>         out = self.ocp.cx()
>         for penalty in penalties:
>             if not penalty:
> ```

or penalty.type == DISCONTINUOUS
(This will take care of previous problem)



_Code quote:_
```Python
            if not penalty:
                continue
```
___
*[`bioptim/limits/constraints.py` line 14 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiVhLX76CLfStyntya:-NDiVhLX76CLfStyntyb:br4d547) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/limits/constraints.py#L14)):*
> ```Python
> from ..misc.fcn_enum import FcnEnum
> from ..misc.options import OptionList
> ```

Move this into `def inner_phase_ [...]

2022-10-07 20:50 UTC, EveCharbie reviewed
@pariterre when you have time, you can look at it :)     

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548#-:-NDoCaAc7eGozvTd_rji:bjocray)* status: all files reviewed, 29 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 850 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiOC_c5i2wjnbZH7xA:-NDmauhY063vAgf6ZERL:b-o6gkh1) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/dynamics/configure_problem.py#L850)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Raise if not true
</blockquote></details>

Done in NodeMappingList.add
___
*[`bioptim/dynamics/configure_problem.py` line 856 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiOgKt3IXSSq_Sinpr:-NDmbD-x57wdFs7AYVbj:bvryz2n) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/dynamics/configure_problem.py#L856)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Raise if untrue
</blockquote></details>

Done in NodeMappingList.add
___
*[`bioptim/dynamics/configure_problem.py` line 862 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiOiyI4IaHHqoGc1xQ:-NDmbGJ88hvD-AByWLzZ:bvryz2n) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/dynamics/configure_problem.py#L862)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

raise if untrue
</blockquote></details>

Done in NodeMappingList.add
___
*[`bioptim/dynamics/configure_problem.py` line 870 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiOr8pEuUny5qXbjuO:-NDoC6lv3tI7y4UmKYf1:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/dynamics/configure_problem.py#L870)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Mapping must be the same between phases. A check is probably required to make sure
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/multi_model_by_constraint.py` line 137 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiQY95Ae7IXbVmNXyS:-NDn4HRG-zkOQp5QVu_f:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/examples/torque_driven_ocp/multi_model_by_constraint.py#L137)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put `False` as default
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/multi_model_by_mapping.py` line 124 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiQhjF88fFSQkB7p-1:-NDn4Isk-46d8lIHbS3j:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/examples/torque_driven_ocp/multi_model_by_mapping.py#L124)):*
> ```Python
> 
>     # --- Show results --- #
>     show_solution_animation = True
> ```

Done.
___
*[`bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_bounds.py` line 30 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiQwGo6jfGc7hkk64T:-NDn4Qzs8QlnUTAF-6-W:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_bounds.py#L30)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put this as a parameter with previous 40, 40 (but you can change it for the tests)
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_mapping.py` line 30 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiR4Ic9qZ5sf-dcbGR:-NDn4SMP3O1G2HHMZHQy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/examples/torque_driven_ocp/phase_transition_uneven_variable_number_by_mapping.py#L30)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put this as a parameter with previous 40, 40 (but you can change it for the tests)
</blockquote></details>

Done.
___
*[`bioptim/gui/plot.py` line 647 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiRriLC2IsZD2gyV21:-NDo0z2EDu_xDjE47hCL:b-k2dctp) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/gui/plot.py#L647)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

If it is easy to do: 
Add the number of the mapped phase to the title of the previous phase (in `configure_new_variable`)
</blockquote></details>

Badly did, I think.
___
*[`bioptim/interfaces/ipopt_interface.py` line 262 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiSo2U2amk5rp79eqB:-NDnfBm_1Tc3lnHrs2gs:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/interfaces/ipopt_interface.py#L262)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

_x = MX(0, 2)  # There is no constraint (? to test)
OR
break if DISCONTINUOUS as no cost function is associated
(probably remove (see below))
</blockquote></details>

Done.
___
*[`bioptim/interfaces/ipopt_interface.py` line 284 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiUHnH6yBpiHiBt-2l:-NDntelc0xf9LMQJeex6:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/interfaces/ipopt_interface.py#L284)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is already taken care by `configure_new_variable`. I think you can leave `nlp.X`
This is true for all next `ocp.nlp[...]`
</blockquote></details>

Done.
___
*[`bioptim/interfaces/ipopt_interface.py` line 313 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiYERS65ItyEb3QESv:-NDnfxeyA3Y7oPvBy7Od:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/interfaces/ipopt_interface.py#L313)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

or penalty.type == DISCONTINUOUS
(This will take care of previous problem)
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 14 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiVhLX76CLfStyntya:-NDn6_hrDKoItG3CKa5c:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/limits/constraints.py#L14)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Move this into `def inner_phase_continuity` and `def inter_phase_continuity`
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 537 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiWKWu48WoekU1gi7G:-NDn707M4FkM5297vpFU:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/limits/constraints.py#L537)):*
> ```Python
>         # Dynamics must be sound within phases
>         for nlp in ocp.nlp:
>             # if nlp.use_states_from_phase_idx == nlp.phase_idx:  # PhaseTransitionFcn.DISCONTINUOUS -> relative import
> ```

Done.
___
*[`bioptim/limits/multinode_constraint.py` line 236 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiXR-J8L6xe0T13UGq:-NDoCE_V71ooQNysqr2X:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/limits/multinode_constraint.py#L236)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

make a simpler function to get the `nlp_pre.states.cx_end` with `"all"` so we can use it with minimize_states
</blockquote></details>

Done.
___
*[`bioptim/limits/multinode_constrai [...]

2022-10-13 17:39 UTC, pariterre requested changes
> Reviewed 20 of 20 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548)* status: all files reviewed, 8 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/limits/constraints.py` line 15 at r4](https://reviewable.io/reviews/pyomeca/bioptim/548#-NEHMiQQ8GpfvoR-mOFk:-NEHMiQQ8GpfvoR-mOFl:b-vfv9pl) ([raw file](https://github.com/pyomeca/bioptim/blob/ba54303daaba2e1729428ed9b2c3afb0301acaa6/bioptim/limits/constraints.py#L15)):*
> ```Python
> from ..misc.options import OptionList
> 
> # from ..limits.phase_transition import PhaseTransitionFcn
> ```

Remove comment?



_Code quote:_
```Python
# from ..limits.phase_transition import PhaseTransitionFcn
```
___
*[`bioptim/limits/phase_transition.py` line 147 at r4](https://reviewable.io/reviews/pyomeca/bioptim/548#-NEHNMUqC61cpxjHe5D-:-NEHNMUr9tgj_6TjSn0s:b1ysuxa) ([raw file](https://github.com/pyomeca/bioptim/blob/ba54303daaba2e1729428ed9b2c3afb0301acaa6/bioptim/limits/phase_transition.py#L147)):*
> ```Python
>                     pt.phase_pre_idx = ocp.n_phases - 1
>                 elif pt.type == PhaseTransitionFcn.DISCONTINUOUS:
>                     pt.phase_pre_idx = 10000  # Ask Pariterre what to do
> ```

Is the 10000 still necessary? `None`?



_Code quote:_
```Python
# Ask Pariterre what to do
```
___
*[`bioptim/limits/phase_transition.py` line 149 at r4](https://reviewable.io/reviews/pyomeca/bioptim/548#-NEHNT8p74MLKOVDWfjG:-NEHNT8p74MLKOVDWfjH:b95tsf) ([raw file](https://github.com/pyomeca/bioptim/blob/ba54303daaba2e1729428ed9b2c3afb0301acaa6/bioptim/limits/phase_transition.py#L149)):*
> ```Python
>                     pt.phase_pre_idx = 10000  # Ask Pariterre what to do
>             if pt.type == PhaseTransitionFcn.DISCONTINUOUS:
>                 pt.phase_post_idx = 1000
> ```

Is 1000 still necessary? `None`?



_Code quote:_
```Python
pt.phase_post_idx = 1000
```
___
*[`bioptim/misc/enums.py` line 171 at r4](https://reviewable.io/reviews/pyomeca/bioptim/548#-NEHNdvQ9ETSDfSmQON5:-NEHNdvQ9ETSDfSmQON6:bhunss8) ([raw file](https://github.com/pyomeca/bioptim/blob/ba54303daaba2e1729428ed9b2c3afb0301acaa6/bioptim/misc/enums.py#L171)):*
> ```Python
> class CxType(Enum):
>     CX = "CX"
>     CX_END = "cx_end"
> ```

Maybe uniformize the labels (all caps or all non-caps)
class 
```
class CXStep(Enum):
    CX_START = "cx_start"
    CX_END = "cx_end"
```



_Code quote:_
```Python
    CX = "CX"
    CX_END = "cx_end"
```
___
*[`bioptim/misc/mapping.py` line 256 at r3](https://reviewable.io/reviews/pyomeca/bioptim/548#-NDiZjiC01h_vPAvK-fy:-NEHOcr0DYZ5Awe8M567:bdruj5t) ([raw file](https://github.com/pyomeca/bioptim/blob/c9d3696d1d05e4024d0f96c0f0cb0179ea0f06bd/bioptim/misc/mapping.py#L256)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

After reflexion, it makes no sens, removed it.
</blockquote></details>

They are still there ;)
___
*[`bioptim/optimization/optimization_variable.py` line 182 at r4](https://reviewable.io/reviews/pyomeca/bioptim/548#-NEHPcPe-VZsj_uzMHzr:-NEHPcPe-VZsj_uzMHzs:b-elmzx) ([raw file](https://github.com/pyomeca/bioptim/blob/ba54303daaba2e1729428ed9b2c3afb0301acaa6/bioptim/optimization/optimization_variable.py#L182)):*
> ```Python
>         self.elements.append(value)
> 
>     def _choose_cx_from_key(self, key, cx_type):
> ```

This is to be called from outside, so it should not be a protected method (no "_" before the name) 
change it to `get_cx`



_Code quote:_
```Python
 _choose_cx_from_key
```


<!-- Sent from Reviewable.io -->

2022-10-14 20:19 UTC, EveCharbie commented
All tests pass on aceglia's computer :)

2022-10-27 18:13 UTC, pariterre reviewed
> Reviewed 1 of 36 files at r5, 35 of 35 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548)* status: 57 of 58 files reviewed, 2 unresolved discussions (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-10-28 00:02 UTC, pariterre commented
@EveCharbie  I rebased this PR to integrate the new tests. Please use reset --hard (don't merge) to move to that PR if you need to push something later. Call me if needed

2022-10-28 18:59 UTC, pariterre commented
@EveCharbie 
Tests fails so renaming to normal name!

2022-11-02 18:43 UTC, pariterre submitted a review, later dismissed
> Reviewed 1 of 1 files at r8, 1 of 4 files at r10, 25 of 30 files at r11, 2 of 2 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-11-03 19:09 UTC, pariterre requested changes
> Reviewed 1 of 2 files at r15, 30 of 30 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548)* status: all files reviewed, 3 unresolved discussions (waiting on @EveCharbie)

___
*[`tests/test_global_torque_driven_ocp.py` line 503 at r16](https://reviewable.io/reviews/pyomeca/bioptim/548#-NFysxg6CHYvV6irrxnI:-NFysxg6CHYvV6irrxnJ:bdcryt9) ([raw file](https://github.com/pyomeca/bioptim/blob/9ea8dbbb7e557a1e4db803a06f3a9ec952b822b3/tests/test_global_torque_driven_ocp.py#L503)):*
> ```Python
>     g = np.array(sol.constraints)
>     np.testing.assert_equal(g.shape, (170, 1))
>     np.testing.assert_equal(sol.status, 1)  # Did not converge, therefore the constraints won't be zero
> ```

Why it did not converge? It was converging before
___
*[`tests/test_global_torque_driven_ocp.py` line 509 at r16](https://reviewable.io/reviews/pyomeca/bioptim/548#-NFyt3OO3oCgmK90X3zt:-NFyt3OO3oCgmK90X3zu:b-2hnv74) ([raw file](https://github.com/pyomeca/bioptim/blob/9ea8dbbb7e557a1e4db803a06f3a9ec952b822b3/tests/test_global_torque_driven_ocp.py#L509)):*
> ```Python
> 
>     # initial and final position
>     np.testing.assert_almost_equal(states[0]["q"][:, 0], np.array([0.0, 0.0, 3.14, -1.57067321]))
> ```

If it does not converge (and it is intended) please remove all these check as they will be different for each platform / architechture and os
___
*[`tests/test_global_torque_driven_ocp.py` line 552 at r16](https://reviewable.io/reviews/pyomeca/bioptim/548#-NFytGf-D8nR3maqpHqD:-NFytGf-D8nR3maqpHqE:b-a1ejst) ([raw file](https://github.com/pyomeca/bioptim/blob/9ea8dbbb7e557a1e4db803a06f3a9ec952b822b3/tests/test_global_torque_driven_ocp.py#L552)):*
> ```Python
>     g = np.array(sol.constraints)
>     np.testing.assert_equal(g.shape, (126, 1))
>     np.testing.assert_almost_equal(g[:44], np.zeros((44, 1)), decimal=6)
> ```

This should converge as well...


<!-- Sent from Reviewable.io -->

2022-11-10 14:28 UTC, pariterre submitted a review, later dismissed
> Reviewed 1 of 1 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-11-10 14:30 UTC, pariterre submitted a review, later dismissed
> Reviewed 3 of 3 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-11-10 14:30 UTC, pariterre commented
@EveCharbie  RTM?

2022-11-21 15:21 UTC, EveCharbie commented
@pariterre we are finally good to merge :)

2022-11-21 15:40 UTC, pariterre requested changes
> Reviewed 1 of 3 files at r19, 4 of 4 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

___
*[`tests/test_global_torque_driven_ocp.py` line 563 at r20](https://reviewable.io/reviews/pyomeca/bioptim/548#-NHPq8KR2SV1mADb8duj:-NHPq8KR2SV1mADb8duk:b1yglke) ([raw file](https://github.com/pyomeca/bioptim/blob/b9ba9ece9fde1ae68b7e5bd5ee2bb2628d406b51/tests/test_global_torque_driven_ocp.py#L563)):*
> ```Python
> def test_multi_model_by_mapping():
>     """
>     This test is highly sensible, do not change anything please.
> ```

sensitive?



_Code quote:_
```Python
sensible
```


<!-- Sent from Reviewable.io -->

2022-11-21 15:46 UTC, EveCharbie reviewed
Done

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548#-:-NHPrYoQ1DHyg9ebyv0W:bb6un1j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-11-21 15:51 UTC, pariterre approved these changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-11-21 16:43 UTC, merged