[RTR] noise magnitude controled for each decision variable
pyomeca/bioptim pull request #553
Opened 2022-10-14 21:41 UTC by Ipuch

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2022-10-20 20:12 UTC, pariterre requested changes
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/553)* status: all files reviewed, 2 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/limits/path_conditions.py` line 920 at r1](https://reviewable.io/reviews/pyomeca/bioptim/553#-NEr072x468aV88R0lwU:-NEr072x468aV88R0lwV:b-dwdmx4) ([raw file](https://github.com/pyomeca/bioptim/blob/6deb593a56df4064eeb6b999379cb29576632344/bioptim/limits/path_conditions.py#L920)):*
> ```Python
> 
>         self.seed = seed
>         if not isinstance(noise_magnitude, (int, float)):
> ```

Then deintend the rest



_Suggestion:_
```Python
if isinstance(noise_magnitude, (int, float)):
    noise_magnitude = (noise_magnitude,)
```
___
*[`bioptim/limits/path_conditions.py` line 930 at r1](https://reviewable.io/reviews/pyomeca/bioptim/553#-NEr-kuQ84GW83g3bim3:-NEr-kuQ84GW83g3bim4:b-g7ggvn) ([raw file](https://github.com/pyomeca/bioptim/blob/6deb593a56df4064eeb6b999379cb29576632344/bioptim/limits/path_conditions.py#L930)):*
> ```Python
>                 raise ValueError("noise_magnitude must be a float or list of float of the size of states or controls")
> 
>         self.noise_magnitude = noise_magnitude
> ```

This should not possible to be of two different types. If int or float cast it to np.array (see previous)



_Code quote:_
```Python
self.noise_magnitude = noise_magnitude
```


<!-- Sent from Reviewable.io -->

2022-10-20 20:21 UTC, pariterre approved these changes
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)



<!-- Sent from Reviewable.io -->

2022-10-25 18:16 UTC, pariterre requested changes
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/553)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/limits/path_conditions.py` line 928 at r3](https://reviewable.io/reviews/pyomeca/bioptim/553#-NFFLiqt0KSlvIpNdZFl:-NFFLiqt0KSlvIpNdZFm:bdfgjpz) ([raw file](https://github.com/pyomeca/bioptim/blob/507b437655f900f390efeb7bdc63d351514db743/bioptim/limits/path_conditions.py#L928)):*
> ```Python
>             noise_magnitude = np.array(noise_magnitude)
> 
>         if noise_magnitude.shape.__len__() == 1:
> ```

Do not use `.__len__()` but call the len(xxx) function instead

Since all these `if` deal with noise_magnitude_validation, can you remove the spacing between them (or create a validate_noise_magnitude method)



_Code quote:_
```Python
 noise_magnitude.shape.__len__() 
```


<!-- Sent from Reviewable.io -->

2022-10-25 18:28 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/553#-:-NFFOoZ6DuZKHnmBBZS2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)



<!-- Sent from Reviewable.io -->

2022-10-25 18:29 UTC, merged

2022-10-25 18:29 UTC, Ipuch commented
@rapidnico your PR will follow #560