Creation of to_noised_initial_guess function
pyomeca/bioptim pull request #560
Opened 2022-10-24 20:35 UTC by rapidnico

creation of to_noised_initial_guess. Allows to create easily a noise on the different initial guess of a multiphase ocp. it does the transition between x_init or u_init and the NoisedInitialGuess class.
the user has to put in argument : nounds, noise_magnitude, n_shooting, bound_push and seed (optional). if several phases but 1 value only, applies th value to all phases.

2022-10-25 18:31 UTC, Ipuch commented
@rapidnico  update and push ;)

2022-10-27 18:14 UTC, Ipuch requested changes
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: 1 of 2 files reviewed, 14 unresolved discussions (waiting on @rapidnico)

___
*[`.gitignore` line 114 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPWNxo0eB_FcaS7AMX:-NFPWNxo0eB_FcaS7AMY:b-ovesjx) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/.gitignore#L114)):*
> ```ignore
> *.gv.pdf
> 
> bioptim/sandbox/
> ```

remove the line, just open this in pycharm and remove the line.
___
*[`bioptim/limits/path_conditions.py` line 874 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPWkWB9akxOWYupl3-:-NFPWkWB9akxOWYupl30:b-hn8upq) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L874)):*
> ```Python
>             seed: int = None,
>             absolute_noise: Union[list, int, float, np.ndarray] = None,
>             relative_noise: Union[list, int, float, np.ndarray] = None,
> ```

You modified the default behavior of the code, please restore it, `relative_noise=1`
___
*[`bioptim/limits/path_conditions.py` line 888 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPWdma1X4XwcvCjXCZ:-NFPWdma1X4XwcvCjXC_:b-b1bz6g) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L888)):*
> ```Python
>         noise_magnitude: Union[list, int, float]
>             The magnitude of the noised that must be applied between 0 and 1 (0 = no noise, 1 = continuous noise with a
>             range defined between the bounds
> ```

The docstring is not up to date.



_Code quote:_
```Python
        noise_magnitude: Union[list, int, float]
            The magnitude of the noised that must be applied between 0 and 1 (0 = no noise, 1 = continuous noise with a
            range defined between the bounds
```
___
*[`bioptim/limits/path_conditions.py` line 924 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPX8lc-37-RULTBn6k:-NFPX8lc-37-RULTBn6l:bq59kyo) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L924)):*
> ```Python
> 
>         if absolute_noise is not None and relative_noise is not None:
>             raise RuntimeError("absolute_noise and relative_noise can't be initialized together")
> ```

ValueError, the error message is not precise:

"Only one of absolute_noise and relative_noise can be set"
___
*[`bioptim/limits/path_conditions.py` line 928 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPXZb5AckSWhKzKYAP:-NFPXZb6Ao3UvzGhcv-D:bs2v519) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L928)):*
> ```Python
>         if absolute_noise is not None:
>             noise_magnitude = absolute_noise
>             noise_type = True
> ```

What is this ?? Better naming : "is_absolute_noise"  or "is_relative_noise"
___
*[`bioptim/limits/path_conditions.py` line 1029 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPXkkD5WtzzlSkpRK4:-NFPXkkD5WtzzlSkpRK5:b-god5dt) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1029)):*
> ```Python
>                     * (bounds_max_matrix - bounds_min_matrix)
>                     / 2  # shift the noise to the center of the range of bounds
>             )
> ```

This has not been merged properly! 

```python3
        self.noise = (
            (np.random.random((self.n_elements, ns)) * 2 - 1)  # random noise
            * self.noise_magnitude  # magnitude of the noise within the range defined by the bounds
            * (bounds_max_matrix - bounds_min_matrix)  # scale the noise to the range of bounds
        )
```
Also, when this is an absolute noise, the last part of the calculation shouldn't be done:

```python3
self.noise = (
            (np.random.random((self.n_elements, ns)) * 2 - 1)  # random noise
            * self.noise_magnitude  # magnitude of the noise within the range defined by the bounds
        )

if relative_noise:
     self.noise *= (bounds_max_matrix - bounds_min_matrix) # scale the noise to the range of bounds
```

You should not switch of noise type, use `random.random` at first for all cases.



_Code quote:_
```Python
            self.noise = (
                    (np.random.randn(self.n_elements, ns) * 2 - 1)  # random noise
                    * self.noise_magnitude  # magnitude of the noise within the range defined by the bounds
                    * (bounds_max_matrix - bounds_min_matrix)  # scale the noise to the range of bounds
                    + bounds_min_matrix
                    + (1 - self.noise_magnitude)
                    * (bounds_max_matrix - bounds_min_matrix)
                    / 2  # shift the noise to the center of the range of bounds
            )
```
___
*[`bioptim/limits/path_conditions.py` line 1105 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPZEGSEcJyBwA-rJ1C:-NFPZEGSEcJyBwA-rJ1D:bxf080s) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1105)):*
> ```Python
>             seed: Union[int, List[int]] = 1,
>             absolute_noise: Union[list, int, float, np.ndarray] = None,
>             relative_noise: Union[list, int, float, np.ndarray] = None,
> ```

If `noise_magnitude = 1` by default in NoisedIntialGuess
relative_noise shouldn't have a default `value = None`
It's a bit dangerous.
___
*[`bioptim/limits/path_conditions.py` line 1106 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPZ22f9PPCJReyR_dz:-NFPZ22f9PPCJReyR_e-:b-sojzgc) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1106)):*
> ```Python
>             absolute_noise: Union[list, int, float, np.ndarray] = None,
>             relative_noise: Union[list, int, float, np.ndarray] = None,
>             # gaussian_noise: Union[bool, List[bool]] = True,
> ```

remove this, we are not ready to treat noise_types.
___
*[`bioptim/limits/path_conditions.py` line 1130 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPZ_tVDyUCHg2-I-6G:-NFPZ_tVDyUCHg2-I-6H:b-gwqhx0) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1130)):*
> ```Python
>         absolute_noise: Union[bool, List[bool]]
>             Get if the noise is absolute or relative to the bounds
>         gaussian_noise: Union[bool, List[bool]]
> ```

not yet please 
___
*[`bioptim/limits/path_conditions.py` line 1142 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPZxz04Mh3l0uQupij:-NFPZxz04Mh3l0uQupik:b-or8aqi) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1142)):*
> ```Python
> 
>         if len(bounds) != nb_phases:
>             raise ValueError(f"bounds must be the same length as the number of phases: {nb_phases}")
> ```

Can you put this in a method called `_check_bounds(bounds)`



_Code quote:_
```Python
        if bounds is None:
            raise ValueError("bounds must be specified to generate noised initial guess")

        if len(bounds) != nb_phases:
            raise ValueError(f"bounds must be the same length as the number of phases: {nb_phases}")
```
___
*[`bioptim/limits/path_conditions.py` line 1173 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFP_waD3JAi2Bu4aGVN:-NFP_waD3JAi2Bu4aGVO:btlg679) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1173)):*
> ```Python
>                 absolute_noise = [absolute_noise[0] for j in range(nb_phases)]
>             elif absolute_noise.shape[0] != nb_phases:
>                 raise  [...]

2022-10-27 23:18 UTC, Ipuch commented
Prefer StrEnum over number

2022-10-28 15:06 UTC, rapidnico reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: 1 of 3 files reviewed, 14 unresolved discussions (waiting on @Ipuch)

___
*[`.gitignore` line 114 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPWNxo0eB_FcaS7AMX:-NFU1f1FBeXU-AY97Aqu:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/.gitignore#L114)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove the line, just open this in pycharm and remove the line.
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 874 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPWkWB9akxOWYupl3-:-NFU1gcp5aV8vg65fLaq:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L874)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

You modified the default behavior of the code, please restore it, `relative_noise=1`
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 888 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPWdma1X4XwcvCjXCZ:-NFU2D9tApovO6VovGj-:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L888)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

The docstring is not up to date.
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 924 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPX8lc-37-RULTBn6k:-NFU1l67EmR1NKcoy_QH:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L924)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

ValueError, the error message is not precise:

"Only one of absolute_noise and relative_noise can be set"
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 928 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPXZb5AckSWhKzKYAP:-NFU1kcw7ONYUmWaL1gF:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L928)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

What is this ?? Better naming : "is_absolute_noise"  or "is_relative_noise"
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1029 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPXkkD5WtzzlSkpRK4:-NFU1NXD-j1eTKbSmMhj:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1029)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This has not been merged properly! 

```python3
        self.noise = (
            (np.random.random((self.n_elements, ns)) * 2 - 1)  # random noise
            * self.noise_magnitude  # magnitude of the noise within the range defined by the bounds
            * (bounds_max_matrix - bounds_min_matrix)  # scale the noise to the range of bounds
        )
```
Also, when this is an absolute noise, the last part of the calculation shouldn't be done:

```python3
self.noise = (
            (np.random.random((self.n_elements, ns)) * 2 - 1)  # random noise
            * self.noise_magnitude  # magnitude of the noise within the range defined by the bounds
        )

if relative_noise:
     self.noise *= (bounds_max_matrix - bounds_min_matrix) # scale the noise to the range of bounds
```

You should not switch of noise type, use `random.random` at first for all cases.

</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1105 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPZEGSEcJyBwA-rJ1C:-NFU1PYf1dOUIdJMfnsa:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1105)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

If `noise_magnitude = 1` by default in NoisedIntialGuess
relative_noise shouldn't have a default `value = None`
It's a bit dangerous.
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1106 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPZ22f9PPCJReyR_dz:-NFU1Q2q1aNMn00JEzKC:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1106)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove this, we are not ready to treat noise_types.
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1130 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPZ_tVDyUCHg2-I-6G:-NFU1QjPEJDGo7x7feJC:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1130)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

not yet please 
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1142 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPZxz04Mh3l0uQupij:-NFU1ROFBEh4aigqz3EL:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1142)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Can you put this in a method called `_check_bounds(bounds)`
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1173 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFP_waD3JAi2Bu4aGVN:-NFU1UoD1yp3016LWkzu:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1173)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

put this in _check_noise_magnitude()
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1198 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPa38D0NNC0xlzR1CW:-NFU1VLQDEhcNzyHm-JN:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1198)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same ;)
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1232 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPaOcfBH03m5SDkYVv:-NFU1WA-4uidTHBUPjaR:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1232)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

everything related to seed also needs to be in a method _check_seed()
</blockquote></details>

Done.
___
*[`bioptim/limits/path_conditions.py` line 1251 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPaGpz3wiUmXgsjjrq:-NFU1XFF56PZerxC5jzA:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/bioptim/limits/path_conditions.py#L1251)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

put this in a method too
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-02 18:41 UTC, pariterre requested changes
> Reviewed 6 of 6 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: all files reviewed, 16 unresolved discussions (waiting on @Ipuch and @rapidnico)

___
*[`.gitignore` line 114 at r3](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFPWNxo0eB_FcaS7AMX:-NFtcJkoD-EP6SALFgYu:b-enobtx) ([raw file](https://github.com/pyomeca/bioptim/blob/567eb16966947431f6a2cff07e5878f78ece41dd/.gitignore#L114)):*
<details><summary><i>Previously, rapidnico wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I've done it
___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 20 at r6](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFtcO_x51Z3nq4Lu1FS:-NFtcO_yE-aKEyQp1iRN:b-ybynwt) ([raw file](https://github.com/pyomeca/bioptim/blob/b48d21c30e6bb4ba3744d580e07bd8ef20a272ba/bioptim/examples/getting_started/custom_initial_guess.py#L20)):*
> ```Python
> import numpy as np
> import biorbd_casadi as biorbd
> from bioptim.misc.enums import MagnitudeType
> ```

Do not import from inside the module. If MagnitudeType should be exposed to users, add it to the main __init__.py file (so you can do: import MagnitudeType)



_Code quote:_
```Python
 bioptim.misc.enums import MagnitudeType
```
___
*[`tests/test_update_bounds_and_init.py` line 5 at r6](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFtdJXe0XGr5sKAFJgS:-NFtdJXe0XGr5sKAFJgT:buo9nmt) ([raw file](https://github.com/pyomeca/bioptim/blob/b48d21c30e6bb4ba3744d580e07bd8ef20a272ba/tests/test_update_bounds_and_init.py#L5)):*
> ```Python
> import biorbd_casadi as biorbd
> from casadi import MX
> from bioptim.misc.enums import MagnitudeType
> ```

Same here


<!-- Sent from Reviewable.io -->

2022-11-02 19:01 UTC, Ipuch submitted a review, later dismissed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre and @rapidnico)

___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 20 at r6](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFtcO_x51Z3nq4Lu1FS:-NFth7u-BkTBi4VEoQqs:b-1far64) ([raw file](https://github.com/pyomeca/bioptim/blob/373002e5a3409c8afafa8b6939e7a8a4877ca8ad/bioptim/examples/getting_started/custom_initial_guess.py#L20)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do not import from inside the module. If MagnitudeType should be exposed to users, add it to the main __init__.py file (so you can do: import MagnitudeType)
</blockquote></details>

And actualize the README.md too


<!-- Sent from Reviewable.io -->

2022-11-02 20:20 UTC, rapidnico reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 20 at r6](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFtcO_x51Z3nq4Lu1FS:-NFtzltQDa5Hl-Ez156m:b-528mlt) ([raw file](https://github.com/pyomeca/bioptim/blob/373002e5a3409c8afafa8b6939e7a8a4877ca8ad/bioptim/examples/getting_started/custom_initial_guess.py#L20)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

And actualize the README.md too
</blockquote></details>

Work in progress for the README.md
___
*[`tests/test_update_bounds_and_init.py` line 5 at r6](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFtdJXe0XGr5sKAFJgS:-NFtzlHZ-OmTTv1rUSt7:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/373002e5a3409c8afafa8b6939e7a8a4877ca8ad/tests/test_update_bounds_and_init.py#L5)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Same here
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-03 12:44 UTC, pariterre requested changes
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: all files reviewed, 2 unresolved discussions (waiting on @rapidnico)

___
*[`tests/test_update_bounds_and_init.py` line 5 at r6](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFtdJXe0XGr5sKAFJgS:-NFxW8Hb50rHShYr7sNj:bw98j63) ([raw file](https://github.com/pyomeca/bioptim/blob/373002e5a3409c8afafa8b6939e7a8a4877ca8ad/tests/test_update_bounds_and_init.py#L5)):*
<details><summary><i>Previously, rapidnico wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please do not flag it has done when it is not... Or make sure to push your modification!


<!-- Sent from Reviewable.io -->

2022-11-03 13:48 UTC, rapidnico reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: 4 of 9 files reviewed, 2 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 20 at r6](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFtcO_x51Z3nq4Lu1FS:-NFxjwOm9WasqWGiTnND:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/373002e5a3409c8afafa8b6939e7a8a4877ca8ad/bioptim/examples/getting_started/custom_initial_guess.py#L20)):*
<details><summary><i>Previously, rapidnico wrote…</i></summary><blockquote>

Work in progress for the README.md
</blockquote></details>

Done
___
*[`tests/test_update_bounds_and_init.py` line 5 at r6](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFtdJXe0XGr5sKAFJgS:-NFxk1nH7O8GLe1T-YST:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/373002e5a3409c8afafa8b6939e7a8a4877ca8ad/tests/test_update_bounds_and_init.py#L5)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please do not flag it has done when it is not... Or make sure to push your modification!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-03 18:14 UTC, pariterre requested changes
> Reviewed 3 of 5 files at r7, 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: all files reviewed, 4 unresolved discussions (waiting on @rapidnico)

___
*[`README.md` line 890 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFyfqLm2Nl80XT1R3fb:-NFyfqLn1IOcwM1HPMAZ:b-7onqtd) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/README.md#L890)):*
> ```Markdown
>   n_shooting,
>   bound_push,
>   seed,
> ```

Can you add types hints here?



_Code quote:_
```Markdown
  bounds,
  magnitude,
  magnitude_type,
  n_shooting,
  bound_push,
  seed,
```
___
*[`README.md` line 916 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFyfuDx8Wa5WG2WONhD:-NFyfuDx8Wa5WG2WONhE:b-h8m8za) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/README.md#L916)):*
> ```Markdown
>   n_shooting,
>   bound_push,
>   seed,
> ```

Can you add type hints here?



_Code quote:_
```Markdown
  bounds,
  magnitude,
  magnitude_type,
  n_shooting,
  bound_push,
  seed,
```
___
*[`README.md` line 1605 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFyfxMmAiNts_FmGhjJ:-NFyfxMmAiNts_FmGhjK:bctb424) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/README.md#L1605)):*
> ```Markdown
> 
> ### Enum: MagnitudeType
> todo: for nicolas + sommaire
> ```

TODO in caps so we can find them
___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 204 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFygIXyBinEyTjQELpG:-NFygIXyBinEyTjQELpH:b5bcg9j) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/bioptim/examples/getting_started/custom_initial_guess.py#L204)):*
> ```Python
> 
>         sol = ocp.solve()
>         print(initial_guess)
> ```

Keep the \n


<!-- Sent from Reviewable.io -->

2022-11-03 19:37 UTC, rapidnico reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @pariterre)

___
*[`README.md` line 890 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFyfqLm2Nl80XT1R3fb:-NFyzY1bDIrrcGFp7WgO:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/README.md#L890)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Can you add types hints here?
</blockquote></details>

Done.
___
*[`README.md` line 916 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFyfuDx8Wa5WG2WONhD:-NFyzaDg9nkK3t3KAbI2:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/README.md#L916)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Can you add type hints here?
</blockquote></details>

Done.
___
*[`README.md` line 1605 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFyfxMmAiNts_FmGhjJ:-NFyzc_fDznJCC3h_Tna:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/README.md#L1605)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

TODO in caps so we can find them
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 204 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFygIXyBinEyTjQELpG:-NFyzg243iAKFqGEBOnS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/bioptim/examples/getting_started/custom_initial_guess.py#L204)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Keep the \n
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-03 20:51 UTC, Ipuch commented
Ready to merge ? :)

2022-11-03 21:11 UTC, rapidnico commented
Ready to merge !

2022-11-04 13:49 UTC, Ipuch commented
@pariterre pinging

2022-11-04 19:56 UTC, pariterre requested changes
So near and yet so far!

> Reviewed 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560#-:-NG3Cm8G77F5WkeueaXk:b-48ykwc)* status: all files reviewed, 1 unresolved discussion (waiting on @rapidnico)

___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 204 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFygIXyBinEyTjQELpG:-NG3CeqrD6dkfvHBtOna:b-tb14gx) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/bioptim/examples/getting_started/custom_initial_guess.py#L204)):*
<details><summary><i>Previously, rapidnico wrote…</i></summary><blockquote>

Done.
</blockquote></details>

That should be \n and not /n


<!-- Sent from Reviewable.io -->

2022-11-04 20:00 UTC, rapidnico reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/examples/getting_started/custom_initial_guess.py` line 204 at r8](https://reviewable.io/reviews/pyomeca/bioptim/560#-NFygIXyBinEyTjQELpG:-NG3DdS0CXipkREZrJ43:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/7ae6bef8845fd8f5f544ae06033c707b33996dd1/bioptim/examples/getting_started/custom_initial_guess.py#L204)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

That should be \n and not /n
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-04 20:31 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/560#-:-NG3KudU3-_y301q3ym4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rapidnico)



<!-- Sent from Reviewable.io -->

2022-11-04 20:33 UTC, merged