Implicit defect type for muscles
pyomeca/bioptim pull request #561
Opened 2022-10-25 21:58 UTC by Ipuch

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [x] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [x] Have you written new tests for your core changes, as applicable?

Cannot build the tests for muscles because master is not updated with #551

2022-10-27 19:57 UTC, pariterre requested changes
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/561)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/dynamics/dynamics_functions.py` line 490 at r1](https://reviewable.io/reviews/pyomeca/bioptim/561#-NFQ0D7bBAmxI8X5YDzD:-NFQ0D7bBAmxI8X5YDzE:b5ru4bb) ([raw file](https://github.com/pyomeca/bioptim/blob/cea20038b7c1bea773efc2f999989dc9b727acaa/bioptim/dynamics/dynamics_functions.py#L490)):*
> ```Python
> 
>         defects = None
>         # todo: contacts and fatigue to be handled with implicit dynamics
> ```

Put TODO in caps so we can easily find it


<!-- Sent from Reviewable.io -->

2022-10-27 23:18 UTC, Ipuch commented
Don't merge, it's not tested 😀

2022-10-28 20:10 UTC, Ipuch reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/561)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 490 at r1](https://reviewable.io/reviews/pyomeca/bioptim/561#-NFQ0D7bBAmxI8X5YDzD:-NFVCvhW6VHa-IndjFPj:bs7wumb) ([raw file](https://github.com/pyomeca/bioptim/blob/eac2db5874cdec49231581ed6c0c7b00844aa7ad/bioptim/dynamics/dynamics_functions.py#L490)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Put TODO in caps so we can easily find it
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-10-28 20:57 UTC, Ipuch commented
It passed except for fatigue...

2022-10-31 20:58 UTC, Ipuch commented
@pariterre approval?

2022-11-02 17:19 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/561#-:-NFtLeE-9-TujZAmGnMa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Ipuch)



<!-- Sent from Reviewable.io -->

2022-11-02 17:55 UTC, merged