[WIP] Check Conditioning
pyomeca/bioptim pull request #573
Opened 2022-11-08 16:09 UTC by Julo0

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request? issue #306
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2022-11-09 18:56 UTC, EveCharbie reviewed
Goog job @julo0! Thanks for that :)

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/573#-:-NGSjtr81eovCx9oVToS:b-j598pz)* status: 0 of 5 files reviewed, 11 unresolved discussions (waiting on @Julo0)

___
*[`bioptim/examples/getting_started/example_multiphase_checkconditioning.py` line 6 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfJS6EtJt2JuNP3N8:-NGSfJS7AFvrBaWm1JVP:b5lilh8) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/examples/getting_started/example_multiphase_checkconditioning.py#L6)):*
> ```Python
> Finally, an objective for the transition continuity on the control is added. Please note that the "last" control
> of the previous phase is the last shooting node (and not the node arrival).
> It is designed to show how one can define a multiphase optimal control program
> ```

This example might be removed, as ocp.check_conditionning does the work.



_Code quote:_
```Python
This example is a trivial box that must superimpose one of its corner to a marker at the beginning of the movement and
a the at different marker at the end of each phase. Moreover a constraint on the rotation is imposed on the cube.
Finally, an objective for the transition continuity on the control is added. Please note that the "last" control
of the previous phase is the last shooting node (and not the node arrival).
It is designed to show how one can define a multiphase optimal control program
```
___
*[`bioptim/examples/getting_started/pendulum.py` line 13 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfahD6kJ1wmJ89x8F:-NGSfahD6kJ1wmJ89x8G:bery3ip) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/examples/getting_started/pendulum.py#L13)):*
> ```Python
> 
> import biorbd_casadi as biorbd
> ```

might have to reblack
___
*[`bioptim/optimization/optimal_control_program.py` line 905 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfidUA1JYTiUuWTGw:-NGSfidUA1JYTiUuWTGx:b-ix5bbu) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L905)):*
> ```Python
> 
>     def Check_Conditioning(self):
>         """
> ```

use_lower_case for methods



_Code quote:_
```Python
    def Check_Conditioning(self):
```
___
*[`bioptim/optimization/optimal_control_program.py` line 954 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfsbkBUjWyg9qYosY:-NGSfsbkBUjWyg9qYosZ:bs2p0dg) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L954)):*
> ```Python
>             hessian_norm_list = []
> 
>             ###-----JACOBIAN-----###
> ```

comment with single 



_Code quote:_
```Python
###-----JACOBIAN-----###
```
___
*[`bioptim/optimization/optimal_control_program.py` line 985 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSgN9fEFTnF1OghQZC:-NGSgN9fEFTnF1OghQZD:b-n854wz) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L985)):*
> ```Python
>                                     vertcat(*self.nlp[phase].X, *self.nlp[phase].U, self.nlp[phase].parameters.cx),
>                                 )
>                             )
> ```

keep only the vertcat with *parameters in the if. The rest (list_constraints.append) is the same for both cases so it can be moved outside the if.
Also, it will allow to reuse the *parameter value in jac_func making the next if not necessary.



_Code quote:_
```Python
                            list_constraints.append(
                                jacobian(
                                    self.nlp[phase]
                                    .g[i]
                                    .function(
                                        self.nlp[phase].states.cx,
                                        self.nlp[phase].controls.cx,
                                        self.nlp[phase].parameters.cx,
                                    )[axis],
                                    vertcat(*self.nlp[phase].X, *self.nlp[phase].U, self.nlp[phase].parameters.cx),
                                )
                            )
```
___
*[`bioptim/optimization/optimal_control_program.py` line 1017 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGShHDz3qflpoqQQuwb:-NGShHDz3qflpoqQQuwc:b-nh0sgx) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1017)):*
> ```Python
> 
>                 # evaluate jac_func at X_init, U_init, considering the parameters
>                 X_init = np.zeros((len(self.nlp[phase].X), self.nlp[phase].x_init.shape[0]))
> ```

use_lower_case for variables too



_Code quote:_
```Python
X_init
```
___
*[`bioptim/optimization/optimal_control_program.py` line 1120 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSh_qI-Tu5lpdy0Mn0:-NGSh_qI-Tu5lpdy0Mn1:b-pc7kko) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1120)):*
> ```Python
> 
>                         else:
>                             do = "nothing"
> ```

can be removed



_Code quote:_
```Python
                        else:
                            do = "nothing"
```
___
*[`bioptim/optimization/optimal_control_program.py` line 1129 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGShixv94oiDZgQMKIZ:-NGShixv94oiDZgQMKI_:b-22wexd) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1129)):*
> ```Python
>                     for row in range(list_hessian[nb_hessian].shape[0]):
>                         for column in range(list_hessian[nb_hessian].shape[1]):
>                             norm += list_hessian[nb_hessian][row, column] ** 2
> ```

Isn't there a build in casadi function to do that ? (genuine question, otherwise it is good as it is :)) 



_Code quote:_
```Python
 norm
```
___
*[`bioptim/optimization/optimal_control_program.py` line 1141 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSi7lk1aKg5Rv7Mqsk:-NGSi7lk1aKg5Rv7Mqsl:bsxglku) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1141)):*
> ```Python
> 
>             Returns
>             -------
> ```

remove return as it does not return anything



_Code quote:_
```Python
            Returns
            -------
```
___
*[`bioptim/optimization/optimal_control_program.py` line 1237 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSiH3J6O1IcV9MJ-mT:-NGSiH3J6O1IcV9MJ-mU:bm9jq82) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1237)):*
> ```Python
>             hessian_obj_list = []
>             for phase in range(0, len(self.nlp)):
>                 # hessian_obj = 0
> ```

remove leftover comments



_Code quote:_
```Python
# hessian_obj = 0
```
___
*[`bioptim/optimization/optimal_control_program.py` line 1296 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSjMxi9ZfmY5jf7ee-:-NGSjMxi9ZfmY5jf7ee0:bw9mnhv) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1296)):*
> ```Python
>                         )
>                         # to handle piecewise constant in controls we have to compute the value for the end of the interval
>                         # which only relies on the value of the control at the beginning of the interval
> ```

you can remove comments you did not add yourself



_Code quote:_
```Python
                        # to handle piecewise constant in controls we h [...]

2022-11-10 14:56 UTC, pariterre requested changes
> Reviewed 3 of 5 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/573)* status: 4 of 5 files reviewed, 22 unresolved discussions (waiting on @EveCharbie and @Julo0)

___
*[`README.md` line 334 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGWxaSUChdA9KjlEgst:-NGWxaSUChdA9KjlEgsu:befys93) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/README.md#L334)):*
> ```Markdown
> To visualize it, you can use
> ```python
> ocp.Check_Conditioning()
> ```

please use snake_case (meaning `ocp.check_conditioning()` instead of `ocp.Check_Conditioning()` as specified in the official python naming conventiont (https://peps.python.org/pep-0008/#naming-conventions)
___
*[`bioptim/examples/getting_started/example_multiphase_checkconditioning.py` line 6 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfJS6EtJt2JuNP3N8:-NGWyC0c7FQhg9OkoevT:b-5htib7) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/examples/getting_started/example_multiphase_checkconditioning.py#L6)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

This example might be removed, as ocp.check_conditionning does the work.
</blockquote></details>

Also since it is so complicated, it is definitely not a `getting_started`, but I advocate for the removal. Maybe add the check in pendulum (commented, but present)
___
*[`bioptim/optimization/optimal_control_program.py` line 1129 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGShixv94oiDZgQMKIZ:-NGWyojq63uyTdBINttK:b-i50q0l) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1129)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

Isn't there a build in casadi function to do that ? (genuine question, otherwise it is good as it is :)) 
</blockquote></details>

please use `idx` for indices. That said `for hessian in list_hessian:` is actually better
___
*[`bioptim/optimization/optimal_control_program.py` line 1134 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGWzAiO5SzW148HMY4m:-NGWzAiO5SzW148HMY4n:b-2nd5t8) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1134)):*
> ```Python
>             return jacobian_list, jacobian_rank, tick_labels_list, hessian_norm_list
> 
>         def Check_constraints_plot():
> ```

This a plotting method, I think it would make sense to take this out of OCP, as it is already big, and to put it in a designated class. I would keep an interface to this plot in ocp though
___
*[`bioptim/optimization/optimal_control_program.py` line 1166 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGWzeWkAjIEOf9yDvpt:-NGWzeWkAjIEOf9yDvpu:b1g89pw) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1166)):*
> ```Python
>             # PLOT GENERAL
>             fig, axis = plt.subplots(1, 2 * len(self.nlp))
>             for ax in range(0, len(self.nlp)):
> ```

As a general rule, if you find yourself writing `for idx in range(len(all_x)):` you are doing something wrong. Do `for x in all_x:`instead. If for some reason you need the index, call it index and use `enumerate()`. Finally it seems that nlp is not even used, but `axis` is, maybe you wanted to loop over axis?  i'd suggest `for i, axis in enumerate(axes):` 



_Code quote:_
```Python
range(0, len(self.nlp))
```
___
*[`bioptim/optimization/optimal_control_program.py` line 1196 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGX004U2jtSdWCgsW6u:-NGX004WE5Pl9V4rVFHu:bwhn4rp) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1196)):*
> ```Python
> 
>                 # Hessian constraints plot
>                 hessian_norm_list[ax][~(hessian_norm_list[ax] != 0).astype(bool)] = np.nan
> ```

Wow, that is complicated... what does this do? can you simplify that?



_Code quote:_
```Python
~(hessian_norm_list[ax] != 0).astype(bool)
```
___
*[`bioptim/optimization/optimal_control_program.py` line 1200 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGX0Bj-6wrtbsRmlPH7:-NGX0Bj-6wrtbsRmlPH8:bczugj) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1200)):*
> ```Python
>                 current_cmap2.set_bad(color="k")
>                 norm2 = mcolors.TwoSlopeNorm(vmin=min_norm - 0.01, vmax=max_norm + 0.01, vcenter=0)
>                 liste_ytick = []
> ```

please don't used french wording. Also, most of the time it is useless to specify it is a list, just use plural
___
*[`bioptim/optimization/optimal_control_program.py` line 1210 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGX-rJ45RHt0qoBHISH:-NGX-rJ52-u1waikzUiQ:bp7qqud) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1210)):*
> ```Python
>                     "Hessian constraint norms \n Phase " + str(ax), fontweight="bold", fontsize=8
>                 )
>                 axis[ax + len(self.nlp)].set_xticks([0])
> ```

len(self.nlp) is n_phases isn't it?
___
*[`bioptim/optimization/optimal_control_program.py` line 1219 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGWzQja-x1n-IqUGgO5:-NGWzQja-x1n-IqUGgO6:b-mbmss2) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1219)):*
> ```Python
>             plt.suptitle("Check conditioning for constraints ", color="b", fontsize=15, fontweight="bold")
> 
>         def Hessian_objective():
> ```

Do not capitalized method names
___
*[`bioptim/optimization/optimal_control_program.py` line 1224 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGX0SCh7jYHQoJFY4_c:-NGX0SCh7jYHQoJFY4_d:b-tzzq5o) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1224)):*
> ```Python
>             Returns
>             -------
>             A list with the hessian of objectives evaluate at initial time for each phase
> ```

Unless it is intended to be modified, prefer tuple to list whenever possible
___
*[`bioptim/optimization/optimal_control_program.py` line 1375 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGX1ENzBDLi1nxnFbWI:-NGX1ENzBDLi1nxnFbWJ:b-paol5n) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1375)):*
> ```Python
>             ###---Convexity checking (positive semi-definite hessian)---###
>             # On R (convexe), the objective is convexe if and only if the hessian is positive semi definite (psd)
>             # And, as the hessian is symetric (Schwarz), the hessian is psd if and only if the eigenvalues are positive
> ```

I think psd is necessary condition but not sufficient condition. Positive definite on the other is sufficient condition. But I may be wrong
___
*[`bioptim/optimization/optimal_control_program.py` line 1394 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGX1bpY1DBZJGkNOB2-:-NGX1bpY1DBZJGkNOB20:b-12h23d) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1394)):*
> ```Python
>             return hessian_obj_list, condition_number, convexity
> 
>         def Check_objective_plot():
> ```

Do not capitalize method's name
___
*[`tests/test__global_plots.py` line 35 at r3](https://reviewable.io/reviews/pyomeca/bi [...]

2022-11-10 18:31 UTC, pariterre requested changes
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/573)* status: 4 of 5 files reviewed, 23 unresolved discussions (waiting on @EveCharbie and @Julo0)

___
*[`bioptim/optimization/optimal_control_program.py` line 1208 at r4](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGXnouL1Hx_TgoTRFac:-NGXnouM6exOHPEOf_t4:b-pxnscv) ([raw file](https://github.com/pyomeca/bioptim/blob/3992d67ca1994610a344493981863d5d5f350e21/bioptim/optimization/optimal_control_program.py#L1208)):*
> ```Python
>             hessian_obj_list = []
>             for phase in range(0, len(self.nlp)):
>                 for obj in range(0, len(self.nlp[phase].J)):
> ```

try :

`for j in self.nlp[phase].J:`



_Code quote:_
```Python
for obj in range(0, len(self.nlp[phase].J)):
```


<!-- Sent from Reviewable.io -->

2022-11-10 20:59 UTC, Julo0 reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/573)* status: 1 of 6 files reviewed, 23 unresolved discussions (waiting on @EveCharbie and @pariterre)

___
*[`README.md` line 334 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGWxaSUChdA9KjlEgst:-NGXWvlO2JrQM8kwFiX2:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/README.md#L334)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please use snake_case (meaning `ocp.check_conditioning()` instead of `ocp.Check_Conditioning()` as specified in the official python naming conventiont (https://peps.python.org/pep-0008/#naming-conventions)
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/example_multiphase_checkconditioning.py` line 6 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfJS6EtJt2JuNP3N8:-NGYExLc9zbRTlWQ122V:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/examples/getting_started/example_multiphase_checkconditioning.py#L6)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Also since it is so complicated, it is definitely not a `getting_started`, but I advocate for the removal. Maybe add the check in pendulum (commented, but present)
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/pendulum.py` line 13 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfahD6kJ1wmJ89x8F:-NGXXCK64x5EuEBr2Q7X:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/examples/getting_started/pendulum.py#L13)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

might have to reblack
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 905 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfidUA1JYTiUuWTGw:-NGY2Iuz2bNOSsxhuImG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L905)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

use_lower_case for methods
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 954 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSfsbkBUjWyg9qYosY:-NGXXk9P-3DweqOJmU3L:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L954)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

comment with single 
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 985 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSgN9fEFTnF1OghQZC:-NGXXlCfA8_Cgt229Ea8:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L985)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

keep only the vertcat with *parameters in the if. The rest (list_constraints.append) is the same for both cases so it can be moved outside the if.
Also, it will allow to reuse the *parameter value in jac_func making the next if not necessary.
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1017 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGShHDz3qflpoqQQuwb:-NGXXluP-C317Y6qxad3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1017)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

use_lower_case for variables too
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1120 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSh_qI-Tu5lpdy0Mn0:-NGXXnF2EWK3lbpSB3pW:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1120)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

can be removed
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1129 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGShixv94oiDZgQMKIZ:-NGXlc4YBoFJrQZFFIua:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1129)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please use `idx` for indices. That said `for hessian in list_hessian:` is actually better
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1141 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSi7lk1aKg5Rv7Mqsk:-NGXlj7pEFdxz_ecq_cf:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1141)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

remove return as it does not return anything
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1237 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSiH3J6O1IcV9MJ-mT:-NGXmglkD6D5JP8T4Xph:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1237)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

remove leftover comments
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1296 at r1](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGSjMxi9ZfmY5jf7ee-:-NGXmils1FCilkORZkYJ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/fc62f8fc599c3dbffd3d96f0b6c5025b8fe7e41d/bioptim/optimization/optimal_control_program.py#L1296)):*
<details><summary><i>Previously, EveCharbie (Eve Charbonneau) wrote…</i></summary><blockquote>

you can remove comments you did not add yourself
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1134 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGWzAiO5SzW148HMY4m:-NGYD60l8Wy1DUDMyYJS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1134)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This a plotting method, I think it would make sense to take this out of OCP, as it is already big, and to put it in a designated class. I would keep an interface to this plot in ocp though
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1166 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NGWzeWkAjIEOf9yDvpt:-NGY5UU10NLD7d60DnnT:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L1166)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

As a general rule, if you find yourself writing `for idx in range(len(all_x)):` you are doing something wrong. Do `for x in all_x:`instead. If for some reason you need the index, call it index and use `enumerate()`. Finally it seems that nlp is not even used, but `axis` is, maybe you wanted to loop over axis?  i'd suggest `for i, axis in enumerate(axes):` 
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 1196 at r2](https://reviewab [...]

2022-11-17 20:41 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 3 files at r5, 2 of 2 files at r6, 2 of 2 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/573#-:-NH6Jhmg5wfblVssbmhl:bnfp4nl)* status: all files reviewed, 13 unresolved discussions (waiting on @EveCharbie and @Julo0)

___
*[`bioptim/examples/getting_started/pendulum.py` line 113 at r8](https://reviewable.io/reviews/pyomeca/bioptim/573#-NH6IlRF0D0Q24Htz6F8:-NH6IlRF0D0Q24Htz6F9:b-rwkldi) ([raw file](https://github.com/pyomeca/bioptim/blob/9fd0c80d57ce4511f094e5177c3f883dfa70a51f/bioptim/examples/getting_started/pendulum.py#L113)):*
> ```Python
>     # Custom plots
>     ocp.add_plot_penalty(CostType.ALL)
>     # ocp.check_conditioning()
> ```

Please add a comment before (for instance: `If one is interested in checking the conditioning of the problem, they can uncomment the following line`)



_Code quote:_
```Python
 # ocp.check_conditioning()
```
___
*[`bioptim/optimization/optimal_control_program.py` line 56 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NH6J4uuCo5ziQ3KZuW0:-NH6J4uuCo5ziQ3KZuW1:bjevj3k) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L56)):*
> ```Python
> from ..optimization.solution import Solution
> 
> check_version(biorbd, "1.9.1", "1.10.0")
> ```

This is VERY important!



_Code quote:_
```Python
check_version(biorbd, "1.9.1", "1.10.0")
```


<!-- Sent from Reviewable.io -->

2022-11-18 15:25 UTC, Julo0 reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/573)* status: 1 of 6 files reviewed, 13 unresolved discussions (waiting on @EveCharbie and @pariterre)

___
*[`bioptim/examples/getting_started/pendulum.py` line 113 at r8](https://reviewable.io/reviews/pyomeca/bioptim/573#-NH6IlRF0D0Q24Htz6F8:-NH6T_m6ECjCBCswwtnd:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9fd0c80d57ce4511f094e5177c3f883dfa70a51f/bioptim/examples/getting_started/pendulum.py#L113)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please add a comment before (for instance: `If one is interested in checking the conditioning of the problem, they can uncomment the following line`)
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimal_control_program.py` line 56 at r2](https://reviewable.io/reviews/pyomeca/bioptim/573#-NH6J4uuCo5ziQ3KZuW0:-NH6TaQn99kz--4CvuFO:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/405fe96261e3fc2dea6356d271e97958ff988802/bioptim/optimization/optimal_control_program.py#L56)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This is VERY important!
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-11-21 14:24 UTC, EveCharbie commented
@pariterre could you approve running the tests please?

2022-11-24 15:59 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 4 files at r9, 3 of 3 files at r10, 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/573#-:-NHeMR4v8UmNn2o_gP5T:bnfp4nl)* status: all files reviewed, 11 unresolved discussions (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2022-11-24 16:07 UTC, EveCharbie reviewed
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/573)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Julo0)



<!-- Sent from Reviewable.io -->

2022-11-24 18:57 UTC, merged