[WIP] Passive Torque
pyomeca/bioptim pull request #584
Opened 2022-12-06 17:08 UTC by AntoineLeroy

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2022-12-08 18:32 UTC, pariterre requested changes
> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: 6 of 7 files reviewed, 11 unresolved discussions (waiting on @AntoineLeroy)

___
*[`bioptim/dynamics/dynamics_functions.py` line 121 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzfdz5NrzQtk6kzLu:-NImzfdz5NrzQtk6kzLv:b-gwewk5) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L121)):*
> ```Python
>         passive_torque = nlp.model.passiveJointTorque(q, qdot)
>         tau = DynamicsFunctions.__get_fatigable_tau(nlp, states, controls, fatigue)
>         tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before

Also please make sure 
`a + b if c else a`
is actually the same as
`(a + b) if c else a` 

(i.e. tau is not added twice)



_Code quote:_
```Python
.to_mx()
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 264 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzl97EzenYKoX_i3f:-NImzl985OwSQUmB2Ohh:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L264)):*
> ```Python
>         passive_torque = nlp.model.passiveJointTorque(q, qdot)
>         tau = nlp.model.torque(tau_activations, q, qdot).to_mx()
>         tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before



_Code quote:_
```Python
.to_mx()
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 315 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzmQcBjCxOaS3B8Mk:-NImzmQcBjCxOaS3B8Ml:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L315)):*
> ```Python
>         tau = DynamicsFunctions.get(nlp.states["tau"], states)
>         passive_torque = nlp.model.passiveJointTorque(q, qdot)
>         tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before



_Code quote:_
```Python
.to_mx()
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 421 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzo3Z3Ya8AkjfzE91:-NImzo3Z3Ya8AkjfzE92:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L421)):*
> ```Python
>         tau = nlp.model.torque(tau_activations, q, qdot).to_mx()
>         passive_torque = nlp.model.passiveJointTorque(q, qdot)
>         tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before



_Code quote:_
```Python
.to_mx()
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 510 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzp8l1UYtiUCliQ2s:-NImzp8l1UYtiUCliQ2t:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L510)):*
> ```Python
>         tau = muscles_tau + residual_tau if residual_tau is not None else muscles_tau
>         passive_torque = nlp.model.passiveJointTorque(q, qdot)
>         tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before



_Code quote:_
```Python
.to_mx()
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 591 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzsyJ2LcckEh3IZVh:-NImzsyJ2LcckEh3IZVi:b-k4exnw) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L591)):*
> ```Python
>         muscles_tau = DynamicsFunctions.compute_tau_from_muscle(nlp, q, qdot, mus_activations)
> 
>         passive_torque = nlp.model.passiveJointTorque(q, qdot)
> ```

to mx?



_Code quote:_
```Python
e(q, qdot)
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 735 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzvyy6dpeorn1LzOR:-NImzvyy6dpeorn1LzOS:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L735)):*
> ```Python
>         qdot_var = nlp.states["qdot"] if "qdot" in nlp.states else nlp.controls["qdot"]
>         passive_torque = nlp.model.passiveJointTorque(q, qdot)
>         tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before



_Code quote:_
```Python
.to_mx()
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 789 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzxk649Pr6ipQ9406:-NImzxk649Pr6ipQ9407:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L789)):*
> ```Python
>             for i, f_ext in enumerate(nlp.external_forces):
>                 tau[:, i] = nlp.model.InverseDynamics(q, qdot, qddot, f_ext).to_mx()
>             tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before



_Code quote:_
```Python
to_mx(
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 793 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzz-72XjKCU9y7AiJ:-NImzz-72XjKCU9y7AiK:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L793)):*
> ```Python
>         else:
>             tau = nlp.model.InverseDynamics(q, qdot, qddot).to_mx()
>             tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before



_Code quote:_
```Python
to_mx()
```
___
*[`bioptim/limits/constraints.py` line 386 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NIn-6Tu3HbcYf0cP_zm:-NIn-6Tu3HbcYf0cP_zn:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/limits/constraints.py#L386)):*
> ```Python
>             qddot = nlp.states["qddot"].mx if "qddot" in nlp.states.keys() else nlp.controls["qddot"].mx
>             passive_torque = nlp.model.passiveJointTorque(q, qdot)
>             tau = tau + passive_torque.to_mx() if with_passive_torque else tau
> ```

move the to_mx() before



_Code quote:_
```Python
.to_mx()
```
___
*[`bioptim/limits/constraints.py` line 481 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NIn-7oOAof5BK1XPQle:-NIn-7oP-3RyjHOyfGM-:b-vvbdh4) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/limits/constraints.py#L481)):*
> ```Python
>                 muscles_states[k].setActivation(muscle_activations[k])
>             muscle_tau = nlp.model.muscularJointTorque(muscles_states, q, qdot).to_mx()
>             muscle_tau = muscle_tau + passive_torque.to_mx() if with_passive_torque else muscle_tau
> ```

move the to_mx() before



_Code quote:_
```Python
.to_mx(
```


<!-- Sent from Reviewable.io -->

2022-12-12 14:39 UTC, pariterre reviewed
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: 5 of 7 files reviewed, 9 unresolved discussions (waiting on @AntoineLeroy)



<!-- Sent from Reviewable.io -->

2022-12-12 16:40 UTC, AntoineLeroy reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: 4 of 7 files reviewed, 9 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 121 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzfdz5NrzQtk6kzLu:-NJ6Bd-h57jcbEhqmLgQ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L121)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move the to_mx() before

Also please make sure 
`a + b if c else a`
is actually the same as
`(a + b) if c else a` 

(i.e. tau is not added twice)
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 421 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzo3Z3Ya8AkjfzE91:-NJ6Bbo94QX0XgEPuC0I:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L421)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move the to_mx() before
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 510 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzp8l1UYtiUCliQ2s:-NJ6Bb-GAV6-Ym2-UipW:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L510)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move the to_mx() before
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 591 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzsyJ2LcckEh3IZVh:-NJ6Ba5p2FmJwv1lkKbb:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L591)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

to mx?
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 735 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzvyy6dpeorn1LzOR:-NJ6BtZw8533_w7JtwEy:bqgt2jx) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L735)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move the to_mx() before
</blockquote></details>

obsolete with bioptim 3.0
___
*[`bioptim/dynamics/dynamics_functions.py` line 789 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzxk649Pr6ipQ9406:-NJ6BwrJ2tXlUCEVXDV4:bqgt2jx) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L789)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move the to_mx() before
</blockquote></details>

obsolete with bioptim 3.0
___
*[`bioptim/dynamics/dynamics_functions.py` line 793 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzz-72XjKCU9y7AiJ:-NJ6BxTS0hR-Wd5VaLwJ:bqgt2jx) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L793)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move the to_mx() before
</blockquote></details>

obsolete with bioptim 3.0
___
*[`bioptim/limits/constraints.py` line 386 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NIn-6Tu3HbcYf0cP_zm:-NJ6Bg7NAFm8bNyz_Rdg:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/limits/constraints.py#L386)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move the to_mx() before
</blockquote></details>

Done.
___
*[`bioptim/limits/constraints.py` line 481 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NIn-7oOAof5BK1XPQle:-NJ6BgeI8vEQTMC4l4OH:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/limits/constraints.py#L481)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

move the to_mx() before
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-13 20:37 UTC, Ipuch requested changes
> Reviewed 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: all files reviewed, 21 unresolved discussions (waiting on @AntoineLeroy and @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 343 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJC9zhm45SnE5LXLRUK:-NJC9zhm45SnE5LXLRUL:br5z1mk) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/dynamics/dynamics_functions.py#L343)):*
> ```Python
>                                   parameters: MX.sym,
>                                   nlp,
>                                   with_passive_torque: bool = False) -> MX:
> ```

please black
___
*[`bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py` line 9 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAJnm8-8XjzKpdabz:-NJCAJnm8-8XjzKpdac-:b-n12qau) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py#L9)):*
> ```Python
> 
> During the optimization process, the graphs are updated real-time (even though it is a bit too fast and short to really
> appreciate it). Finally, once it finished optimizing, it animates the model using the optimal solution
> ```

please re-write the description in accordance with the example.
___
*[`bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py` line 39 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAZ2C3YFxhXTouq4o:-NJCAZ2C3YFxhXTouq4p:byax6ep) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py#L39)):*
> ```Python
>     n_threads: int = 1,
>     rigidbody_dynamics=RigidBodyDynamics.ODE,
>     with_passive_torque= False,
> ```

keep only necessary
___
*[`bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py` line 57 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAaDc5cqSwZKUoVhK:-NJCAaDc5cqSwZKUoVhL:beykwik) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py#L57)):*
> ```Python
>         If the SX variable should be used instead of MX (can be extensive on RAM)
>     n_threads: int
>         The number of threads to use in the paralleling (1 = no parallel computing)
> ```

update docstrings
___
*[`bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py` line 123 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAkpd7t2Act6QvuRH:-NJCAkpd7t2Act6QvuRI:b-l6mwxj) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py#L123)):*
> ```Python
> 
>     # --- If one is interested in checking the conditioning of the problem, they can uncomment the following line --- #
>     # ocp.check_conditioning()
> ```

remove
___
*[`bioptim/interfaces/biomodel.py` line 196 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAtBBCWCeOIuoPIaM:-NJCAtBBCWCeOIuoPIaN:b2yy9nu) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/interfaces/biomodel.py#L196)):*
> ```Python
> 
>     def ligament_joint_torque(self, q, qdot) -> MX:
>         """Get the ligament joint torque"""
> ```

plz black and remove ligament
___
*[`bioptim/interfaces/biorbd_model.py` line 304 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBEQJC0CC1Fqnx_1e:-NJCBEQJC0CC1Fqnx_1f:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/interfaces/biorbd_model.py#L304)):*
> ```Python
>     def ligament_joint_torque(self, q, qdot) -> MX:
> 
>         return self.model.ligamentsJointTorque(q, qdot).to_mx()
> ```

same
___
*[`tests/test_dynamics.py` line 293 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBhWM4wpQQ4YzZnlo:-NJCBhWM4wpQQ4YzZnlp:b-hfpv2h) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_dynamics.py#L293)):*
> ```Python
> @pytest.mark.parametrize("with_external_force", [False, True])
> @pytest.mark.parametrize("with_contact", [False, True])
> def test_torque_derivative_driven(with_contact, with_external_force, with_passive_torque, cx):
> ```

remove 
___
*[`tests/test_dynamics.py` line 308 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBk4B13edf8zcgpV0:-NJCBk4CBE9i9DOQehmc:b-l6mwxj) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_dynamics.py#L308)):*
> ```Python
> 
>     NonLinearProgram.add(
>         ocp, "dynamics_type", Dynamics(DynamicsFcn.TORQUE_DERIVATIVE_DRIVEN, with_contact=with_contact, with_passive_torque=with_passive_torque), False
> ```

remove
___
*[`tests/test_dynamics.py` line 674 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBlfV692wXPaIYWXs:-NJCBlfV692wXPaIYWXt:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_dynamics.py#L674)):*
> ```Python
> @pytest.mark.parametrize("with_external_force", [False, True])
> @pytest.mark.parametrize("with_contact", [False, True])
> def test_torque_activation_driven(with_contact, with_external_force, with_passive_torque, cx):
> ```

same
___
*[`tests/test_dynamics.py` line 687 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBmvTDcwXBJM6HlRn:-NJCBmvTDcwXBJM6HlRo:brpmoq0) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_dynamics.py#L687)):*
> ```Python
>     nlp.control_type = ControlType.CONSTANT
>     NonLinearProgram.add(
>         ocp, "dynamics_type", Dynamics(DynamicsFcn.TORQUE_ACTIVATIONS_DRIVEN, with_contact=with_contact, with_passive_torque=with_passive_torque), False
> ```

remove ?
___
*[`tests/test_passive_torque.py` line 1 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCC0u-EARTFA-_bKLK:-NJCC0u-EARTFA-_bKLL:b-k0cxtg) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_passive_torque.py#L1)):*
> ```Python
> import pytest
> ```

move to the same file "test_passive_torque.py"


<!-- Sent from Reviewable.io -->

2022-12-15 14:42 UTC, AntoineLeroy reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: 3 of 13 files reviewed, 21 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 343 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJC9zhm45SnE5LXLRUK:-NJCLKxm1F1rFScI3Geh:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/dynamics/dynamics_functions.py#L343)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

please black
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py` line 9 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAJnm8-8XjzKpdabz:-NJHWLPR3Y6nnN-YB78z:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py#L9)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

please re-write the description in accordance with the example.
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py` line 39 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAZ2C3YFxhXTouq4o:-NJLE9Pi0qr2LpMxQADo:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py#L39)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

keep only necessary
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py` line 57 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAaDc5cqSwZKUoVhK:-NJCLIBG-r0TxMsKTJnL:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py#L57)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

update docstrings
</blockquote></details>

Done.
___
*[`bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py` line 123 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAkpd7t2Act6QvuRH:-NJCLCu93QCNm32K7dZs:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/examples/torque_driven_ocp/pendulum_with_passive_torque.py#L123)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 196 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCAtBBCWCeOIuoPIaM:-NJCLEGd2-r6e2VWnPBR:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/interfaces/biomodel.py#L196)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

plz black and remove ligament
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biorbd_model.py` line 304 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBEQJC0CC1Fqnx_1e:-NJCLFEyBRUONiU0lJkg:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/bioptim/interfaces/biorbd_model.py#L304)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`tests/test_dynamics.py` line 293 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBhWM4wpQQ4YzZnlo:-NJCLRFW-gGBoAZCy-p3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_dynamics.py#L293)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove 
</blockquote></details>

Done.
___
*[`tests/test_dynamics.py` line 308 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBk4B13edf8zcgpV0:-NJCLSI7Cp2ybaw6yHpe:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_dynamics.py#L308)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`tests/test_dynamics.py` line 674 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBlfV692wXPaIYWXs:-NJCLSi64hL6Zt2OL8oB:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_dynamics.py#L674)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`tests/test_dynamics.py` line 687 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCBmvTDcwXBJM6HlRn:-NJCLTIcBg2MCE9Uxd2O:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_dynamics.py#L687)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove ?
</blockquote></details>

Done.
___
*[`tests/test_passive_torque.py` line 1 at r3](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJCC0u-EARTFA-_bKLK:-NJCLUTN3U8Thiy7f6dN:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4eba35a8938dc7553720bb9b9e9a875ecf54b792/tests/test_passive_torque.py#L1)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

move to the same file "test_passive_torque.py"
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 18:42 UTC, pariterre approved these changes
> Reviewed 11 of 11 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: all files reviewed, 19 unresolved discussions (waiting on @AntoineLeroy and @Ipuch)

___
*[`bioptim/dynamics/dynamics_functions.py` line 421 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzo3Z3Ya8AkjfzE91:-NJM3kPq-_mBzmEY0v98:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L421)):*
<details><summary><i>Previously, AntoineLeroy wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same
___
*[`bioptim/dynamics/dynamics_functions.py` line 510 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzp8l1UYtiUCliQ2s:-NJM3lvn0uU9PjLx1V4u:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L510)):*
<details><summary><i>Previously, AntoineLeroy wrote…</i></summary><blockquote>

Done.
</blockquote></details>

same
___
*[`bioptim/dynamics/dynamics_functions.py` line 259 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM3VF47XgkJ3yHkM5j:-NJM3VF47XgkJ3yHkM5k:b-e5afxy) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/bioptim/dynamics/dynamics_functions.py#L259)):*
> ```Python
>         tau = nlp.model.torque(tau_activations, q, qdot)
>         passive_torque = nlp.model.passive_joint_torque(q, qdot)
>         tau = tau + passive_torque if with_passive_torque else tau
> ```

put directly the nlp.model....



_Code quote:_
```Python
passive_torque
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 309 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM3fw-8227TWU6c98W:-NJM3fw-8227TWU6c98X:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/bioptim/dynamics/dynamics_functions.py#L309)):*
> ```Python
>         tau = DynamicsFunctions.get(nlp.states["tau"], states)
>         passive_torque = nlp.model.passive_joint_torque(q, qdot)
>         tau = tau + passive_torque if with_passive_torque else tau
> ```

same
___
*[`bioptim/dynamics/dynamics_functions.py` line 371 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM3iZlDcdZX8LIoSqM:-NJM3iZm3XVJIkqG9wXV:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/bioptim/dynamics/dynamics_functions.py#L371)):*
> ```Python
>         tau = DynamicsFunctions.get(tau_nlp, tau_var)
>         passive_torque = nlp.model.passive_joint_torque(q, qdot)
>         tau = tau + passive_torque if with_passive_torque else tau
> ```

same
___
*[`bioptim/dynamics/dynamics_functions.py` line 581 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM3nvw5j2w42ceRruD:-NJM3nvw5j2w42ceRruE:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/bioptim/dynamics/dynamics_functions.py#L581)):*
> ```Python
>         passive_torque = nlp.model.passive_joint_torque(q, qdot)
>         tau = muscles_tau + residual_tau if residual_tau is not None else muscles_tau
>         tau = tau + passive_torque if with_passive_torque else tau
> ```

same
___
*[`tests/test_passive_torque.py` line 44 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM4mma0eaRQZxahsf_:-NJM4mma0eaRQZxahsfa:b-tyn62p) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/tests/test_passive_torque.py#L44)):*
> ```Python
>     ],
> )
> def test_torque_driven(with_passive_torque, cx, rigidbody_dynamics):
> ```

Make sure this test does not override another one


<!-- Sent from Reviewable.io -->

2022-12-15 20:27 UTC, AntoineLeroy reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: all files reviewed, 19 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 510 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzp8l1UYtiUCliQ2s:-NJMSk91CsaZirTPnwk1:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L510)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 259 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM3VF47XgkJ3yHkM5j:-NJMSYmm47k1WeGHWd5o:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/bioptim/dynamics/dynamics_functions.py#L259)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

put directly the nlp.model....
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 309 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM3fw-8227TWU6c98W:-NJMScsu5ePZJmL5BgfT:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/bioptim/dynamics/dynamics_functions.py#L309)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 371 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM3iZlDcdZX8LIoSqM:-NJMSgJ86rZ4DHTVI3dE:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/bioptim/dynamics/dynamics_functions.py#L371)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`bioptim/dynamics/dynamics_functions.py` line 581 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM3nvw5j2w42ceRruD:-NJMSkvh-ON3RhF0LjcJ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/bioptim/dynamics/dynamics_functions.py#L581)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`tests/test_passive_torque.py` line 44 at r4](https://reviewable.io/reviews/pyomeca/bioptim/584#-NJM4mma0eaRQZxahsf_:-NJMT7nH3zXYaGIPgHss:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/68c92e4a0f54f125e52a25aa57e1d4e99eac7059/tests/test_passive_torque.py#L44)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Make sure this test does not override another one
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2022-12-15 20:27 UTC, AntoineLeroy reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: all files reviewed, 19 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/dynamics/dynamics_functions.py` line 421 at r1](https://reviewable.io/reviews/pyomeca/bioptim/584#-NImzo3Z3Ya8AkjfzE91:-NJMT9kt6MaRoHYQurna:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90cb5d98b5d8cea131897db3a259a0055a5da43/bioptim/dynamics/dynamics_functions.py#L421)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-01-17 23:59 UTC, pariterre commented
@AntoineLeroy 
Can you update to latest version? The tests should pass now that biorbd is at 1.9.9

2023-01-18 17:09 UTC, Ipuch submitted a review, later dismissed
> Reviewed 1 of 2 files at r5, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/584)* status: all files reviewed, 7 unresolved discussions (waiting on @pariterre)



<!-- Sent from Reviewable.io -->

2023-01-18 17:23 UTC, AntoineLeroy commented
@pariterre done, you can run tests

2023-01-18 20:47 UTC, pariterre commented
@Ipuch 
Do you have the button to run the tests?

2023-01-18 20:49 UTC, Ipuch commented
@pariterre no i don't. @AntoineLeroy I would suggest to open a another PR, to trigger the tests.

2023-01-19 19:43 UTC, pariterre approved these changes
LGTM

2023-01-19 21:05 UTC, merged