changes for ligaments
pyomeca/bioptim pull request #614
Opened 2023-02-10 14:42 UTC by AntoineLeroy

few changes to prepare arrival of ligaments in bioptim

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2023-02-24 21:19 UTC, pariterre requested changes
> Reviewed 6 of 6 files at r1, 3 of 3 files at r2, 1 of 3 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/614)* status: all files reviewed, 2 unresolved discussions (waiting on @AntoineLeroy)

___
*[`tests/test_ligaments.py` line 357 at r4](https://reviewable.io/reviews/pyomeca/bioptim/614#-NP4HspK-qh4FRMAsHo6:-NP4HspK-qh4FRMAsHo7:b-dk7fht) ([raw file](https://github.com/pyomeca/bioptim/blob/88e2cb6890ab4aa7fc3296c041fc746b5682fdf0/tests/test_ligaments.py#L357)):*
> ```Python
>             # initial and final position
>             np.testing.assert_almost_equal(q[:, 0], np.array([0.0]))
>             np.testing.assert_almost_equal(q[:, -1], np.array([-3.1415927]))
> ```

Why these values changed?



_Code quote:_
```Python
3.1415927])
```
___
*[`bioptim/examples/torque_driven_ocp/ocp_mass_with_ligament.py` line 72 at r4](https://reviewable.io/reviews/pyomeca/bioptim/614#-NP4H_CF0khoKZbtcklY:-NP4H_CF0khoKZbtcklZ:b-b0x9ps) ([raw file](https://github.com/pyomeca/bioptim/blob/88e2cb6890ab4aa7fc3296c041fc746b5682fdf0/bioptim/examples/torque_driven_ocp/ocp_mass_with_ligament.py#L72)):*
> ```Python
>         )
>         u_init.add([tau_init] * bio_model.nb_tau)
>     else:
> ```

please use elif for all of the case and raise a NotImplementedYet if it gets to else


<!-- Sent from Reviewable.io -->

2023-02-27 19:30 UTC, AntoineLeroy reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/614)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`tests/test_ligaments.py` line 357 at r4](https://reviewable.io/reviews/pyomeca/bioptim/614#-NP4HspK-qh4FRMAsHo6:-NPJLiEi34XVLwqDaFvM:b-eg70sv) ([raw file](https://github.com/pyomeca/bioptim/blob/88e2cb6890ab4aa7fc3296c041fc746b5682fdf0/tests/test_ligaments.py#L357)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why these values changed?
</blockquote></details>

because these are the right values for the test to pass
___
*[`bioptim/examples/torque_driven_ocp/ocp_mass_with_ligament.py` line 72 at r4](https://reviewable.io/reviews/pyomeca/bioptim/614#-NP4H_CF0khoKZbtcklY:-NPJL3oV-PY3QMHJ5VN2:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/88e2cb6890ab4aa7fc3296c041fc746b5682fdf0/bioptim/examples/torque_driven_ocp/ocp_mass_with_ligament.py#L72)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

please use elif for all of the case and raise a NotImplementedYet if it gets to else
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-02-27 20:16 UTC, AntoineLeroy reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/614)* status: all files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`tests/test_ligaments.py` line 357 at r4](https://reviewable.io/reviews/pyomeca/bioptim/614#-NP4HspK-qh4FRMAsHo6:-NPJVwGz9PuNP7YKy1mo:bpx4kno) ([raw file](https://github.com/pyomeca/bioptim/blob/88e2cb6890ab4aa7fc3296c041fc746b5682fdf0/tests/test_ligaments.py#L357)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I understand that these are the current values for the tests to pass, but why did it changed? Making the tests passing is not the goal, the goal is that it returns the right answer. I am asking, what did you change that made these values change and are we sure it is intended
</blockquote></details>

This is a test I created specifically for this PR and the change is from RigidBodyDynamics.ODE to RigidBodyDynamics.DAE_FORWARD_DYNAMICS and RigidBodyDynamics.DAE_FINVERSE_DYNAMICS. I just wanted to test the last two. 


<!-- Sent from Reviewable.io -->

2023-03-02 19:41 UTC, pariterre submitted a review, later dismissed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/614)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @AntoineLeroy)



<!-- Sent from Reviewable.io -->

2023-03-06 15:36 UTC, merged