[WIP] Add residual torque to TORQUE_ACTIVATION_DRIVEN function
pyomeca/bioptim pull request #623
Opened 2023-02-22 16:43 UTC by AnaisFarr

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [x] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2023-02-23 20:50 UTC, pariterre requested changes
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/623)* status: all files reviewed, 4 unresolved discussions (waiting on @AnaisFarr)

___
*[`bioptim/dynamics/configure_problem.py` line 1233 at r1](https://reviewable.io/reviews/pyomeca/bioptim/623#-NP--wV1-_C4k3tK5OGl:-NP--wV1-_C4k3tK5OGm:b-cstnkg) ([raw file](https://github.com/pyomeca/bioptim/blob/7e0a706cf2cbbd18d65b9daf6654676d7d065628/bioptim/dynamics/configure_problem.py#L1233)):*
> ```Python
>         name = "residual_tau"
>         name_residual_tau = ConfigureProblem._get_kinematics_based_names(nlp, name)
>         ConfigureProblem._adjust_mapping(name, ["qdot", "taudot"], nlp)  ### @pariterre???
> ```

I agree



_Code quote:_
```Python
### @pariterre???
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 270 at r1](https://reviewable.io/reviews/pyomeca/bioptim/623#-NP-07nwDeH6mwjgxIe_:-NP-07nwDeH6mwjgxIea:bwaj03b) ([raw file](https://github.com/pyomeca/bioptim/blob/7e0a706cf2cbbd18d65b9daf6654676d7d065628/bioptim/dynamics/dynamics_functions.py#L270)):*
> ```Python
>             tau_residual = DynamicsFunctions.get(nlp.controls["residual_tau"], controls)
>         tau = nlp.model.torque(tau_activation, q, qdot)
>         tau = tau + tau_residual if with_residual_torque else tau
> ```

Please add the (): 
(tau + tau_residual) if with_residual_torque else tau



_Code quote:_
```Python
tau + tau_residual if with_residual_torque else tau
```
___
*[`bioptim/dynamics/dynamics_functions.py` line 271 at r1](https://reviewable.io/reviews/pyomeca/bioptim/623#-NP-0YByBzG6gCmx4K4d:-NP-0YByBzG6gCmx4K4e:b-8ppdzi) ([raw file](https://github.com/pyomeca/bioptim/blob/7e0a706cf2cbbd18d65b9daf6654676d7d065628/bioptim/dynamics/dynamics_functions.py#L271)):*
> ```Python
>         tau = nlp.model.torque(tau_activation, q, qdot)
>         tau = tau + tau_residual if with_residual_torque else tau
>         tau = tau + nlp.model.passive_joint_torque(q, qdot) if with_passive_torque else tau
> ```

Add the () here too, just to make sure
___
*[`bioptim/examples/torque_driven_ocp/residual_torque_actuator.py` line 2 at r1](https://reviewable.io/reviews/pyomeca/bioptim/623#-NP-146Z05IOqSSFgb1i:-NP-146Z05IOqSSFgb1j:b-3oq1qf) ([raw file](https://github.com/pyomeca/bioptim/blob/7e0a706cf2cbbd18d65b9daf6654676d7d065628/bioptim/examples/torque_driven_ocp/residual_torque_actuator.py#L2)):*
> ```Python
> """
> This is an example of the use of torque actuator using a model of 2 segments and 2 degrees of freedom
> ```

torque_activation_driven.py ?


<!-- Sent from Reviewable.io -->

2023-02-23 20:50 UTC, pariterre reviewed
Please black with -l120 (and not the default -l80)

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/623#-:-NP-1fhrCr2XAt9goDvi:bb8x41q)* status: all files reviewed, 4 unresolved discussions (waiting on @AnaisFarr)



<!-- Sent from Reviewable.io -->

2023-02-24 21:23 UTC, pariterre requested changes
> Reviewed 14 of 14 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/623)* status: all files reviewed, 2 unresolved discussions (waiting on @AnaisFarr)

___
*[`bioptim/examples/torque_driven_ocp/residual_torque_actuator.py` line 2 at r1](https://reviewable.io/reviews/pyomeca/bioptim/623#-NP-146Z05IOqSSFgb1i:-NP4IW209Pv3P6TiZLSW:bvvjvnw) ([raw file](https://github.com/pyomeca/bioptim/blob/7e0a706cf2cbbd18d65b9daf6654676d7d065628/bioptim/examples/torque_driven_ocp/residual_torque_actuator.py#L2)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

torque_activation_driven.py ?
</blockquote></details>

Please change this file name
___
*[`bioptim/examples/torque_driven_ocp/residual_torque_actuator.py` line 121 at r2](https://reviewable.io/reviews/pyomeca/bioptim/623#-NP4I_DX0TtC-7lgkh3A:-NP4I_DX0TtC-7lgkh3B:bwhp2xr) ([raw file](https://github.com/pyomeca/bioptim/blob/ce887f87049614856dc39e5802dac4152c9703b4/bioptim/examples/torque_driven_ocp/residual_torque_actuator.py#L121)):*
> ```Python
>     sol.print_cost()
>     print(sol.states)
>     print(sol.controls)
> ```

Do not add these prints



_Code quote:_
```Python
    print(sol.states)
    print(sol.controls)
```


<!-- Sent from Reviewable.io -->

2023-03-02 15:38 UTC, AnaisFarr commented
Ready to merge @pariterre

2023-03-02 18:56 UTC, pariterre approved these changes
> Reviewed 5 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/623)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2023-03-02 18:56 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/623#-:-NPYfmBpAzOkpsK_IyTo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2023-03-02 18:57 UTC, merged