Sample_data_control
pyomeca/bioptim pull request #628
Opened 2023-03-01 15:23 UTC by Kev1CO

### All Submissions:

* [ ] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [ ] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [ ] Have you opened/linked the issue related to your pull request?
* [ ] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [ ] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2023-03-01 15:27 UTC, Kev1CO commented
This pull request is to allow the execution in Bioptim of Pontryagin : optimal sampled-data control

2023-03-02 00:38 UTC, Kev1CO reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: 4 of 16 files reviewed, 12 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/integrator.py` line 76 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSljUHAEwA8PXXIQ4_:-NPUaDanDGa88Al73IkA:b-wg6t90) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/dynamics/integrator.py#L76)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please use ternary operator for these trivial tests 
e.g. `self.u_sym = ode["p_scaled"] if "p_scale" in ode.keys() else []`

Also unless it makes sense to do so, prefer `None` to `[]`
</blockquote></details>

Done.
Not able to put None as the program needs a list, even empty
___
*[`bioptim/dynamics/ode_solver.py` line 128 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSm0JT5jJteyb-TWG0:-NPUbMyKAwpBRBL601BU:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/dynamics/ode_solver.py#L128)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Try to avoid "not" operator when possible in if statements, unless it avoids the else completely. It is far more easier to understand `if something is ..., then ... otherwise ...`, than to understand `if something is not ..., then ... otherwise ...`.
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 146 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSmUtDALoGzhlgYEEj:-NPUbONY4t14-xdERrRh:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/dynamics/ode_solver.py#L146)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Providing different data structure is generally bad practise as it leads to having to test if some key exists. 
A better practise is to make sure it is a valid structure, but filled with None for the non-sensical one.
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 155 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSn2fl19VCC3LfKult:-NPUcOqn5K6iurSDeRKp:b1t9kcw) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/dynamics/ode_solver.py#L155)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This elif does not oppose `if len(nlp.external_forces`in any meaningful way. both can be true and therefore your piece of code will never be run.

Also do not test for instance unless you are trying to differentiate inherited elements. Use a flag instead.
</blockquote></details>

Ode is either a function or a list of function with our case, this is the reason why we used a isinstance condition to verify our problem
not sure to understant the use of flag instead of isinstance
___
*[`bioptim/interfaces/solve_ivp_interface.py` line 350 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSnpL5-5JzNCEYEZx8:-NPUdF30Bj7E2lvEZomt:b-wg6t90) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/interfaces/solve_ivp_interface.py#L350)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

if u, instead of not u. Also, u should be a None, not an empty list. So `if u is None` is a better option
</blockquote></details>

Done.
Not able to put None as the program needs a list, even empty
___
*[`bioptim/limits/penalty.py` line 676 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSoR124pJ7spVJnwWN:-NPUehMY8eOF0ZUdWfDe:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/limits/penalty.py#L676)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Please add a raise here (just prior to that line) that raises a NotImplementedYet if `len(penalty.node_idx) > 1`
(PS I know you are not the one who wrote that piece of code)
</blockquote></details>

Done.
___
*[`bioptim/limits/penalty_option.py` line 427 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSoh744Pywcrq4j0fl:-NPUhNig9jdJMN6cereM:b-nbyw50) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/limits/penalty_option.py#L427)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Do not test for instance unless it makes sense. If you used a `None`, then test for `None`

In other word, avoid encoding the information that something means something else because it is empty. 
</blockquote></details>

Test is mendatory, cannot use none as the solver needs a list
___
*[`bioptim/optimization/optimal_control_program.py` line 513 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSpI3GBIbjEv5kg7Lg:-NPUhYk-39c7MOHM66WS:b-9jwwul) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/optimal_control_program.py#L513)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why do you need two for loops for that?
please add a comment in the second to quickly explain why 
</blockquote></details>

Forgotten modification for tests
Done.
___
*[`bioptim/optimization/optimization_variable.py` line 483 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSpU4LBtzCVcF0ybfM:-NPUj8bTA4vdSV3oiqyk:brj4vma) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/optimization_variable.py#L483)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should be `CX()` and not a list OR a `None`

Also do not test negative when there is an else 
</blockquote></details>

Can't
___
*[`bioptim/optimization/optimization_variable.py` line 491 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSpmNT8Esm7xEPrajz:-NPUj9mHB1PqDe-yIqZj:b-89z7d4) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/optimization_variable.py#L491)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should be `CX()` and not a list OR a `None`

Also do not test negative when there is an else 
</blockquote></details>

Can't
___
*[`bioptim/optimization/optimization_vector.py` line 312 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSpqKcBDupocAlM60h:-NPUjess0p1X8yP1FvYi:b17z76c) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/optimization_vector.py#L312)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Are you sure that this loop does not already do what you want? I feel that if data are empty, then the loop will just be skipped anyway (as dimensions will be 0). It seems redundant and unnecessarily complex...
</blockquote></details>

No this flag is necessary otherwise it will go trought and try to slice a empty control vector
___
*[`bioptim/optimization/solution.py` line 1017 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSqEY0CinKZo70l7C_:-NPUjx_j8JEPSHmzb0Lm:b-em1vqs) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/solution.py#L1017)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

I feel this should be a None... but maybe it causes problem
</blockquote></details>

Yes it does if not np.array([])


<!-- Sent from Reviewable.io -->

2023-03-02 20:40 UTC, pariterre requested changes
> Reviewed 3 of 12 files at r6, 3 of 9 files at r7, 5 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: 14 of 16 files reviewed, 15 unresolved discussions (waiting on @Kev1CO)

___
*[`bioptim/dynamics/integrator.py` line 73 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ0Cq7-rqx24XFNhbT:-NPZ0Cq7-rqx24XFNhbU:bf58z7) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/integrator.py#L73)):*
> ```Python
>         self.cx = ode_opt["cx"]
>         self.x_sym = ode["x_scaled"]
>         self.u_sym = ode["p_scaled"] if "p_scale" in ode.keys() else []
> ```

This should be useless



_Code quote:_
```Python
 if "p_scale" in ode.keys() else
```
___
*[`bioptim/dynamics/integrator.py` line 300 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPYzmSo8ghqKouE9XMr:-NPYzmSo8ghqKouE9XMs:b-l2h8jv) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/integrator.py#L300)):*
> ```Python
>         """
> 
>         return x_prev + h * self.fun(x_prev, self.get_u(u, t), p)  # [:, self.idx]
> ```

Why did you remove "[:, idx]"?



_Code quote:_
```Python
# [:, self.idx]
```
___
*[`bioptim/dynamics/ode_solver.py` line 128 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ0HZa8HhAYcCQiZma:-NPZ0HZa8HhAYcCQiZmb:bs93ufn) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/ode_solver.py#L128)):*
> ```Python
>             "defects_type": DefectType.NOT_APPLICABLE,
>         }
>         if nlp.controls.shape == 0:
> ```

This if should be be element, so we are sure we have the same dict



_Code quote:_
```Python
if nlp.controls.shape == 0:
```
___
*[`bioptim/dynamics/ode_solver.py` line 133 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ-B7P8rCQRMY5VXTC:-NPZ-B7P8rCQRMY5VXTD:bk7xp76) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/ode_solver.py#L133)):*
> ```Python
>                 "x_scaled": nlp.states["scaled"].cx,
>                 "p_unscaled": None,
>                 "p_scaled": None,
> ```

p_scaled: None if nlp.controls.shape == 0 else nlp.controls["scaled"]

Change to MX()



_Code quote:_
```Python
"p_scaled": None,
```
___
*[`bioptim/dynamics/ode_solver.py` line 333 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ1BrpCrcTN7sLnmOb:-NPZ1BrpCrcTN7sLnmOc:bwc3ojh) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/ode_solver.py#L333)):*
> ```Python
>             if len(nlp.external_forces) == 0:
>                 return [nlp.ode_solver.rk_integrator(ode, ode_opt)]
>             else:
> ```

No need for else (as it already returns)



_Code quote:_
```Python
else:
```


<!-- Sent from Reviewable.io -->

2023-03-02 20:40 UTC, Ipuch reviewed
> Reviewed 3 of 12 files at r6, 1 of 9 files at r7, 3 of 7 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: 15 of 16 files reviewed, 15 unresolved discussions (waiting on @Kev1CO and @pariterre)

___
*[`bioptim/dynamics/ode_solver.py` line 155 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSn2fl19VCC3LfKult:-NPZ1JZt8WM80PIHe7Gh:bfuv4xm) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/dynamics/ode_solver.py#L155)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

Ode is either a function or a list of function with our case, this is the reason why we used a isinstance condition to verify our problem
not sure to understant the use of flag instead of isinstance
</blockquote></details>

We need a more META way to treat this information. 
Instead of sending list of dynamics we need to have a MX of size n  x n_shooting nodes as we have for external forces. So there will be only one if case.
___
*[`bioptim/limits/penalty_option.py` line 427 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSoh744Pywcrq4j0fl:-NPZ1nka5LPzf0RyKatd:bgoowjz) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/limits/penalty_option.py#L427)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

Test is mendatory, cannot use none as the solver needs a list
</blockquote></details>

We need a need feature, global flag to test this:
"ControlType.NONE"
___
*[`bioptim/optimization/optimization_variable.py` line 483 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSpU4LBtzCVcF0ybfM:-NPZ24JQ89HLWhooIHCA:by4w3g1) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/optimization_variable.py#L483)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

Can't
</blockquote></details>

Let's try again together.
___
*[`bioptim/optimization/optimization_variable.py` line 491 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSpmNT8Esm7xEPrajz:-NPZ28HdD6oJ0kG_A7DC:b-1o8dph) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/optimization_variable.py#L491)):*
> Let's try again together.
___
*[`bioptim/optimization/optimization_vector.py` line 312 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSpqKcBDupocAlM60h:-NPZ2A1XBBk8k9oG5FdB:bi5a5kk) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/optimization_vector.py#L312)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

No this flag is necessary otherwise it will go trought and try to slice a empty control vector
</blockquote></details>

ControlType.NONE
___
*[`bioptim/optimization/solution.py` line 1017 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSqEY0CinKZo70l7C_:-NPZ2M-rEC65Vdt0tlI2:bi5au38) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/solution.py#L1017)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

Yes it does if not np.array([])
</blockquote></details>

ControlType.None



_Code quote:_
```Python
nlp.controls.shape == 0
```


<!-- Sent from Reviewable.io -->

2023-03-08 00:27 UTC, Kev1CO reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: 15 of 16 files reviewed, 15 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/integrator.py` line 73 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ0Cq7-rqx24XFNhbT:-NPyXTFvAgutyRy2ISS_:bs8ovy7) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/integrator.py#L73)):*
> if "p_scale" in ode.keys() else
When there is no control, there is no "p_scale" in the ode
That is why we keep it
___
*[`bioptim/dynamics/integrator.py` line 300 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPYzmSo8ghqKouE9XMr:-NPyY11V5XCsxAd-mM_b:blq42j) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/integrator.py#L300)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Why did you remove "[:, idx]"?
</blockquote></details>

Cannot remember, works well with it anyway
Done.
___
*[`bioptim/dynamics/ode_solver.py` line 128 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ0HZa8HhAYcCQiZma:-NPyakoiEKWg2-tUEioZ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/ode_solver.py#L128)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This if should be be element, so we are sure we have the same dict
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 133 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ-B7P8rCQRMY5VXTC:-NPyajLJCLfaoZ73Mt2o:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/ode_solver.py#L133)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

p_scaled: None if nlp.controls.shape == 0 else nlp.controls["scaled"]

Change to MX()
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 333 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ1BrpCrcTN7sLnmOb:-NPyb8PH8T65_3U-MROq:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/ode_solver.py#L333)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

No need for else (as it already returns)
</blockquote></details>

Done.



_Code quote:_
```Python
                dynamics_out = []
                for idx in range(len(nlp.external_forces)):
                    ode_opt["idx"] = idx
```


<!-- Sent from Reviewable.io -->

2023-03-10 20:12 UTC, Ipuch reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: 13 of 16 files reviewed, 15 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/ode_solver.py` line 155 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSn2fl19VCC3LfKult:-NQC0bxZ3SP29GUcBV59:b-4e017i) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/dynamics/ode_solver.py#L155)):*
> len(nlp.external_forces)
up


<!-- Sent from Reviewable.io -->

2023-03-16 14:28 UTC, Kev1CO reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: 10 of 17 files reviewed, 15 unresolved discussions (waiting on @Ipuch, @Kev1CO, and @pariterre)

___
*[`bioptim/optimization/optimization_vector.py` line 312 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSpqKcBDupocAlM60h:-NQenoeD5WzAkSPaAKsA:brpqcbn) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/optimization_vector.py#L312)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

ControlType.NONE
</blockquote></details>

DONE.
___
*[`bioptim/optimization/solution.py` line 1017 at r5](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPSqEY0CinKZo70l7C_:-NQeoVMc7ZQDDnjVnOHx:brpqcbn) ([raw file](https://github.com/pyomeca/bioptim/blob/4c18d35a310694db5aec189cc7d75d2cc31075d9/bioptim/optimization/solution.py#L1017)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

ControlType.None
</blockquote></details>

DONE.


<!-- Sent from Reviewable.io -->

2023-03-16 14:54 UTC, pariterre requested changes
> Reviewed 1 of 7 files at r8, 1 of 5 files at r10, 6 of 6 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: all files reviewed, 12 unresolved discussions (waiting on @Kev1CO)

___
*[`bioptim/dynamics/integrator.py` line 73 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ0Cq7-rqx24XFNhbT:-NQepRH48UjGPQQlQ899:b-nnovg5) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/integrator.py#L73)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

> if "p_scale" in ode.keys() else
When there is no control, there is no "p_scale" in the ode
That is why we keep it
</blockquote></details>

self.u_sym = [] if ode_opt["control_type"] is ControlType.NONE else ode["p_scaled"] 
___
*[`bioptim/dynamics/integrator.py` line 122 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQeqmPi3pgMjjgzpqi7:-NQeqmPi3pgMjjgzpqi8:b-s7e51i) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/dynamics/integrator.py#L122)):*
> ```Python
>             return u[:, 0] + (u[:, 1] - u[:, 0]) * dt_norm
>         elif self.control_type == ControlType.NONE:
>             return np.ndarray([])
> ```

either:
np.ndarray(0) or np.array(())



_Code quote:_
```Python
np.ndarray([])
```
___
*[`bioptim/dynamics/ode_solver.py` line 132 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQer88s9s8WInmFGBoQ:-NQer88s9s8WInmFGBoR:b7bgl55) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/dynamics/ode_solver.py#L132)):*
> ```Python
>             "x_unscaled": nlp.states.cx,
>             "x_scaled": nlp.states["scaled"].cx,
>             "p_unscaled": MX() if nlp.controls.shape == 0 else nlp.controls.cx
> ```

change this for ControlType



_Code quote:_
```Python
nlp.controls.shape
```
___
*[`bioptim/dynamics/ode_solver.py` line 135 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQerDHA5RiZrOZ7Xwdq:-NQerDHA5RiZrOZ7Xwdr:b-jt3w7b) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/dynamics/ode_solver.py#L135)):*
> ```Python
>             if nlp.control_type == ControlType.CONSTANT
>             else horzcat(nlp.controls.cx, nlp.controls.cx_end),
>             "p_scaled": MX() if nlp.controls.shape == 0 else nlp.controls["scaled"].cx
> ```

Use ControlType



_Code quote:_
```Python
nlp.controls.shape
```
___
*[`bioptim/limits/penalty.py` line 670 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQesSkA4q32huZEMKFo:-NQesSkA4q32huZEMKFp:bm6y99p) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/limits/penalty.py#L670)):*
> ```Python
>                 u = horzcat(nlp.controls.cx, nlp.controls.cx_end)
>             elif nlp.control_type == ControlType.NONE:
>                 u = []
> ```

This should be a CX...



_Code quote:_
```Python
[]
```
___
*[`bioptim/optimization/optimization_vector.py` line 453 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQetbxbDtvSKA_HMwA-:-NQetbxcAy2n2UR4c2sj:b-yxqh3l) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/optimization/optimization_vector.py#L453)):*
> ```Python
>             # For controls
>             if nlp.use_controls_from_phase_idx == nlp.phase_idx:
>                 if nlp.control_type == ControlType.CONSTANT or nlp.control_type == ControlType.NONE:
> ```

`nlp.control_type in (ControlType.CONSTANT, ControlType.NONE)`



_Code quote:_
```Python
nlp.control_type == ControlType.CONSTANT or nlp.control_type == ControlType.NONE
```
___
*[`bioptim/optimization/optimization_vector.py` line 508 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQetnyGAyRoeiILkWdc:-NQetnyGAyRoeiILkWdd:b-yxqh3l) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/optimization/optimization_vector.py#L508)):*
> ```Python
> 
>             if nlp.use_controls_from_phase_idx == nlp.phase_idx:
>                 if nlp.control_type == ControlType.CONSTANT or nlp.control_type == ControlType.NONE:
> ```

`nlp.control_type in (ControlType.CONSTANT, ControlType.NONE)`



_Code quote:_
```Python
nlp.control_type == ControlType.CONSTANT or nlp.control_type == ControlType.NONE
```
___
*[`bioptim/optimization/optimization_vector.py` line 544 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQetowGBxiJk8--rCVn:-NQetowGBxiJk8--rCVo:undefined) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/optimization/optimization_vector.py#L544)):*
> ```Python
>             # For controls
>             if nlp.use_controls_from_phase_idx == nlp.phase_idx:
>                 if nlp.control_type == ControlType.CONSTANT or nlp.control_type == ControlType.NONE:
> ```





_Suggestion:_
```Python
`nlp.control_type in (ControlType.CONSTANT, ControlType.NONE)`
```
___
*[`bioptim/optimization/solution.py` line 1276 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQeu4G16dyDCBLc2992:-NQeu4G16dyDCBLc2993:b-pi9d9n) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/optimization/solution.py#L1276)):*
> ```Python
>                         axis=1,
>                     )
>             elif nlp.control_type == ControlType.LINEAR_CONTINUOUS or nlp.control_type == ControlType.NONE:
> ```

remove this



_Code quote:_
```Python
 nlp.control_type == ControlType.LINEAR_CONTINUOUS or nlp.control_type == ControlType.NONE
```


<!-- Sent from Reviewable.io -->

2023-03-16 16:27 UTC, Kev1CO reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: all files reviewed, 12 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/integrator.py` line 73 at r8](https://reviewable.io/reviews/pyomeca/bioptim/628#-NPZ0Cq7-rqx24XFNhbT:-NQf4urg5SEG9Be_k7Cb:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/819a12c68431c6fb572cf242b70f6b97cc516a3f/bioptim/dynamics/integrator.py#L73)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

self.u_sym = [] if ode_opt["control_type"] is ControlType.NONE else ode["p_scaled"] 
</blockquote></details>

Done.
___
*[`bioptim/dynamics/integrator.py` line 122 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQeqmPi3pgMjjgzpqi7:-NQfCEHa9eMjtEp7_-oN:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/dynamics/integrator.py#L122)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

either:
np.ndarray(0) or np.array(())
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 132 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQer88s9s8WInmFGBoQ:-NQfCZxd-9rxVdAYbBmY:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/dynamics/ode_solver.py#L132)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

change this for ControlType
</blockquote></details>

Done.
___
*[`bioptim/dynamics/ode_solver.py` line 135 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQerDHA5RiZrOZ7Xwdq:-NQfCcclDCB8wSVHIWm1:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/dynamics/ode_solver.py#L135)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Use ControlType
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 453 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQetbxbDtvSKA_HMwA-:-NQfE6om1i54I7ikXmzv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/optimization/optimization_vector.py#L453)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`nlp.control_type in (ControlType.CONSTANT, ControlType.NONE)`
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 508 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQetnyGAyRoeiILkWdc:-NQfE7E97dARjs15ZpNE:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/optimization/optimization_vector.py#L508)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`nlp.control_type in (ControlType.CONSTANT, ControlType.NONE)`
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 544 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQetowGBxiJk8--rCVn:-NQfE8FZ0B9G7ryE5ily:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/optimization/optimization_vector.py#L544)):*
> ```Python
>             # For controls
>             if nlp.use_controls_from_phase_idx == nlp.phase_idx:
>                 if nlp.control_type == ControlType.CONSTANT or nlp.control_type == ControlType.NONE:
> ```

Done.
___
*[`bioptim/optimization/solution.py` line 1276 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQeu4G16dyDCBLc2992:-NQfEdtXAR4vsvj6ojC0:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/optimization/solution.py#L1276)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

remove this
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-17 19:11 UTC, Ipuch requested changes
> Reviewed 2 of 4 files at r12, 1 of 2 files at r13, 1 of 5 files at r14, 6 of 6 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: all files reviewed, 15 unresolved discussions (waiting on @Kev1CO and @pariterre)

___
*[`bioptim/dynamics/ode_solver.py` line 135 at r11](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQerDHA5RiZrOZ7Xwdq:-NQkwxIN9H7BNXiZM638:b-wyczd5) ([raw file](https://github.com/pyomeca/bioptim/blob/92d15e5ade4149ceb157e6f711971570baff9b03/bioptim/dynamics/ode_solver.py#L135)):*
<details><summary><i>Previously, Kev1CO wrote…</i></summary><blockquote>

Done.
</blockquote></details>


nlp.controls.cx if nlp.control_type in (ControlType.CONSTANT, ...)  else ...
___
*[`bioptim/dynamics/ode_solver.py` line 135 at r15](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQkwlj-3Ppw_5FY_cGD:-NQkwlj-3Ppw_5FY_cGE:b-9r2obt) ([raw file](https://github.com/pyomeca/bioptim/blob/c90a4f04ab046285aa33f17465036b60f0bc4f49/bioptim/dynamics/ode_solver.py#L135)):*
> ```Python
>             if nlp.control_type == ControlType.NONE
>             else nlp.controls.cx
>             if nlp.control_type == ControlType.CONSTANT
> ```

nlp.controls.cx if nlp.control_type in (ControlType.CONSTANT, ...)  else ...
___
*[`bioptim/optimization/optimization_variable.py` line 602 at r15](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQkxsty3hAqMwpasVlI:-NQkxsty3hAqMwpasVlJ:bol902l) ([raw file](https://github.com/pyomeca/bioptim/blob/c90a4f04ab046285aa33f17465036b60f0bc4f49/bioptim/optimization/optimization_variable.py#L602)):*
> ```Python
>     def _set_casadi_symbolic_callable(self, casadi_symbolic_callable: Callable = None):
>         if casadi_symbolic_callable is None:
>             raise ValueError()
> ```

if casadi_symbolic_callable is None and not isinstance(..., Callable):

"This entry should be either casadi.MX or casadi.SX"
___
*[`bioptim/optimization/optimization_vector.py` line 312 at r15](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQkyPvAAnrJWQ0NCUYZ:-NQkyPvAAnrJWQ0NCUY_:bm6wlhj) ([raw file](https://github.com/pyomeca/bioptim/blob/c90a4f04ab046285aa33f17465036b60f0bc4f49/bioptim/optimization/optimization_vector.py#L312)):*
> ```Python
>         p_idx = 0
> 
>         if self.ocp.nlp[0].control_type != ControlType.NONE:
> ```

self.ocp.nlp[0].control_type in (CONSTANT and LINEAR_CONTINUOUS...)



_Code quote:_
```Python
self.ocp.nlp[0].control_type
```


<!-- Sent from Reviewable.io -->

2023-03-17 19:52 UTC, Kev1CO reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: 19 of 20 files reviewed, 15 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/optimization/optimization_variable.py` line 602 at r15](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQkxsty3hAqMwpasVlI:-NQl3Y5eCOFSNwMV-5L8:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90a4f04ab046285aa33f17465036b60f0bc4f49/bioptim/optimization/optimization_variable.py#L602)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

if casadi_symbolic_callable is None and not isinstance(..., Callable):

"This entry should be either casadi.MX or casadi.SX"
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_vector.py` line 312 at r15](https://reviewable.io/reviews/pyomeca/bioptim/628#-NQkyPvAAnrJWQ0NCUYZ:-NQl3xQjEpjY7q58Xdp-:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/c90a4f04ab046285aa33f17465036b60f0bc4f49/bioptim/optimization/optimization_vector.py#L312)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

self.ocp.nlp[0].control_type in (CONSTANT and LINEAR_CONTINUOUS...)
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-23 20:03 UTC, pariterre requested changes
> Reviewed 3 of 4 files at r17, 7 of 7 files at r18, 1 of 1 files at r19, 2 of 2 files at r20, 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: all files reviewed, 10 unresolved discussions (waiting on @Ipuch and @Kev1CO)

___
*[`bioptim/optimization/optimization_variable.py` line 3 at r20](https://reviewable.io/reviews/pyomeca/bioptim/628#-NRF277r0I_95TFjdFGM:-NRF277s3OXev7YSME54:b-eznd2n) ([raw file](https://github.com/pyomeca/bioptim/blob/da6db12ff0c227870fd4a32151f2322ba7a1f5d0/bioptim/optimization/optimization_variable.py#L3)):*
> ```Python
> import numpy as np
> from casadi import MX, SX, vertcat
> from typing import Callable
> ```

Typing is a built-in package. It should therefore appear first followed by a white space



_Code quote:_
```Python
from typing import Callable
```
___
*[`bioptim/optimization/optimization_variable.py` line 324 at r20](https://reviewable.io/reviews/pyomeca/bioptim/628#-NRF2XTf48mLoOGEZ8la:-NRF2XTf48mLoOGEZ8lb:b8wlwpm) ([raw file](https://github.com/pyomeca/bioptim/blob/da6db12ff0c227870fd4a32151f2322ba7a1f5d0/bioptim/optimization/optimization_variable.py#L324)):*
> ```Python
>     mx_reduced: MX
>         The reduced MX to the size of _cx
>     _casadi_symbolic_callable: Callable
> ```

change the name to `cx_constructor`



_Code quote:_
```Python
_casadi_symbolic_callable
```
___
*[`bioptim/optimization/optimization_variable.py` line 578 at r20](https://reviewable.io/reviews/pyomeca/bioptim/628#-NRF2zqM9t85rup9fBWB:-NRF2zqM9t85rup9fBWC:b-437v6t) ([raw file](https://github.com/pyomeca/bioptim/blob/da6db12ff0c227870fd4a32151f2322ba7a1f5d0/bioptim/optimization/optimization_variable.py#L578)):*
> ```Python
> 
> class OptimizationVariableContainer:
>     def __init__(self, variable_scaled=None, variables_unscaled=None, casadi_symbolic_callable: Callable = None):
> ```

Update this name



_Code quote:_
```Python
casadi_symbolic_callable
```


<!-- Sent from Reviewable.io -->

2023-03-23 20:04 UTC, Ipuch submitted a review, later dismissed
> Reviewed 2 of 4 files at r17, 7 of 7 files at r18, 1 of 1 files at r19, 2 of 2 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: all files reviewed, 7 unresolved discussions (waiting on @Kev1CO and @pariterre)



<!-- Sent from Reviewable.io -->

2023-03-24 02:36 UTC, Kev1CO reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628)* status: 17 of 20 files reviewed, 7 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/optimization/optimization_variable.py` line 3 at r20](https://reviewable.io/reviews/pyomeca/bioptim/628#-NRF277r0I_95TFjdFGM:-NRGSoPf9-IvNcV4BlyX:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/da6db12ff0c227870fd4a32151f2322ba7a1f5d0/bioptim/optimization/optimization_variable.py#L3)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Typing is a built-in package. It should therefore appear first followed by a white space
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_variable.py` line 324 at r20](https://reviewable.io/reviews/pyomeca/bioptim/628#-NRF2XTf48mLoOGEZ8la:-NRGSLnM30NE3os_P6D5:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/da6db12ff0c227870fd4a32151f2322ba7a1f5d0/bioptim/optimization/optimization_variable.py#L324)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

change the name to `cx_constructor`
</blockquote></details>

Done.
___
*[`bioptim/optimization/optimization_variable.py` line 578 at r20](https://reviewable.io/reviews/pyomeca/bioptim/628#-NRF2zqM9t85rup9fBWB:-NRGSM3D3n6a5EEqhjqm:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/da6db12ff0c227870fd4a32151f2322ba7a1f5d0/bioptim/optimization/optimization_variable.py#L578)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Update this name
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-03-24 16:17 UTC, Kev1CO commented
@pariterre RTM

2023-03-30 19:22 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 3 files at r22, 1 of 1 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/628#-:-NRnyD9h4MWGpWwtLBI8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Kev1CO)



<!-- Sent from Reviewable.io -->

2023-03-30 19:23 UTC, merged