[WIP] BiorrbdModelHolonomic and VariationalBiorbdModel in core
pyomeca/bioptim pull request #699
Opened 2023-06-19 16:19 UTC by 20chupin

2023-06-19 20:58 UTC, Ipuch requested changes
> Reviewed 8 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 8 of 11 files reviewed, 31 unresolved discussions (waiting on @20chupin)

___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 30 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKEbS44q06R43Q2Ro1:-NYKEbS44q06R43Q2Ro2:b-jlhpby) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L30)):*
> ```Python
>         bio_model: VariationalBiorbdModel,
>         n_shooting: int,
>         final_time: float,
> ```

I feel that n_shooting and final_time should be in kwarg too ?
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 57 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKEtLW5cpu6v1sGVHc:-NYKEtLW5cpu6v1sGVHd:bcz9qvp) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L57)):*
> ```Python
> 
>         q_sym = MX.sym("q", (n_q, 1))
>         if bio_model.nb_holonomic_constraints:
> ```

This should not be necessary, as discussed earlier.
bio_model.holonomic_constraints(...) already throw MX type values.
___
*[`bioptim/interfaces/biomodel.py` line 532 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKFZMA27q4zNEsp_NP:-NYKFZMA27q4zNEsp_NQ:bm7jwvt) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L532)):*
> ```Python
>         Compute the coupling matrix, denoted Bvu in the paper :
> 
>         Docquier, N., Poncelet, A., and Fisette, P.:
> ```

The source can be put next to the actual code of the implementation.
___
*[`bioptim/interfaces/biomodel.py` line 542 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKFfns4SzM3d9_NckN:-NYKFfns4SzM3d9_NckO:bb73xfv) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L542)):*
> ```Python
>         Compute the biais vector, denoted b in the paper :
> 
>         Docquier, N., Poncelet, A., and Fisette, P.:
> ```

Same
___
*[`bioptim/interfaces/biomodel.py` line 586 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKH6Nc8Xisu_a6XSiL:-NYKH6Nc8Xisu_a6XSiM:bf61ths) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L586)):*
> ```Python
>         """
> 
>     def compute_v_from_u_numeric(self, u: DM, v_init=None) -> DM:
> ```

We may find a better way to do this. numeric vs symbolic should be handled in a better way. Not sure yet how
___
*[`bioptim/interfaces/biomodel.py` line 607 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKG1kgExE9w4IsDs29:-NYKG1khBNXVbOfpmcEp:bdendmq) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L607)):*
> ```Python
>         """
> 
>     def partitioned_forward_dynamics(self, u, udot, tau, external_forces=None, f_contacts=None) -> MX:
> ```

Delete this function and use its name to replace "forward_dynamics_constrained_independent".
___
*[`bioptim/interfaces/biomodel.py` line 610 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKFqJPEIkCVnCInRQl:-NYKFqJQE6QLILT1EiAE:bih51be) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L610)):*
> ```Python
>         """not used"""
> 
>     def dae_inverse_dynamics(
> ```

Delete this, I'm not sure what I've done...
___
*[`bioptim/interfaces/biomodel.py` line 672 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKGJjb6-PxxdWBb5I0:-NYKGJjb6-PxxdWBb5I1:b84zrfs) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L672)):*
> ```Python
>         ----------
>         The term associated to the controls in the Lagrangian equations.
>         Johnson, E. R., & Murphey, T. D. (2009).
> ```

Returns
----------
The term associated with the controls in the Lagrangian equations.

Source
----------
Johnson, E. R., & Murphey, T. D. (2009).
Scalable Variational Integrators for Constrained Mechanical Systems in Generalized Coordinates.
IEEE Transactions on Robotics, 25(6), 1249–1261. doi:10.1109/tro.2009.2032955
___
*[`bioptim/interfaces/biomodel.py` line 738 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKGm2Z41e9dA7ezDTT:-NYKGm2_0So3TsdDP7t5:ba7br0e) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L738)):*
> ```Python
>             The jacobian of the constraints.
>         lambdas: MX | SX
>             The Lagrange multipliers.
> ```

Returns
___
*[`bioptim/interfaces/biomodel.py` line 757 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKGqqg08E_BGH4rm_R:-NYKGqqg08E_BGH4rm_S:b-rqint6) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L757)):*
> ```Python
>         The following equation as been calculated thanks to the paper "Discrete mechanics and optimal control for
>         constrained systems" (https://onlinelibrary.wiley.com/doi/epdf/10.1002/oca.912), equations (14) and the
>         indications given just before the equation (18) for p0 and pN.
> ```

Parameters
-----

Returns
----

Source
------
___
*[`bioptim/interfaces/biomodel.py` line 772 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKGwJbEzNSBi3sj7e-:-NYKGwJc6ULtShhyVWy1:b-rqint6) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L772)):*
> ```Python
>         lambdasN: MX | SX = None,
>     ):
>         """
> ```

Parameters
-----

Returns
----

Source
------
___
*[`bioptim/interfaces/biorbd_model.py` line 526 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKHPGb6E4Byk8tNzmv:-NYKHPGb6E4Byk8tNzmw:beqocqa) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biorbd_model.py#L526)):*
> ```Python
> 
>     def lagrangian(self, q: MX | SX, qdot: MX | SX) -> MX | SX:
>         return self.model.KineticEnergy(q, qdot).to_mx() - self.model.PotentialEnergy(q).to_mx()
> ```

self.model.Lagrangrian(q,qdot).to_mx()  ? :dancer: 
___
*[`bioptim/interfaces/biorbd_model.py` line 529 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKH_Or2Jy155tzy4pI:-NYKH_Or2Jy155tzy4pJ:bpgvayt) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biorbd_model.py#L529)):*
> ```Python
> 
>     def set_dependencies(self, dependent_joint_index: list, independent_joint_index: list):
>         raise NotImplementedError("This function is not implemented for BiorbdModel use BiorbdModelHolonomic instead.")
> ```

"This function is not implemented for BiorbdModel. Please consider using BiorbdModelHolonomic if you model holonomic constraints."
___
*[`bioptim/interfaces/biorbd_model.py` line 533 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKHl5t7pqkjEPHk2aM:-NYKHl5t7pqkjEPHk2aN:bpgvayt) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biorbd_model.py#L533)):*
> ```Python
>     @property
>     def nb_independent_joints(self):
>         raise NotImplementedError("This function is not implemented for BiorbdModel use BiorbdModelHolonomic instead.")
> ```

"This function is not implemented for BiorbdModel. Please consider using BiorbdModelHolonomic if you model holonomic constraints."
___
*[`bioptim/interfaces/biorbd_model.py` line 537 at r1](https://reviewable.io [...]

2023-06-20 14:47 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 8 of 11 files reviewed, 31 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 30 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKEbS44q06R43Q2Ro1:-NYO4kG36NNhcnvWqX1W:b-nmrv23) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L30)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

I feel that n_shooting and final_time should be in kwarg too ?
</blockquote></details>

I'd say that no because they are mandatory...
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 57 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKEtLW5cpu6v1sGVHc:-NYO5eIk6v1ybgQMcAST:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L57)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

This should not be necessary, as discussed earlier.
bio_model.holonomic_constraints(...) already throw MX type values.
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 532 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKFZMA27q4zNEsp_NP:-NYO7UnjDr_Y9Chax2tG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L532)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

The source can be put next to the actual code of the implementation.
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 542 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKFfns4SzM3d9_NckN:-NYO7bxF9Hd51WRPw39W:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L542)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Same
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 607 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKG1kgExE9w4IsDs29:-NYO8l7wB89BHc3L6_LY:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L607)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Delete this function and use its name to replace "forward_dynamics_constrained_independent".
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 610 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKFqJPEIkCVnCInRQl:-NYO639bEvHlwC7eSB_P:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L610)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Delete this, I'm not sure what I've done...
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 672 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKGJjb6-PxxdWBb5I0:-NYO6Ggj7wsK5dcgKvsM:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L672)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Returns
----------
The term associated with the controls in the Lagrangian equations.

Source
----------
Johnson, E. R., & Murphey, T. D. (2009).
Scalable Variational Integrators for Constrained Mechanical Systems in Generalized Coordinates.
IEEE Transactions on Robotics, 25(6), 1249–1261. doi:10.1109/tro.2009.2032955


</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 738 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKGm2Z41e9dA7ezDTT:-NYO9inl24RH_o_xxliZ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L738)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Returns
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 757 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKGqqg08E_BGH4rm_R:-NYOAM0W-IV4Uh3hlBXW:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L757)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Parameters
-----

Returns
----

Source
------
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel.py` line 772 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKGwJbEzNSBi3sj7e-:-NYOBGs196vZmB-OZDaS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L772)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Parameters
-----

Returns
----

Source
------
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biorbd_model.py` line 526 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKHPGb6E4Byk8tNzmv:-NYOBWtD-JgrMbnlcc-K:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biorbd_model.py#L526)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

self.model.Lagrangrian(q,qdot).to_mx()  ? :dancer: 
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biorbd_model.py` line 529 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKH_Or2Jy155tzy4pI:-NYOBjA0B5K3GDfMD2hF:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biorbd_model.py#L529)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"This function is not implemented for BiorbdModel. Please consider using BiorbdModelHolonomic if you model holonomic constraints."
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biorbd_model.py` line 533 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKHl5t7pqkjEPHk2aM:-NYOBk7sDxRQH-fkotHr:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biorbd_model.py#L533)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"This function is not implemented for BiorbdModel. Please consider using BiorbdModelHolonomic if you model holonomic constraints."
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biorbd_model.py` line 537 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKHlmJ1CGIstFNAb16:-NYOBo419Fbdu2vB9tqU:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biorbd_model.py#L537)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"This function is not implemented for BiorbdModel. Please consider using BiorbdModelHolonomic if you model holonomic constraints."
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biorbd_model.py` line 545 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKHmdk7V6IQuv-Vm0D:-NYOCNgz-nqRuZo4qyv3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biorbd_model.py#L545)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"This function is not implemented for BiorbdModel. Please consider using BiorbdModelHolonomic if you model holonomic constraint [...]

2023-06-21 19:01 UTC, Ipuch requested changes
> Reviewed 1 of 11 files at r1, 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 4 unresolved discussions (waiting on @20chupin)

___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 62 at r2](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYUJH3Q3CltUf-4AVmS:-NYUJH3Q3CltUf-4AVmT:b-b7drm0) ([raw file](https://github.com/pyomeca/bioptim/blob/f5a12c4b1e3dd3f2fc613be66acff41af90b23f1/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L62)):*
> ```Python
>             self.holonomic_constraints = None
>             self.holonomic_constraints_jacobian = None
>         self.has_holonomic_constraints = self.holonomic_constraints is not None
> ```

use this attribute before, once set.
and remove the if bio_model.nb_holonomics_constraints:


<!-- Sent from Reviewable.io -->

2023-06-21 19:02 UTC, Ipuch reviewed
Try to add the examples with the BiorbdModelCustomHolonomic. (y)

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699#-:-NYUKPu5-EjILByXxZXu:blajkt)* status: all files reviewed, 4 unresolved discussions (waiting on @20chupin)



<!-- Sent from Reviewable.io -->

2023-06-21 19:43 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 62 at r2](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYUJH3Q3CltUf-4AVmS:-NYURFUL1xhsHYVHSlnc:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/f5a12c4b1e3dd3f2fc613be66acff41af90b23f1/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L62)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

use this attribute before, once set.
and remove the if bio_model.nb_holonomics_constraints:
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-21 19:48 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 10 of 11 files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/interfaces/biomodel.py` line 586 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKH6Nc8Xisu_a6XSiL:-NYUUyUcBYoUXNov3rns:brc8vpr) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/interfaces/biomodel.py#L586)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

We may find a better way to do this. numeric vs symbolic should be handled in a better way. Not sure yet how
</blockquote></details>

I copied that from your script, do you want me to look into it ?
___
*[`bioptim/misc/enums.py` line 160 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKJrroDGjCR33PpVrW:-NYUU8I7CAQOgO9U5Zv0:b-xjn27t) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/misc/enums.py#L160)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

We need to evaluate if we can evaluate merge this two enums.

```python3
class QuadratureRule(Enum):
     DEFAULT = "default"
    RECTANGLE_LEFT_APPROXIMATION = "rectangle left approximation"  # equivalent to RECTANGLE
    RECTANGLE_RIGHT_APPROXIMATION = "..."
    MIDPOINT = "midpoint"
    TRAPEZOIDAL = "trapezoidal"  # fake trapezoidal currently in bioptim because we pick the end node of the interval instead of the first node of the next.
# change to APPROXIMATIVE_TRAPEZOIDAL = "approximative trapezoidal"
    TRUE_TRAPEZOIDAL = "true_trapezoidal"  #  This would be trapezoidal
# change to  TRAPEZOIDAL = "trapezoidal" ?
```

</blockquote></details>

Is default midpoint ?, if yes, we could just add `RIGHT_APPROXIMATION`


<!-- Sent from Reviewable.io -->

2023-06-22 15:09 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 7 of 13 files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 30 at r1](https://reviewable.io/reviews/pyomeca/bioptim/699#-NYKEbS44q06R43Q2Ro1:-NYYdl18-1RDzesebzf4:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ea5c8f77ffddbf93d695aa1207ed82192b273113/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L30)):*
<details><summary><i>Previously, 20chupin wrote…</i></summary><blockquote>

I'd say that no because they are mandatory...
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-29 14:53 UTC, Ipuch requested changes
> Reviewed 6 of 19 files at r6, 4 of 8 files at r7, 12 of 12 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 59 unresolved discussions (waiting on @20chupin)

___
*[`bioptim/__init__.py` line 205 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6HGT-BQlqVX9Juo8x:-NZ6HGT-BQlqVX9Juo8y:b-x9pnpg) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/__init__.py#L205)):*
> ```Python
>     MagnitudeType,
>     MultiCyclicCycleSolutions,
>     QuadratureRule,
> ```

To disappear?
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/holonomic_constraints.py` line 9 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Horm-AqOxaoBE6Pc:-NZ6Horm-AqOxaoBE6Pd:bqyrenc) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/holonomic_constraints.py#L9)):*
> ```Python
> 
> 
> class HolonomicConstraintFcn:
> ```

Do we need to put this in the core too ?
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 47 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6I9uF-VUDHiXbx2Ai:-NZ6I9uF-VUDHiXbx2Aj:b2sp2z8) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L47)):*
> ```Python
>     ):
>         if type(bio_model) != VariationalBiorbdModel:
>             raise RuntimeError("bio_model must be of type VariationalBiorbdModel")
> ```

ValueError or TypeError ?
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 51 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6IL257-V7rLUdu4Yk:-NZ6IL257-V7rLUdu4Yl:bkmvbqu) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L51)):*
> ```Python
>         if "phase_time" in kwargs or isinstance(final_time, (list, tuple)):
>             raise NotImplementedError(
>                 "Phases have not been implemented in VariationalOptimalControlProgram yet. Please register only a final"
> ```

"Multiphase problems have not been implemented yet with VariationalOptimalControlProgram. 
Please use final_time argument and use one float to define it."

Test if np.array of shape [n]. test the number of elements.
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 73 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6d3qcBryLzuucjkHk:-NZ6d3qcBryLzuucjkHl:b-s3d2q9) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L73)):*
> ```Python
>         n_qdot = n_q = self.bio_model.nb_q
> 
>         self.has_holonomic_constraints = self.bio_model.nb_holonomic_constraints > 0
> ```

as @property method in BiorbdModelHolonomic
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 75 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6J_W99s85Tl0OXFWT:-NZ6J_W99s85Tl0OXFWU:b-g8xgqs) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L75)):*
> ```Python
>         self.has_holonomic_constraints = self.bio_model.nb_holonomic_constraints > 0
>         if self.has_holonomic_constraints:
>             self.holonomic_constraints = self.bio_model.holonomic_constraints
> ```

one line :)
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 286 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Zd3P-cEjwVUhBhsJ:-NZ6Zd3P-cEjwVUhBhsK:bzb4g7b) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L286)):*
> ```Python
>                     control_cur,
>                     control_next,
>                     self.holonomic_constraints,
> ```

remove this argument ?
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 23 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Jrte4uMza9E7RjmQ:-NZ6Jrte4uMza9E7RjmR:b-c2e48a) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L23)):*
> ```Python
> from bioptim.examples.discrete_mechanics_and_optimal_control.holonomic_constraints import HolonomicConstraintFcn
> 
> from bioptim.examples.holonomic_constraints.two_pendulums import custom_configure, custom_dynamic
> ```

We may displace them in the core too.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 64 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6KlIIEg7pkdLObvbH:-NZ6KlIIEg7pkdLObvbI:bw4uaz7) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L64)):*
> ```Python
>         constraint_double_derivative=constraint_double_derivative,
>     )
>     bio_model.set_dependencies(independent_joint_index=[0, 1, 4], dependent_joint_index=[2, 3])
> ```

Add comments since this a tutorial example.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 73 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6K5stEIGCbJYrFrGG:-NZ6K5stEIGCbJYrFrGH:bep2cc8) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L73)):*
> ```Python
>     # Dynamics
>     dynamics = DynamicsList()
>     dynamics.add(custom_configure, dynamic_function=custom_dynamic, expand=False)
> ```

HOLONOMIC\_TORQUE\_DRIVEN = (ConfigureProblem.holonomic\_torque\_driven,) in the core of bioptim.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 80 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6KrYHAVVaTl3kLx-Y:-NZ6KrYHAVVaTl3kLx-Z:b6ilbkn) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L80)):*
> ```Python
>     # Boundaries
>     mapping = BiMappingList()
>     mapping.add("q", to_second=[0, 1, None, None, 2], to_first=[0, 1, 4])
> ```

comment this too :)
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 83 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6KyzcEgXBGObxnwD6:-NZ6KyzcEgXBGObxnwD7:b9iigui) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L83)):*
> ```Python
>     mapping.add("qdot", to_second=[0, 1, None, None, 2], to_first=[0, 1, 4])
>     x_bounds = BoundsList()
>     x_bounds["u"] = bio_model.bounds_from_ranges("q", mapping=mapping)
> ```

"to q_u and qdot_u"
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 133 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6LdVEA9knkA4-u578:-NZ6LdVEA9knkA4-u579:b-i9wq25) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L133)):*
> ```Python
>     )
> 
>     ocp.add_plot_penalty(cost_type=CostType.ALL)
> ```

plots are working ? if not remove this line.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 137 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Lrff40Jx5k8KuduG:-NZ6Lrff40Jx5k8KuduH:b-l6mwxj) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/biopti [...]

2023-06-29 15:01 UTC, Ipuch commented
[ ] VariationalBiorbdModel instead of BiorbdModelVariational
[ ] Documentation in README.md new models, new ocp.

2023-06-29 19:05 UTC, 20chupin commented
>     * [x]  VariationalBiorbdModel instead of BiorbdModelVariational
> 
>     * [ ]  Documentation in README.md new models, new ocp.
> 
>     * [x]  Bvu
> 
>     * [x]  Jv
> 
>     * [x]  partionned_constrained_jacobian, enhance me this.

2023-06-29 19:22 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 9 of 25 files reviewed, 59 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 73 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6d3qcBryLzuucjkHk:-NZ7Y4wP5dmuZjY44jBc:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L73)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

as @property method in BiorbdModelHolonomic
</blockquote></details>

Done.
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 75 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6J_W99s85Tl0OXFWT:-NZ7YEg84JXiXO3GyoQG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L75)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

one line :)
</blockquote></details>

Done.
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 286 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Zd3P-cEjwVUhBhsJ:-NZ7YGtx6tflD9Ii3w7e:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L286)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove this argument ?
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 137 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Lrff40Jx5k8KuduG:-NZ7Yh7a7N_TJE8sKwb2:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L137)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 138 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Ltnl8ZHd0N4GKr2d:-NZ7YhaQ3TJMklxAhZGX:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L138)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

that's why it may be too long remove this line.
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 141 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6La1BETYUlzrmZhLC:-NZ7Ykfc-zpTX0drBrrc:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L141)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

101 but 10 shooting resolve
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 147 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6OfDc3QJ0HS3G_d-X:-NZ7YyLS1ydOBAxqHdQ2:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L147)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

At the top of the script
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 8 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6PFaX2TVt4iPEO05R:-NZ7ZHa43_iTn_DCoWP8:b-n5e6av) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L8)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

remove SX
</blockquote></details>

I removed use_sx
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 76 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6OsDT4iJ6RRnfjJ44:-NZ7_o_6DPfkoqjtwdVq:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L76)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

take index of indepedant dof.
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 82 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6P-7QBF_CLK1-693S:-NZ7_sALBbueqZaGYRQG:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L82)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 94 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6P6wnEUmnjCoTC21R:-NZ7_tA_CeAhHxa4dVxc:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L94)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Then remove it
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 142 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6PJ8UDlHO3DrFT1IY:-NZ7_volA47Zlx1TJ8qq:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L142)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

q_u
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 147 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6PRHp7DDuJ8WeS8yg:-NZ7a2PN4xOP9W6Aw58R:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L147)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

directly but the values into x_init and x_bounds
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 200 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Q-BoC1IsZuqq_3Uz:-NZ7a3Ve-QyqzBbxllzl:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L200)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

101?
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 206 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Q5T0ASGoVKmVjiSR:-NZ7a4AQ0eV0N_Ij65A9:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L206)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

on top
</blockquote></details>

Done.
___
*[`bioptim/interfaces/variational_biomodel.py` line 40 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6XY011K-hZhxYU3HR:-NZ7HZ_-92A9_dsypEAP:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/interfaces/variational_biomodel.py#L40)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

should be an attr [...]

2023-06-29 20:10 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 9 of 25 files reviewed, 59 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/holonomic_constraints.py` line 9 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Horm-AqOxaoBE6Pc:-NZ7eH2v0Gh94kmB8SZ3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/holonomic_constraints.py#L9)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Do we need to put this in the core too ?
</blockquote></details>

Done.
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 47 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6I9uF-VUDHiXbx2Ai:-NZ7eR-PCk0emgLW2VCw:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L47)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

ValueError or TypeError ?
</blockquote></details>

Done.
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py` line 51 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6IL257-V7rLUdu4Yk:-NZ7fmSY2U3aXX77vGLv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/discrete_mechanics_and_optimal_control/variational_optimal_control_program.py#L51)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"Multiphase problems have not been implemented yet with VariationalOptimalControlProgram. 
Please use final_time argument and use one float to define it."

Test if np.array of shape [n]. test the number of elements.
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 23 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6Jrte4uMza9E7RjmQ:-NZ7iwVbEPh93KFJDNlm:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L23)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

We may displace them in the core too.
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 73 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6K5stEIGCbJYrFrGG:-NZ7ivGb3OOLKou2B58A:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L73)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

HOLONOMIC\_TORQUE\_DRIVEN = (ConfigureProblem.holonomic\_torque\_driven,) in the core of bioptim.
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 30 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6OkzU0VjruoTVthvY:-NZ7j-Oe3BFbchA5hePE:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L30)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Move into core.
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 33 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6PDtnCHjd1Ql3WQn_:-NZ7j0uB5tSklu14F6le:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L33)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Then remove it
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 63 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6OmsyARknJgE3DtAy:-NZ7j3zE5PPuKiQDP6pn:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L63)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Move into core
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-06-29 20:36 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 6 of 27 files reviewed, 59 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 64 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6KlIIEg7pkdLObvbH:-NZ7msJm7YEe7w1lvDec:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L64)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Add comments since this a tutorial example.
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 80 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6KrYHAVVaTl3kLx-Y:-NZ7n5Rs1lP5P4X5h5c3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L80)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

comment this too :)
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 83 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6KyzcEgXBGObxnwD6:-NZ7n6G55x9sW3ygemR4:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L83)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

"to q_u and qdot_u"
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/three_bars.py` line 133 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6LdVEA9knkA4-u578:-NZ7o6QfByzdfIJdACFh:bdvcio4) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/three_bars.py#L133)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

plots are working ? if not remove this line.
</blockquote></details>

Plots are not working for now
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 160 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6PmqU0QwE1aajBZsF:-NZ7omZv2PqtX_aanUej:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/examples/holonomic_constraints/two_pendulums.py#L160)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

add a comment on why we use mapping here.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-04 19:57 UTC, 20chupin reviewed
I did all of these but I can't manage to tick the boxes

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699#-:-NZXTKyj4Fe5MEKSs8KP:bbonc7o)* status: 0 of 36 files reviewed, 59 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/__init__.py` line 205 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6HGT-BQlqVX9Juo8x:-NZ7t92W6IGFtd_H9jBI:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/__init__.py#L205)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

To disappear?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 16:28 UTC, Ipuch requested changes
> Reviewed 1 of 13 files at r11, 6 of 35 files at r13, 15 of 26 files at r14, 13 of 13 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 18 unresolved discussions (waiting on @20chupin)

___
*[`README.md` line 749 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZak7OF5exI1eqpuAcK:-NZak7OG6Gr1EAgzAkIm:b-8mortk) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/README.md#L749)):*
> ```Markdown
> ### Class: HolonomicBiorbdModel
> The `HolonomicBiorbdModel` class is implementing a BioModel of the biorbd dynamics library. Since the class inherits
> from `BiorbdModel`, all the methods of `BiorbdModel` are available.You can define the
> ```

. You
___
*[`README.md` line 760 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZakNUMC5f5lhKzpdXL:-NZakNUMC5f5lhKzpdXM:b-bfj54l) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/README.md#L760)):*
> ```Markdown
> bio_model.add_holonomic_constraint(constraint, constraint_jacobian, constraint_double_derivative)
> ```
> ```

Two dynamics are implemented in the Differential algebraic equations handling constraints at acceleration-level in forward_dynamics_constrained(...)
And the other was inspired by [robotran]() which uses index reduction methods to satisfy the constraints.
forward_dynamics_partitionned(...)
___
*[`README.md` line 953 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZalLl37LfwaJSltjm8:-NZalLl47uS0PrHWWOQN:bjzljho) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/README.md#L953)):*
> ```Markdown
> ##### with_ligament = True
> The tau generated by the ligament is taken into account in the *tau* 
> ```

add holonomicDynamics
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 154 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZasUa_4VXITLQ74SiC:-NZasUa_4VXITLQ74SiD:bq8xz05) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/examples/holonomic_constraints/two_pendulums.py#L154)):*
> ```Python
>     # constraint, so we need to map the states and controls to only compute the dynamics of the independent joints
>     # The dynamics of the dependent joints will be computed from the holonomic constraint
>     mapping.add("q", to_second=[0, None, None, 1], to_first=[0, 3])
> ```

[@pariterre](https://github.com/pariterre) What do you think of this?

-   Should we consider this as mapping
-   Should we put this script as a method in the BiorbdModelHolonomic?
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 207 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZamB0i2vw4sKWwE0SM:-NZamB0i2vw4sKWwE0SN:bb6ifnl) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/examples/holonomic_constraints/two_pendulums.py#L207)):*
> ```Python
> 
>     model_path = "models/two_pendulums.bioMod"
>     n_shooting = 10
> ```

30 ?
___
*[`bioptim/interfaces/variational_biomodel.py` line 65 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZaqN3w5DfseGwkOdKh:-NZaqN3w5DfseGwkOdKi:b55qg22) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/interfaces/variational_biomodel.py#L65)):*
> ```Python
> 
>         Sources
>         -------
> ```

Source
----
___
*[`bioptim/interfaces/biomodel_holonomic.py` line 310 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6S4PC0gMTJoK1n3Yx:-NZamv2o4LxfMxiP11El:b9c75e2) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/interfaces/biomodel_holonomic.py#L310)):*
<details><summary><i>Previously, 20chupin wrote…</i></summary><blockquote>

I did not do
compute_qddot_v(self, qddot_u: MX)  
compute_qddot(self, qddot_u: MX)
</blockquote></details>

Finally done.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 351 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZan2Yo2f2pSADhQ5qz:-NZan2Yo2f2pSADhQ5r-:b2niaki) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biomodel.py#L351)):*
> ```Python
>         """
> 
>     def compute_q_v(self, u: MX) -> MX:
> ```

q_u
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 474 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZanGFF5KI63lyJBMkg:-NZanGFF5KI63lyJBMkh:b2niaki) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biomodel.py#L474)):*
> ```Python
>         """
> 
>     def compute_q_v_numeric(self, u: DM, v_init=None) -> DM:
> ```

q_u
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 492 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZanPkf76OyFU70JGni:-NZanPkf76OyFU70JGnj:b-5khhzc) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biomodel.py#L492)):*
> ```Python
>         -------
>         DM
>             The numerical values of the dependent joint for a given independent joint state_u
> ```

q_v instead of state_u ?
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 495 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZanMb4AIMMPwvvRSDT:-NZanMb4AIMMPwvvRSDU:bb7l634) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biomodel.py#L495)):*
> ```Python
>         """
> 
>     def compute_the_Lagrangian_multiplier(
> ```

name
___
*[`bioptim/interfaces/holonomic_biorbd_model.py` line 257 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZaoTSyEWAdTNJ9lTl5:-NZaoTSyEWAdTNJ9lTl6:b-f6ebr2) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biorbd_model.py#L257)):*
> ```Python
>         https://doi.org/10.5194/ms-4-199-2013, 2013.
>         """
>         partitioned_constrained_jacobian = self.partitioned_constraints_jacobian(q)
> ```

partionned_constraints_jacobian
___
*[`bioptim/interfaces/holonomic_biorbd_model.py` line 275 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZao_AO27kxb4KM1CsA:-NZao_AO27kxb4KM1CsB:bb7od0r) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biorbd_model.py#L275)):*
> ```Python
>         The right term of the equation (15) in the paper.
>         """
>         partitioned_constrained_jacobian = self.partitioned_constraints_jacobian(q)
> ```

same
___
*[`bioptim/interfaces/holonomic_biorbd_model.py` line 392 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZap8aw2DvQnXc2iFp7:-NZap8aw2DvQnXc2iFp8:b-27dpv0) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biorbd_model.py#L392)):*
> ```Python
>         if f_contacts is not None:
>             raise NotImplementedError("Contact forces are not implemented yet.")
>         J = self.partitioned_constraints_jacobian(q)
> ```

J , name.
___
*[`bioptim/interfaces/holonomic_biorbd_model.py` line 406 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZapCAA8BVq0RglH9LG:-NZapCAA8BVq0RglH9LH:b-ks5nq5) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biorbd_model.py#L406)):*
> ```Python
>         non_linear_effect_v = non_linear_effect[self.nb_independent_joints :]
> 
>         Q = self.partitioned_tau(tau)
> ```

Q, name.
___
*[`bioptim/interfaces/variational_biorbd_model.py` line 107 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZaqhV57C1Zb6NMKoN4:-NZaqhV57C1Zb6NMKoN5:bh9ywnn) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/var [...]

2023-07-05 18:10 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 32 of 36 files reviewed, 17 unresolved discussions (waiting on @Ipuch)

___
*[`README.md` line 749 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZak7OF5exI1eqpuAcK:-NZbAxcb96SAbnke9DAr:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/README.md#L749)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

. You
</blockquote></details>

Done.
___
*[`README.md` line 760 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZakNUMC5f5lhKzpdXL:-NZbDwS50e7Wb-7cH-V5:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/README.md#L760)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Two dynamics are implemented in the Differential algebraic equations handling constraints at acceleration-level in forward_dynamics_constrained(...)
And the other was inspired by [robotran]() which uses index reduction methods to satisfy the constraints.
forward_dynamics_partitionned(...)

</blockquote></details>

Done.
___
*[`README.md` line 953 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZalLl37LfwaJSltjm8:-NZbEkADEifdKMeGRF2D:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/README.md#L953)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

add holonomicDynamics
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 207 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZamB0i2vw4sKWwE0SM:-NZbBChQ1wwbI140HEfl:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/examples/holonomic_constraints/two_pendulums.py#L207)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

30 ?
</blockquote></details>

Done.
___
*[`bioptim/interfaces/variational_biomodel.py` line 65 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZaqN3w5DfseGwkOdKh:-NZbD2JZ0q_PVMIVHheQ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/interfaces/variational_biomodel.py#L65)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Source
----
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel_holonomic.py` line 310 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6S4PC0gMTJoK1n3Yx:-NZbBEF27t_oiQLPkHeH:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/interfaces/biomodel_holonomic.py#L310)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Finally done.
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 351 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZan2Yo2f2pSADhQ5qz:-NZbBgj06BqoM8WCw88z:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biomodel.py#L351)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

q_u
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 474 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZanGFF5KI63lyJBMkg:-NZbBm2e12qtY59czfEV:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biomodel.py#L474)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

q_u
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 492 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZanPkf76OyFU70JGni:-NZbBzdh-D809u2vEfXe:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biomodel.py#L492)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

q_v instead of state_u ?
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 495 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZanMb4AIMMPwvvRSDT:-NZbC0NC3fAp8FaS3ez3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biomodel.py#L495)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

name
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biorbd_model.py` line 257 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZaoTSyEWAdTNJ9lTl5:-NZbCD394ZKacqdpRR-G:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biorbd_model.py#L257)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

partionned_constraints_jacobian
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biorbd_model.py` line 275 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZao_AO27kxb4KM1CsA:-NZbCDyp9U5Y5yNCs-Op:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biorbd_model.py#L275)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biorbd_model.py` line 392 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZap8aw2DvQnXc2iFp7:-NZbCSn268bRidagYzsX:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biorbd_model.py#L392)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

J , name.
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biorbd_model.py` line 406 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZapCAA8BVq0RglH9LG:-NZbCnMCA-P0qcqtnjYm:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/holonomic_biorbd_model.py#L406)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Q, name.
</blockquote></details>

Done.
___
*[`bioptim/interfaces/variational_biorbd_model.py` line 107 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZaqhV57C1Zb6NMKoN4:-NZbDL-h9p2peeddnjCi:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/interfaces/variational_biorbd_model.py#L107)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

else not implemented
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 21:16 UTC, Ipuch requested changes
> Reviewed 4 of 4 files at r17, 7 of 7 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 4 unresolved discussions (waiting on @20chupin)

___
*[`bioptim/gui/plot.py` line 360 at r18](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZbu0WU7SyaD4eFNB7x:-NZbu0WVCJzYsfeSkBnT:b32vmt) ([raw file](https://github.com/pyomeca/bioptim/blob/bfbf1a0f67635bb9d0eab320fbb904bd5998e91d/bioptim/gui/plot.py#L360)):*
> ```Python
>                     nlp.plot[key].phase_mappings = BiMapping(to_first=range(size), to_second=range(size))
>                     # else:
>                     #     size = len(nlp.plot[key].phase_mappings.to_second.map_idx)
> ```

??
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 495 at r18](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZbu8M91lTKXHxPzefq:-NZbu8M91lTKXHxPzefr:by79aq4) ([raw file](https://github.com/pyomeca/bioptim/blob/bfbf1a0f67635bb9d0eab320fbb904bd5998e91d/bioptim/interfaces/holonomic_biomodel.py#L495)):*
> ```Python
>         """
> 
>     def compute_the_lagrangian_multiplier(
> ```

multipliers ?


<!-- Sent from Reviewable.io -->

2023-07-06 14:35 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 4 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/gui/plot.py` line 360 at r18](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZbu0WU7SyaD4eFNB7x:-NZfbLDf-yIQ-8m6D5Qn:b43drl9) ([raw file](https://github.com/pyomeca/bioptim/blob/bfbf1a0f67635bb9d0eab320fbb904bd5998e91d/bioptim/gui/plot.py#L360)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

??
</blockquote></details>

Wooops! Done.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 495 at r18](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZbu8M91lTKXHxPzefq:-NZfbde08iMOgxepQY8A:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/bfbf1a0f67635bb9d0eab320fbb904bd5998e91d/bioptim/interfaces/holonomic_biomodel.py#L495)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

multipliers ?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-06 19:04 UTC, pariterre requested changes
> Reviewed 1 of 1 files at r4, 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 9 unresolved discussions (waiting on @20chupin and @Ipuch)

___
*[`bioptim/dynamics/configure_problem.py` line 610 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgWUOX0rFeosmN1F_Y:-NZgWUOYA0HKtjTUwYYz:b-qyd24x) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/dynamics/configure_problem.py#L610)):*
> ```Python
>         name = "qdot_u"
>         names_qdot = ConfigureProblem._get_kinematics_based_names(nlp, "qdot")
>         names_udot = [names_qdot[nlp.model.independent_joint_index[i]] for i in range(nlp.model.nb_independent_joints)]
> ```

this should be: `nlp.model.independent_state_index`

`nlp.state["q"].mapping.to_second`
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 154 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZasUa_4VXITLQ74SiC:-NZgPiXzAAVsx_R05APr:bfq3gd5) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/examples/holonomic_constraints/two_pendulums.py#L154)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

[@pariterre](https://github.com/pariterre) What do you think of this?

-   Should we consider this as mapping
-   Should we put this script as a method in the BiorbdModelHolonomic?
</blockquote></details>

Not sure 
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 135 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgOaRp8D3AArqPEBIu:-NZgOaRp8D3AArqPEBIv:b4mt4q0) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/examples/holonomic_constraints/two_pendulums.py#L135)):*
> ```Python
>     # The rotations (joint 0 and 3) are independent. The translations (joint 1 and 2) are constrained by the holonomic
>     # constraint
>     bio_model.set_dependencies(independent_joint_index=[0, 3], dependent_joint_index=[1, 2])
> ```

Find a way to merge this!
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 191 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgQS27CzGaCXrawHWm:-NZgQS27CzGaCXrawHWn:buvf492) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/examples/holonomic_constraints/two_pendulums.py#L191)):*
> ```Python
>             u_init=u_init,
>             x_bounds=x_bounds,
>             u_bounds=u_bounds,
> ```

Swap init and bounds
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 351 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgT1XP78nGbF1kLV0f:-NZgT1XP78nGbF1kLV0g:bh7ry3j) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/interfaces/holonomic_biomodel.py#L351)):*
> ```Python
>         """
> 
>     def compute_q_v(self, q_u: MX) -> MX:
> ```

`compute_q_v(self, q_u: MX | DM, v_init: MX | DM) -> MX | DM`
___
*[`bioptim/optimization/variational_optimal_control_program.py` line 115 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZg_5Xn7IyyoFMU-2jF:-NZg_5Xn7IyyoFMU-2jG:b-k8io4z) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/optimization/variational_optimal_control_program.py#L115)):*
> ```Python
>         # Declare parameters for the initial and final velocities
>         if "parameters" not in kwargs.keys() or kwargs["parameters"] is None:
>             kwargs["parameters"] = ParameterList()
> ```

Whenever you feel that you must check an element of "kwargs" and do something withit, then it is not kwargs, it is a parameter of the method:

```
def __init__(..., parameters=None,...):
...
if parameters is None:
    parameters = ....
...
super().__init__(..., parameters=parameters, ....)
```

Do this for all


<!-- Sent from Reviewable.io -->

2023-07-07 18:17 UTC, Ipuch requested changes
> Reviewed 13 of 19 files at r20, 10 of 10 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 9 unresolved discussions (waiting on @20chupin)

___
*[`bioptim/dynamics/configure_problem.py` line 610 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgWUOX0rFeosmN1F_Y:-NZlTGJK8D0MO-KUQKqC:b9lfe7f) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/dynamics/configure_problem.py#L610)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

this should be: `nlp.model.independent_state_index`

`nlp.state["q"].mapping.to_second`
</blockquote></details>

It works according to @20chupin !
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/example_variational_integrator_with_holonomic_constraints_pendulum.py` line 55 at r21](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZlTb6i7-gaa8eWibsJ:-NZlTb6i7-gaa8eWibsK:b-cccz82) ([raw file](https://github.com/pyomeca/bioptim/blob/9d75562cdded36ae3c41f0a986535ba0de534acb/bioptim/examples/discrete_mechanics_and_optimal_control/example_variational_integrator_with_holonomic_constraints_pendulum.py#L55)):*
> ```Python
>     ) = HolonomicConstraintsFcn.superimpose_markers(bio_model, marker_1="marker_1", index=slice(2, 3))
>     holonomic_constraints = HolonomicConstraintsList()
>     holonomic_constraints.add(
> ```

holonomic_constraints = HolonomicConstraintsList()
holonomic_constraints.add(HolonomicConstraintsFcn.superimpose_markers, marker_1 = "marker1", index=sliced(...))

bio_model.set_holonomic_configuration()

HolonomicBiorbdModel -> no holonomic constraint
HolonomicBiorbdModel -> holonomic constraints, no dependencies
HolonomicBiorbdModel -> no holonomic constraints, dependencies  not possible (raise)

bio_model.set_holonomic_configuration(
holonomic_constraints: HolonomicConstraintsList,
independent_joints: list = None,
dependent_joints: list = None,
)

explain why in NOTE why these indexes are not mandatory.

test if joint indexes are sorted.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 334 at r21](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZlXHD9C6_ygQdtiRVc:-NZlXHD9C6_ygQdtiRVd:bq8afn8) ([raw file](https://github.com/pyomeca/bioptim/blob/9d75562cdded36ae3c41f0a986535ba0de534acb/bioptim/interfaces/holonomic_biomodel.py#L334)):*
> ```Python
>         At the end of this step, we get admissible generalized coordinates w.r.t. the holonomic constraints
> 
>         !! Symbolic version of the function
> ```

comment.
___
*[`bioptim/interfaces/holonomic_constraints.py` line 120 at r21](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZlZ-Bc-IFAiw4zNQKq:-NZlZ-Bc-IFAiw4zNQKr:b-gva19g) ([raw file](https://github.com/pyomeca/bioptim/blob/9d75562cdded36ae3c41f0a986535ba0de534acb/bioptim/interfaces/holonomic_constraints.py#L120)):*
> ```Python
>         constraints: Function,
>         constraints_jacobian: Function,
>         constraints_double_derivative: Function,
> ```

    def add(
        self,
        key: str,
       HolonomicConstraintFcn,
      *kwarg,
    ):


<!-- Sent from Reviewable.io -->

2023-07-07 19:00 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: 29 of 36 files reviewed, 9 unresolved discussions (waiting on @Ipuch and @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 610 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgWUOX0rFeosmN1F_Y:-NZlg_4v63_uLiWF5q1e:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/dynamics/configure_problem.py#L610)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

It works according to @20chupin !
</blockquote></details>

Done.
___
*[`bioptim/examples/discrete_mechanics_and_optimal_control/example_variational_integrator_with_holonomic_constraints_pendulum.py` line 55 at r21](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZlTb6i7-gaa8eWibsJ:-NZlfILa011AaMEkyr7-:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9d75562cdded36ae3c41f0a986535ba0de534acb/bioptim/examples/discrete_mechanics_and_optimal_control/example_variational_integrator_with_holonomic_constraints_pendulum.py#L55)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

holonomic_constraints = HolonomicConstraintsList()
holonomic_constraints.add(HolonomicConstraintsFcn.superimpose_markers, marker_1 = "marker1", index=sliced(...))

bio_model.set_holonomic_configuration()

HolonomicBiorbdModel -> no holonomic constraint
HolonomicBiorbdModel -> holonomic constraints, no dependencies
HolonomicBiorbdModel -> no holonomic constraints, dependencies  not possible (raise)

bio_model.set_holonomic_configuration(
holonomic_constraints: HolonomicConstraintsList,
independent_joints: list = None,
dependent_joints: list = None,
)

explain why in NOTE why these indexes are not mandatory.

test if joint indexes are sorted.




</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 154 at r16](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZasUa_4VXITLQ74SiC:-NZgdA4D9F9tFbSNc9V7:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/64f2359a77f975a2d2a0d5fe0d5eeb9033fd24bc/bioptim/examples/holonomic_constraints/two_pendulums.py#L154)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Not sure 
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 135 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgOaRp8D3AArqPEBIu:-NZlgGzL89dy2dv1fmh0:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/examples/holonomic_constraints/two_pendulums.py#L135)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Find a way to merge this!
</blockquote></details>

Done.
___
*[`bioptim/examples/holonomic_constraints/two_pendulums.py` line 191 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgQS27CzGaCXrawHWm:-NZgdHQo8YCtJMaaEGHV:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/examples/holonomic_constraints/two_pendulums.py#L191)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Swap init and bounds
</blockquote></details>

Done.
___
*[`bioptim/interfaces/biomodel_holonomic.py` line 329 at r8](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZ6TbXZ-VkC5H8-jtDa:-NZgpGO11XUByeB33cDy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/93c0d0318e0b0f93236397a8bb9c97c5906e6e13/bioptim/interfaces/biomodel_holonomic.py#L329)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

But we are not satisfied with the fact we have numerical methods in the class. @pariterre do you have a better idea to handle this properly?
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 351 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZgT1XP78nGbF1kLV0f:-NZghgDoEiwq7BXHaPCk:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/interfaces/holonomic_biomodel.py#L351)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

`compute_q_v(self, q_u: MX | DM, v_init: MX | DM) -> MX | DM`
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_biomodel.py` line 334 at r21](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZlXHD9C6_ygQdtiRVc:-NZlgMex75IjQCdWi7qt:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9d75562cdded36ae3c41f0a986535ba0de534acb/bioptim/interfaces/holonomic_biomodel.py#L334)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

comment.
</blockquote></details>

Done.
___
*[`bioptim/interfaces/holonomic_constraints.py` line 120 at r21](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZlZ-Bc-IFAiw4zNQKq:-NZlgWY_-1AEREyqXobX:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/9d75562cdded36ae3c41f0a986535ba0de534acb/bioptim/interfaces/holonomic_constraints.py#L120)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

    def add(
        self,
        key: str,
       HolonomicConstraintFcn,
      *kwarg,
    ):

</blockquote></details>

Done.
___
*[`bioptim/optimization/variational_optimal_control_program.py` line 115 at r19](https://reviewable.io/reviews/pyomeca/bioptim/699#-NZg_5Xn7IyyoFMU-2jF:-NZgj9R6ASlkFOWEYIQq:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/ce291d6481bd636d209ea7352ff8b9a4bd5532a3/bioptim/optimization/variational_optimal_control_program.py#L115)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Whenever you feel that you must check an element of "kwargs" and do something withit, then it is not kwargs, it is a parameter of the method:

```
def __init__(..., parameters=None,...):
...
if parameters is None:
    parameters = ....
...
super().__init__(..., parameters=parameters, ....)
```

Do this for all
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-10 13:46 UTC, Ipuch approved these changes
> Reviewed 7 of 7 files at r22, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699)* status: all files reviewed, 5 unresolved discussions (waiting on @pariterre)



<!-- Sent from Reviewable.io -->

2023-07-11 13:07 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 2 of 2 files at r23, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/699#-:-N_43A3sCDT5kqwtSxFP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)



<!-- Sent from Reviewable.io -->

2023-07-11 14:02 UTC, merged