[RTM] Bug and BoundsList
pyomeca/bioptim pull request #703
Opened 2023-06-28 14:05 UTC by 20chupin

Corrects a bug when running `getting_started\pendulum.py` and check the bound is not defined twice or with the same name

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/703)

2023-07-05 17:50 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/703)* status: all files reviewed, 1 unresolved discussion (waiting on @Ipuch)

___
*[`bioptim/limits/path_conditions.py` line 654 at r1](https://reviewable.io/reviews/pyomeca/bioptim/703#-NZajdaH8ZwXQItCzgSK:-NZbAPkv3OptglJ45423:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/28893abe1aac23ebc46b1119de52ef2634af1eff/bioptim/limits/path_conditions.py#L654)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

If
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-05 21:16 UTC, Ipuch submitted a review, later dismissed
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/703)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)



<!-- Sent from Reviewable.io -->

2023-07-06 17:56 UTC, pariterre requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/703)* status: all files reviewed, 1 unresolved discussion (waiting on @20chupin)

___
*[`bioptim/limits/path_conditions.py` line 651 at r2](https://reviewable.io/reviews/pyomeca/bioptim/703#-NZgL1Kh73qKk1HsBQ-i:-NZgL1Kh73qKk1HsBQ-j:blbn01w) ([raw file](https://github.com/pyomeca/bioptim/blob/1b209e629afa21cc1cc442cceb3811ed3c0924a7/bioptim/limits/path_conditions.py#L651)):*
> ```Python
> 
>         if isinstance(item, str) and len(self.options) > 1:
>             raise TypeError(
> ```

This should appear in the parent using "self.type" to get the type of option, and this should also be in the `setter`


<!-- Sent from Reviewable.io -->

2023-07-06 18:22 UTC, 20chupin reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/703)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Ipuch and @pariterre)

___
*[`bioptim/limits/path_conditions.py` line 651 at r2](https://reviewable.io/reviews/pyomeca/bioptim/703#-NZgL1Kh73qKk1HsBQ-i:-NZgRKYE5E7qIuei-TmD:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/1b209e629afa21cc1cc442cceb3811ed3c0924a7/bioptim/limits/path_conditions.py#L651)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

This should appear in the parent using "self.type" to get the type of option, and this should also be in the `setter`
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-07-06 19:05 UTC, pariterre approved these changes
Tests?

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/703#-:-NZga88w2pGnNjyKFqZa:b-zdvn8d)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)



<!-- Sent from Reviewable.io -->

2023-07-06 19:10 UTC, 20chupin reviewed
They passed !

> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/703#-:-NZgbBKC7guIQeyasqey:b14abtw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @20chupin)



<!-- Sent from Reviewable.io -->

2023-07-06 19:11 UTC, merged