Not compute the defects if not in implicit
pyomeca/bioptim pull request #742
Opened 2023-08-05 17:33 UTC by EveCharbie

### All Submissions:

* [x] Have you followed the guidelines in our Contributing document [docs/contribution.md]?
* [x] Have you checked to ensure there aren't other open [Pull Requests] for the same update/change?
* [x] Have you opened/linked the issue related to your pull request?
* [x] Have you used the tag [WIP] for on-going changes, and removed it when the pull request was ready?
* [x] When ready to merge, have you sent a comment pinging @pariterre in it?

### New Feature Submissions:

1. [ ] Does your submission pass the tests (if not please explain why this is intended)?
2. [ ] Did you write a proper documentation (docstrings and ReadMe)
3. [ ] Have you linted your code locally prior to submission (using the command: `black . -l120 --exclude "external/*"`)?

### Changes to Core Features:

* [ ] Have you added an explanation of what your changes do and why you'd like us to include them?
* [ ] Have you written new examples for your core changes, as applicable?
* [ ] Have you written new tests for your core changes, as applicable?

2023-08-05 17:35 UTC, EveCharbie commented
Hoping this would decrease the RAM consumption when we are in explicit.
WARNING: there seems to be some tests missing for joint_acceleration_driven and implicit dynamics (issue #741) , so I don't know for sure if I did not break anything...

2023-08-07 07:22 UTC, EveCharbie commented
@pariterre this one would also be a good candidate to being merge, it will not create merge conflicts I think :)

2023-08-07 14:01 UTC, pariterre requested changes
Change back to ODE default 

> Reviewed 4 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/742#-:-NbFHmPXA0q72XPkbXZY:b-5zb24a)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

___
*[`bioptim/dynamics/dynamics_functions.py` line 151 at r2](https://reviewable.io/reviews/pyomeca/bioptim/742#-NbFH65dCuGx1gSMBOh1:-NbFH65e4_RV4cFbbh-N:bignhge) ([raw file](https://github.com/pyomeca/bioptim/blob/ee69ee520b24af8ecc61ef94b38bd348782bc0ab/bioptim/dynamics/dynamics_functions.py#L151)):*
> ```Python
>         defects = None
>         # TODO: contacts and fatigue to be handled with implicit dynamics
>         if rigidbody_dynamics is not None:
> ```

if rigid != RIGID.ODE:


<!-- Sent from Reviewable.io -->

2023-08-07 16:23 UTC, EveCharbie commented
@pariterre I don't think RigidBodyDynamics.ODE has the same meaning as None, I think it means compute defects = [qdot_from_states_dot - qdot, tau_from_inverse_dynamics - tau] 
It should be computed in test_muscle_driven_ocp_implicit.py.

Should I instead create another enum : RigidBodyDynamics.NO_DEFECTS ?

2023-08-10 14:31 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/742#-:-NbUqw142NljeYLzTLSq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2023-08-10 18:59 UTC, EveCharbie commented
Test does not pass on Windows, I will remove it. But here is the Error message for the future:

================================== FAILURES ===================================
____________ test_arm_reaching_torque_driven_implicit[False-False] ____________

with_cholesky = False, with_scaling = False

    @pytest.mark.parametrize("with_cholesky", [True, False])
    @pytest.mark.parametrize("with_scaling", [True, False])
    def test_arm_reaching_torque_driven_implicit(with_cholesky, with_scaling):
        from bioptim.examples.stochastic_optimal_control import arm_reaching_torque_driven_implicit as ocp_module
    
        final_time = 0.8
        n_shooting = 4
        ee_final_position = np.array([9.359873986980460e-12, 0.527332023564034])
    
        dt = 0.01
        motor_noise_std = 0.05
        wPq_std = 3e-4
        wPqdot_std = 0.0024
        motor_noise_magnitude = DM(np.array([motor_noise_std**2 / dt, motor_noise_std**2 / dt]))
        wPq_magnitude = DM(np.array([wPq_std**2 / dt, wPq_std**2 / dt]))
        wPqdot_magnitude = DM(np.array([wPqdot_std**2 / dt, wPqdot_std**2 / dt]))
        sensory_noise_magnitude = vertcat(wPq_magnitude, wPqdot_magnitude)
    
        bioptim_folder = os.path.dirname(ocp_module.__file__)
    
        ocp = ocp_module.prepare_socp(
            biorbd_model_path=bioptim_folder + "/models/LeuvenArmModel.bioMod",
            final_time=final_time,
            n_shooting=n_shooting,
            ee_final_position=ee_final_position,
            motor_noise_magnitude=motor_noise_magnitude,
            sensory_noise_magnitude=sensory_noise_magnitude,
            with_cholesky=with_cholesky,
            with_scaling=with_scaling,
        )
    
        # Solver parameters
        solver = Solver.IPOPT(show_online_optim=False)
        solver.set_maximum_iterations(4)
        solver.set_nlp_scaling_method("none")
    
>       sol = ocp.solve(solver)

tests\shard3\test_global_stochastic.py:568: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
bioptim\optimization\optimal_control_program.py:1591: in solve
    self.ocp_solver.solve()
bioptim\interfaces\ipopt_interface.py:97: in solve
    return generic_solve(self)
bioptim\interfaces\interface_utils.py:58: in generic_solve
    interface.ocp_solver = nlpsol("solver", interface.solver_name.lower(), interface.sqp_nlp, options)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = ('solver', 'ipopt', {'f': MX(@1=0x1, mac(ones(1x15),vertcat(MINIMIZE_CONTROL(X_scaled_0_0, U_scaled_0_0, @1, S_scaled_...acceptable_constr_viol_tol': 0.01, 'ipopt.acceptable_dual_inf_tol': 10000000000.0, 'ipopt.acceptable_tol': 1e-06, ...})

    def nlpsol(*args) -> "casadi::Function":
        """
          [INTERNAL]
    
        ::
    
          nlpsol(str name, str solver, Importer compiler, dict opts) -> Function
          nlpsol(str name, str solver, NlpBuilder nl, dict opts) -> Function
          nlpsol(str name, str solver, dict:SX nlp, dict opts) -> Function
          nlpsol(str name, str solver, dict:MX nlp, dict opts) -> Function
          nlpsol(str name, str solver, str fname, dict opts) -> Function
    
    
        .......
    
        ::
    
          nlpsol(str name, str solver, dict:SX nlp, dict opts)
    
    
    
        [INTERNAL]
    
        Create an NLP solver Creates a solver for the following parametric
    
        nonlinear program (NLP):
    
        ::
    
          min          F(x, p)
          x
    
          subject to
          LBX <=   x    <= UBX
          LBG <= G(x, p) <= UBG
          p  == P
    
          nx: number of decision variables
          ng: number of constraints
          np: number of parameters
    
        General information
    
        >List of available options
    
        +------------------+-----------------+------------------+------------------+
        |        Id        |      Type       |   Description    |     Used in      |
        +==================+=================+==================+==================+
        | ad_weight        | OT_DOUBLE       | Weighting factor | casadi::Function |
        |                  |                 | for derivative   | Internal         |
        |                  |                 | calculation.When |                  |
        |                  |                 | there is an      |                  |
        |                  |                 | option of either |                  |
        |                  |                 | using forward or |                  |
        |                  |                 | reverse mode     |                  |
        |                  |                 | directional      |                  |
        |                  |                 | derivatives, the |                  |
        |                  |                 | condition ad_wei |                  |
        |                  |                 | ght*nf<=(1-      |                  |
        |                  |                 | ad_weight)*na is |                  |
        |                  |                 | used where nf    |                  |
        |                  |                 | and na are       |                  |
        |                  |                 | estimates of the |                  |
        |                  |                 | number of        |                  |
        |                  |                 | forward/reverse  |                  |
        |                  |                 | mode directional |                  |
        |                  |                 | derivatives      |                  |
        |                  |                 | needed. By       |                  |
        |                  |                 | default,         |                  |
        |                  |                 | ad_weight is     |                  |
        |                  |                 | calculated       |                  |
        |                  |                 | automatically,   |                  |
        |                  |                 | but this can be  |                  |
        |                  |                 | overridden by    |                  |
        |                  |                 | setting this     |                  |
        |                  |                 | option. In       |                  |
        |                  |                 | particular, 0    |                  |
        |                  |                 | means forcing    |                  |
        |                  |                 | forward mode and |                  |
        |                  |                 | 1 forcing        |                  |
        |                  |                 | reverse mode.    |                  |
        |                  |                 | Leave unset for  |                  |
        |                  |                 | (class specific) |                  |
        |                  |                 | heuristics.      |                  |
        +------------------+-----------------+------------------+------------------+
        | ad_weight_sp     | OT_DOUBLE       | Weighting factor | casadi::Function |
        |                  |                 | for sparsity     | Internal         |
        |                  |                 | pattern          |                  |
        |                  |                 | calculation calc |                  |
        |                  |                 | ulation.Override |                  |
        |                  |                 | s default        |                  |
        |                  |                 | behavior. Set to |                  |
        |                  |                 | 0 and 1 to force |                  |
        |                  |                 | forward and      |                  |
        |              [...]

2023-08-11 07:05 UTC, EveCharbie commented
@pariterre can be merged :)

2023-08-11 13:37 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 3 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/742#-:-NbZoG3E9_2Mf_QHLwHj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2023-08-11 13:37 UTC, merged