[WIP] Needed to merge the two PRs here
pyomeca/bioptim pull request #867
Opened 2024-03-29 22:12 UTC by EveCharbie

2024-04-03 00:09 UTC, EveCharbie commented
The only problem is RigidBodyDynamics.DAE_INVERSE_DYNAMICS for test_maximize_predicted_height_CoM_rigidbody_dynamics.
@pariterre or @Ipuch could you tell me if this is a normal behavior (knowing that the max_iter is set to 1)?

2024-04-03 13:19 UTC, pariterre commented
@EveCharbie 
I have never seen this particular test fail before. Therefore, I do not expect this test to be a sensitive test

2024-04-04 16:15 UTC, pariterre requested changes
> Reviewed 59 of 66 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/867)* status: all files reviewed, 120 unresolved discussions (waiting on @EveCharbie)

___
*[`bioptim/dynamics/configure_problem.py` line 167 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudfffj4R3YLdFqXkEb:-Nudfffk-NIdRM1e0KbP:b-4olu7c) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L167)):*
> ```Python
>         soft_contacts_dynamics: SoftContactDynamics = SoftContactDynamics.ODE,
>         fatigue: FatigueList = None,
>         dynamics_constants_used_at_each_nodes: dict[list] = {},
> ```

Must be a None
if None: skip
___
*[`bioptim/dynamics/configure_problem.py` line 192 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudb4fh1B2sU3PCl3MZ:-Nudb4fh1B2sU3PCl3M_:b1r4rpv) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L192)):*
> ```Python
>         fatigue: FatigueList
>             A list of fatigue elements
>         dynamics_constants_used_at_each_nodes: dict[np.ndarray]
> ```

numerical_data_timeseries: dict[str, np.ndarray]
___
*[`bioptim/dynamics/configure_problem.py` line 205 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NuddfUgAQyQ6tmb8QaZ:-NuddfUgAQyQ6tmb8Qa_:b-v5pk8o) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L205)):*
> ```Python
>                 raise RuntimeError(
>                     "The only dynamics_constants_used_at_each_nodes allowed for torque_driven dynamics is external_forces."
>                 )
> ```

just `continue`
___
*[`bioptim/dynamics/configure_problem.py` line 322 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nuddur09_FNgU_PIoBI:-Nuddur09_FNgU_PIoBJ:btrojj4) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L322)):*
> ```Python
>         with_ligament: bool = False,
>         with_friction: bool = False,
>         dynamics_constants_used_at_each_nodes: dict[list] = {},
> ```

= None
___
*[`bioptim/dynamics/configure_problem.py` line 448 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudfvUG8FshwcRS_0gD:-NudfvUG8FshwcRS_0gE:bnvg19m) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L448)):*
> ```Python
>         with_cholesky: bool = False,
>         initial_matrix: DM = None,
>         dynamics_constants_used_at_each_nodes: dict[list] = {},
> ```

= None
___
*[`bioptim/dynamics/configure_problem.py` line 531 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudfwKtATWEcDzkmkYr:-NudfwKtATWEcDzkmkYs:bnvg19m) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L531)):*
> ```Python
>         with_cholesky: bool = False,
>         initial_matrix: DM = None,
>         dynamics_constants_used_at_each_nodes: dict[list] = {},
> ```

= None
___
*[`bioptim/dynamics/configure_problem.py` line 608 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudfxPZ9yO5W2lSSUi6:-NudfxPZ9yO5W2lSSUi7:bnvg19m) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L608)):*
> ```Python
>         rigidbody_dynamics: RigidBodyDynamics = RigidBodyDynamics.ODE,
>         soft_contacts_dynamics: SoftContactDynamics = SoftContactDynamics.ODE,
>         dynamics_constants_used_at_each_nodes: dict[list] = {},
> ```

= None
___
*[`bioptim/dynamics/configure_problem.py` line 708 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudfyzI8HlOLzJ-SE0v:-NudfyzI8HlOLzJ-SE0w:bnvg19m) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L708)):*
> ```Python
>         with_residual_torque: bool = False,
>         with_ligament: bool = False,
>         dynamics_constants_used_at_each_nodes: dict[list] = {},
> ```

= None
___
*[`bioptim/dynamics/configure_problem.py` line 777 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudg-N50S0lqX8wPoOF:-Nudg-N50S0lqX8wPoOG:bnvg19m) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L777)):*
> ```Python
>         nlp,
>         rigidbody_dynamics: RigidBodyDynamics = RigidBodyDynamics.ODE,
>         dynamics_constants_used_at_each_nodes: dict[list] = {},
> ```

= None
___
*[`bioptim/dynamics/configure_problem.py` line 839 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudg5QyBfnVnu2Hc4Lx:-Nudg5QyBfnVnu2Hc4Ly:bnvg19m) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L839)):*
> ```Python
>         with_ligament: bool = False,
>         rigidbody_dynamics: RigidBodyDynamics = RigidBodyDynamics.ODE,
>         dynamics_constants_used_at_each_nodes: dict[list] = {},
> ```

= None
___
*[`bioptim/dynamics/configure_problem.py` line 930 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudgCDO9bsovovCNMrW:-NudgCDO9bsovovCNMrX:bnvg19m) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L930)):*
> ```Python
> 
>     @staticmethod
>     def holonomic_torque_driven(ocp, nlp, dynamics_constants_used_at_each_nodes: dict[list] = {}):
> ```

= None
___
*[`bioptim/dynamics/configure_problem.py` line 1000 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudgH_ODeolBasWVFsF:-NudgH_ODeolBasWVFsG:b3ksf) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1000)):*
> ```Python
>                 ],
>                 [dynamics_dxdt],
>                 ["t_span", "x", "u", "p", "a", "dynamics_constants"],
> ```

d
___
*[`bioptim/dynamics/configure_problem.py` line 1018 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudhHUw2-YEYeDUrcG7:-NudhHUw2-YEYeDUrcG8:b-8jphnh) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1018)):*
> ```Python
>                     )
> 
>             # Only possible for regular dynamics, not for extra_dynamics
> ```

to be removed
___
*[`bioptim/dynamics/configure_problem.py` line 1032 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudhIRUCAQGf3C7pCJ9:-NudhIRUCAQGf3C7pCJA:b3ksf) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1032)):*
> ```Python
>                     ],
>                     [dynamics_eval.defects],
>                     ["t_span", "x", "u", "p", "a", "dynamics_constants", "xdot"],
> ```

d
___
*[`bioptim/dynamics/configure_problem.py` line 1060 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudhJp6E7zI6Vjr3Fji:-NudhJp6E7zI6Vjr3Fjj:b3ksf) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1060)):*
> ```Python
>                     ],
>                     [dynamics_dxdt],
>                     ["t_span", "x", "u", "p", "a", "dynamics_constants"],
> ```

d
___
*[`bioptim/dynamics/configure_problem.py` line 1065 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudhYPj9oy7PqH_sj25:-NudhYPj9oy7PqH_sj26:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1065)):*
> ```Python
>             )
> 
>             # TODO: allow expand for each dynamics independently
> ```

Done
___
*[`bioptim/dynamics/configure_problem.py` line 1068 at r2](https [...]

2024-04-05 01:12 UTC, EveCharbie reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/867)* status: all files reviewed, 120 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 167 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudfffj4R3YLdFqXkEb:-NufMrjn8t5Ly4sLWrUv:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L167)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Must be a None
if None: skip
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 192 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudb4fh1B2sU3PCl3MZ:-NufLT8kEGq6u-W9AkiS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L192)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

numerical_data_timeseries: dict[str, np.ndarray]
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 205 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NuddfUgAQyQ6tmb8QaZ:-NufNdHLCEXpQjXaPWlC:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L205)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

just `continue`
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 322 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nuddur09_FNgU_PIoBI:-NufNj5l0H3CtChhdShm:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L322)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

= None
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 448 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudfvUG8FshwcRS_0gD:-NufNjdq1sEBABbFEniQ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L448)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

= None
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 531 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudfwKtATWEcDzkmkYr:-NufNk3C9FCulb9jIyUF:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L531)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

= None
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 608 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudfxPZ9yO5W2lSSUi6:-NufNkTV0muz24EY0eh_:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L608)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

= None
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 708 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudfyzI8HlOLzJ-SE0v:-NufNks3-5aDbg9R8NS-:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L708)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

= None
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 777 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudg-N50S0lqX8wPoOF:-NufNlJC5qzKYB6_AxHe:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L777)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

= None
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 839 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudg5QyBfnVnu2Hc4Lx:-NufNlhBCTT-p-nF443x:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L839)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

= None
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 930 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudgCDO9bsovovCNMrW:-NufNqs_-sv8dcl3vOJr:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L930)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

= None
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 1000 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudgH_ODeolBasWVFsF:-NufNxG11bS1wIugLbeA:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1000)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

d
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 1018 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudhHUw2-YEYeDUrcG7:-NufOPW31VtfpoX4ex8n:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1018)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

to be removed
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 1032 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudhIRUCAQGf3C7pCJ9:-NufOQMY4Buz_fsn_HgS:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1032)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

d
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 1060 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudhJp6E7zI6Vjr3Fji:-NufOQy87l4OA94F6_Du:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1060)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

d
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 1065 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-NudhYPj9oy7PqH_sj25:-NufOSJE1NPu0SJg1iaK:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1065)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 1068 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudhn2Q5-kC1lvp3gpl:-NufOZlQCHUh_-tejrK0:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1068)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

that is a bit convoluted for a name
</blockquote></details>

Done.
___
*[`bioptim/dynamics/configure_problem.py` line 1117 at r2](https://reviewable.io/reviews/pyomeca/bioptim/867#-Nudhv1C3yg-T-Ig-sQN:-NufO_V_AuJHtbKtG1zD:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/452ffa385719aba6f0654bfbb28d5fc1a6f2bc35/bioptim/dynamics/configure_problem.py#L1117)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

d
</blockquote></details>
 [...]

2024-04-05 13:00 UTC, pariterre requested changes
> Reviewed 43 of 43 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/867)* status: all files reviewed, 1 unresolved discussion (waiting on @EveCharbie)

___
*[`bioptim/dynamics/configure_problem.py` line 971 at r3](https://reviewable.io/reviews/pyomeca/bioptim/867#-NuiGVf80Ze20r1x18LZ:-NuiGVf80Ze20r1x18L_:b2y4an) ([raw file](https://github.com/pyomeca/bioptim/blob/b9627f9c5d07e8e95db5bf70e6bc37c8d35e3f7a/bioptim/dynamics/configure_problem.py#L971)):*
> ```Python
>             nlp.parameters.scaled.mx_reduced,
>             nlp.algebraic_states.scaled.mx_reduced,
>             nlp.numerical_timeseries.mx,
> ```

should we be consistent (numerical_data_timeseries vs numerical_timeseries) ? Or there was a reason to have these two names. I suspect it was based on mistake I've made in the comments yesterday...
That said, I think `numerical_data_timeseries` is too long... maybe we can drop the "data"


<!-- Sent from Reviewable.io -->

2024-04-05 13:04 UTC, EveCharbie reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/867)* status: all files reviewed, 1 unresolved discussion (waiting on @pariterre)

___
*[`bioptim/dynamics/configure_problem.py` line 971 at r3](https://reviewable.io/reviews/pyomeca/bioptim/867#-NuiGVf80Ze20r1x18LZ:-NuiLXo66qJATVklquj-:b-9koqws) ([raw file](https://github.com/pyomeca/bioptim/blob/b9627f9c5d07e8e95db5bf70e6bc37c8d35e3f7a/bioptim/dynamics/configure_problem.py#L971)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

should we be consistent (numerical_data_timeseries vs numerical_timeseries) ? Or there was a reason to have these two names. I suspect it was based on mistake I've made in the comments yesterday...
That said, I think `numerical_data_timeseries` is too long... maybe we can drop the "data"
</blockquote></details>

No, it's because I wanted to discriminate between numerical_data_timeseries the actual np.array data provided by the user and numerical_timeseries the symbolic variables. I have to stock both values in nlp and I found it less confusing to have two different names.


<!-- Sent from Reviewable.io -->

2024-04-05 13:31 UTC, pariterre submitted a review, later dismissed
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/867)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2024-04-05 15:43 UTC, EveCharbie commented
@pariterre ready to merge :)

2024-04-05 22:07 UTC, pariterre approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 5 of 5 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/867#-:-NukIMg10VobdrbWN1PW:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @EveCharbie)



<!-- Sent from Reviewable.io -->

2024-04-05 22:07 UTC, merged