[RTM] New plotting!
pyomeca/bioptim pull request #887
Opened 2024-08-01 15:16 UTC by pariterre

New way of plotting using a server B-)

- - -
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/pyomeca/bioptim/887)

2024-08-01 19:35 UTC, Ipuch requested changes
Great ! 

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/887#-:-O3ER7aaA2RPU-zdc55d:b-ufm0y1)* status: all files reviewed, 37 unresolved discussions (waiting on @pariterre)

___
*[`README.md` line 794 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E79049oqG4-PwvvnH:-O3E79049oqG4-PwvvnI:b15pd37) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/README.md#L794)):*
> ```Markdown
> One can refer to their respective solver's documentation to know which options exist.
> The `show_online_optim` parameter can be set to `True` so the graphs nicely update during the optimization.
> Please note that `ShowOnlineType.MULTIPROCESS` is not available on Windows. To see how to run the server on Windows, please refer to the `getting_started/pendulum.py` example.
> ```

ShowOnlineType.MULTITHREAD ?
___
*[`README.md` line 798 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E7JGm9TBvkrrXi8bh:-O3E7JGm9TBvkrrXi8bi:bb7i16w) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/README.md#L798)):*
> ```Markdown
> `show_options` can be also passed as a dict to the plotter to customize the plotter's behavior.
> The following keys are special options:
>   - `type`: the type of plotter to use (default is `ShowOnlineType.MULTIPROCESS`)
> ```

idem



_Code quote:_
```Markdown
ShowOnlineType.MULTIPROCESS
```
___
*[`README.md` line 1692 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E8MyUBLgictTTnEan:-O3E8MyUBLgictTTnEao:br21xku) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/README.md#L1692)):*
> ```Markdown
> 
> The accepted values are:
> MULTIPROCESS: The online plotter is in a separate process.
> ```

MULTITHREAD
___
*[`bioptim/examples/getting_started/pendulum.py` line 155 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E90QR18I8bjyqWmRl:-O3E90QR18I8bjyqWmRm:br21xku) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/examples/getting_started/pendulum.py#L155)):*
> ```Python
>     # --- Solve the ocp --- #
>     if platform.system() == "Windows":
>         # The default online type (ShowOnlineType.MULTIPROCESS) is not available on Windows
> ```

MULTITHREAD
___
*[`bioptim/examples/getting_started/pendulum.py` line 157 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E9D9zAPHz5_7YEFnp:-O3E9D9zAPHz5_7YEFnq:bl3vjh3) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/examples/getting_started/pendulum.py#L157)):*
> ```Python
>         # The default online type (ShowOnlineType.MULTIPROCESS) is not available on Windows
>         # Since `as_multiprocess` default value is True, it will automatically starts the server in the background
>         solver = Solver.IPOPT(show_online_optim=True, show_options={"type": ShowOnlineType.SERVER})
> ```

OnlineOptim.None # False
OnlineOptim.MULTIPROCESS
OnlineOptim.DEFAULT # True, specific for each Plateform !
OnlineOptim.MULTIPROCESS_SERVER
OnlineOptim.SERVER
___
*[`bioptim/gui/online_callback_multiprocess.py` line 60 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3ECX72-w7S9XfEkCXV:-O3ECX72-w7S9XfEkCXW:b-h4g1z5) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_multiprocess.py#L60)):*
> ```Python
>             The multiprocessing queue to evaluate
>         plot: PlotOcp
>             The handler on all the figures
> ```

you can update



_Code quote:_
```Python
        pipe: mp.Queue
            The multiprocessing queue to evaluate
        plot: PlotOcp
            The handler on all the figures
```
___
*[`bioptim/gui/online_callback_multiprocess.py` line 118 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EDdf39LpiSYpjYUVc:-O3EDdf39LpiSYpjYUVd:b-2bbvo7) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_multiprocess.py#L118)):*
> ```Python
>             for fig in self._plotter.all_figures:
>                 fig.canvas.draw()
>             if [plt.fignum_exists(fig.number) for fig in self._plotter.all_figures].count(True) > 0:
> ```

has_at_least_one_active_figure =



_Code quote:_
```Python
[plt.fignum_exists(fig.number) for fig in self._plotter.all_figures].count(True)
```
___
*[`bioptim/gui/online_callback_server.py` line 18 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EE9jpDXmNcUp2Itso:-O3EE9jpDXmNcUp2Itsp:b-hu06mv) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L18)):*
> ```Python
> 
> 
> _default_host = "localhost"
> ```

_DEFAULT_HOST + _DEFAULT_PORT
___
*[`bioptim/gui/online_callback_server.py` line 42 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EEL2EAqrSy9Ip9RhD:-O3EEL2EAqrSy9Ip9RhE:bmaob48) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L42)):*
> ```Python
> 
> 
> class _ServerMessages(Enum):
> ```

EnumInt ?
___
*[`bioptim/gui/online_callback_server.py` line 95 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EGVe686zDycQtsjnj:-O3EGVe686zDycQtsjnk:b-g92zzp) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L95)):*
> ```Python
> 
>     @staticmethod
>     def as_multiprocess(*args, **kwargs) -> None:
> ```

A class would abstract better the behavior. -> "PlottingMultiProcessServer"
___
*[`bioptim/gui/online_callback_server.py` line 105 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EGRUY3SG7KEJk9mjb:-O3EGRUZCPQRj-3lTeNG:b-v82nyj) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L105)):*
> ```Python
>         from multiprocessing import Process
> 
>         thread = Process(target=_start_as_multiprocess_internal, args=args, kwargs=kwargs)
> ```

process = ...
___
*[`bioptim/gui/online_callback_server.py` line 110 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EGmkGEB8GSFBFeTSE:-O3EGmkGEB8GSFBFeTSF:b-sgutay) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L110)):*
> ```Python
>     def _run(self) -> None:
>         """
>         Starts the server, this method can be called directly by the user to start a plot server
> ```

update doc
___
*[`bioptim/gui/online_callback_server.py` line 154 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EHsEd05DiCqgxMSaF:-O3EHsEd05DiCqgxMSaG:bqkqksu) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L154)):*
> ```Python
>             self._logger.warning("Client closed connexion")
>             client_socket.close()
>             return _ServerMessages.CLOSE_CONNEXION, None
> ```

get_data_length()



_Code quote:_
```Python
        # Receive the actual data
        try:
            self._logger.debug("Waiting for data from client")
            data = client_socket.recv(1024)
            if not data:
                return _ServerMessages.EMPTY, None
        except:
            self._logger.warning("Client closed connexion")
            client_socket.close()
            return _ServerMessages.CLOSE_CONNEXION, None
```
___
*[`bioptim/gui/online_callback_server.py` line 168 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EI7_z1ec-0HiZOPsW:-O3EI7_z1ec-0HiZOPsX:bcv6mt7) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L168)):*
> ```Python
>                 data_out.append(client_socket.recv(len_data))
>                 if len(data_out[- [...]

2024-08-01 19:37 UTC, Ipuch requested changes
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/887)* status: all files reviewed, 37 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/gui/online_callback_server.py` line 513 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EMDwX9oHCj0q7gVEE:-O3ERREn3e1xMFaihakc:b-7vqsxb) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L513)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Put it into a function called "xydata_encoder" with "xydata_decoder" up there ideal for testing !
</blockquote></details>

Add a test for encoding decoding part.


<!-- Sent from Reviewable.io -->

2024-08-01 21:24 UTC, pariterre reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/887)* status: all files reviewed, 37 unresolved discussions (waiting on @Ipuch)

___
*[`README.md` line 794 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E79049oqG4-PwvvnH:-O3EkFjO1UVQCI83oX_l:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/README.md#L794)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

ShowOnlineType.MULTITHREAD ?
</blockquote></details>

Done.
___
*[`README.md` line 798 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E7JGm9TBvkrrXi8bh:-O3EkFK07t-LPjQN39JV:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/README.md#L798)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

idem
</blockquote></details>

Done.
___
*[`README.md` line 1692 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E8MyUBLgictTTnEan:-O3EkEq24uE5tmlSCArd:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/README.md#L1692)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

MULTITHREAD
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/pendulum.py` line 155 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E90QR18I8bjyqWmRl:-O3EkE878LSpSRP7yDtO:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/examples/getting_started/pendulum.py#L155)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

MULTITHREAD
</blockquote></details>

Done.
___
*[`bioptim/examples/getting_started/pendulum.py` line 157 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3E9D9zAPHz5_7YEFnp:-O3EkDLRBSqwHC8ibDA3:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/examples/getting_started/pendulum.py#L157)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

OnlineOptim.None # False
OnlineOptim.MULTIPROCESS
OnlineOptim.DEFAULT # True, specific for each Plateform !
OnlineOptim.MULTIPROCESS_SERVER
OnlineOptim.SERVER
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_multiprocess.py` line 60 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3ECX72-w7S9XfEkCXV:-O3ElF1W2g_Ns01IgNQ2:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_multiprocess.py#L60)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

you can update
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_multiprocess.py` line 118 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EDdf39LpiSYpjYUVc:-O3ElWrPDKXGBChW7Z42:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_multiprocess.py#L118)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

has_at_least_one_active_figure =
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 18 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EE9jpDXmNcUp2Itso:-O3ElnEzDb6_yP-rhAs_:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L18)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

_DEFAULT_HOST + _DEFAULT_PORT
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 42 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EEL2EAqrSy9Ip9RhD:-O3EmCii842eBhcL5pvW:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L42)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

EnumInt ?
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 95 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EGVe686zDycQtsjnj:-O3Emu-n7XW-_blFRpBp:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L95)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

A class would abstract better the behavior. -> "PlottingMultiProcessServer"
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 105 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EGRUY3SG7KEJk9mjb:-O3EmuYA68aOpm3bV-IX:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L105)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

process = ...
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 110 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EGmkGEB8GSFBFeTSE:-O3En-y12aQwuk3Xn4PJ:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L110)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

update doc
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 256 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EIgh08JdHMNnzRx2t:-O3En2Ai0H9TWiESDhEy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L256)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

has_at_least_one_active_plot =
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 291 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EJ5CXAWY2Azammlym:-O3En6x68pflcvavoJFy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L291)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

message_type in (Enum1, Enum2)
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 298 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EJXK1EppC-IyNyLtQ:-O3EnLsiETguCzFhQSJo:bme97kn) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L298)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

jsonlike_data ?
</blockquote></details>

serialized_raw_data
___
*[`bioptim/gui/online_callback_server.py` line 305 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EKJ5j2wIpd9qjKBez:-O3EnaMd6MfAzdLDrlFN:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L305)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

see Also ?
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 435 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3ELODcCl_Q_D-7Poqr:-O3EnbuF-fvQkiwyqzGy:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L435)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Done
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 458 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3ELaZe4IprOow6v2nL:-O3Enf6v3gobjVWhP2Of:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea492884 [...]

2024-08-02 15:16 UTC, pariterre reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/887)* status: 1 of 30 files reviewed, 37 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/gui/online_callback_server.py` line 154 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EHsEd05DiCqgxMSaF:-O3I7xXG2LTyv-cMWppo:b-7dagmy) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L154)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

get_data_length()
</blockquote></details>

Separated in two subfunctions
___
*[`bioptim/gui/online_callback_server.py` line 168 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EI7_z1ec-0HiZOPsW:-O3IBw9rBY3pHSe5BMIu:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L168)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Can go with the function above
</blockquote></details>

Done.
___
*[`bioptim/gui/online_callback_server.py` line 513 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3EMDwX9oHCj0q7gVEE:-O3IdecG4zFMGgBDXm17:b-896fix) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L513)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

Add a test for encoding decoding part.
</blockquote></details>

Done.
___
*[`bioptim/gui/plot.py` line 455 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3ENHSKEgdeowPNuxTV:-O3IePVr7r4RWofTY2_f:b-z91eus) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/plot.py#L455)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

def initializes_all_axes(...)
</blockquote></details>

This part actually defines 4 different variables needed later. I feel unconfortable moving this part without proper testing


<!-- Sent from Reviewable.io -->

2024-08-02 15:33 UTC, Ipuch reviewed
> Reviewed 20 of 28 files at r2, 11 of 11 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/887)* status: all files reviewed, 2 unresolved discussions (waiting on @pariterre)

___
*[`bioptim/gui/online_callback_server.py` line 435 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3ELODcCl_Q_D-7Poqr:-O3Ig9yN-6ZDT-g-7OI9:brehwmw) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L435)):*
<details><summary><i>Previously, pariterre (Pariterre) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The comment wasn't supposed to be gone ?


<!-- Sent from Reviewable.io -->

2024-08-05 13:35 UTC, pariterre reviewed
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/887)* status: all files reviewed, 2 unresolved discussions (waiting on @Ipuch)

___
*[`bioptim/gui/online_callback_server.py` line 435 at r1](https://reviewable.io/reviews/pyomeca/bioptim/887#-O3ELODcCl_Q_D-7Poqr:-O3Xjt_B1NOWAIQhfU63:bb6un1j) ([raw file](https://github.com/pyomeca/bioptim/blob/4f4173c58456f5fb7ea4928846fd58b03aa12371/bioptim/gui/online_callback_server.py#L435)):*
<details><summary><i>Previously, Ipuch (Pierre Puchaud) wrote…</i></summary><blockquote>

The comment wasn't supposed to be gone ?
</blockquote></details>

Done


<!-- Sent from Reviewable.io -->

2024-08-05 14:47 UTC, Ipuch approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pyomeca/bioptim/887#-:-O3Y-cID9hjkQ6iKciZf:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @pariterre)



<!-- Sent from Reviewable.io -->

2024-08-05 14:47 UTC, merged